### ISSUE TITLE
Consider exposing a unique user handle to the grains

### ISSUE THREAD

**Issue by mquandalle** [sandstorm-io/sandstorm#1027]
Hi,

I believe being able to mentions users using a @mention is a expectable pattern in quite a few collaborative Sandstorm applications. The Sandstorm http-bridge currently exposes a `X-Sandstorm-Preferred-Handle` for that purpose that has two documented “weakness” (1) a user can change their preferred handle at any time and (2) the handle is not unique, “it is only a hint from the user“.

I’m fine with the first point because this is also how other users informations behaves (name, avatar, etc.) and that is useful feature from a user point of view, but I tend to think that Sandstorm should enforce handle uniqueness:
- to make the app job easier (which is one side of the motivation for Sandstorm to handle the user management) and give it directly the user mention handle and not just a hint
- to ensure name consistency across grains, currently since the grain has to manage these itself it will have to create handles like `maxime`, `maxime2`, `maxime3` but if in another grain of the same application `maxime3` joins before `maxime2`, then `maxime2` of grain 1 will be `maxime3` of grain 2 and reciprocally which is a kind of a mess

Is there any rationale for not enforcing uniqueness here?

**Comment by ocdtrekkie** [comment]
As a 'preferred' handle, I think it's appropriate for the app to require it be unique within that grain. Your unique identifier remains the (X-Sandstorm-User-ID one (I think that's what its called).

**Comment by mquandalle** [comment]
My point is that I would like Sandstorm to expose a unique handle to be able to @mention users in a consistent way across grains.

**Comment by ocdtrekkie** [comment]
The problem is that the likelihood of a collision is extremely low in any given community on one grain. But the likelihood of collision across a major Sandstorm host like Oasis is very high.

**Comment by paulproteus** [comment]
(I took the liberty of fixing what I believe was a typo, "handle" <=> "handler", in the issue title here. Please restore to the old value if you know if that's not what you want!)

**Comment by mquandalle** [comment]
<not-native-english-speaker-here> ;-)

**Comment by zarvox** [comment]
Keep in mind that all of the things that are specific to login and unique identity must also work identically on any server, so you can download a grain backup and restore it elsewhere.  If my server has granted `@zarvox` to me, but another server has already given it to someone else, that will break my grain if I try to move the grain to that server.  To that end, guarantees of uniqueness would have to mean *universal uniqueness*, not even just for one server.

As a bonus, if we want cross-server federation to be possible, that's another reason that if we guarantee uniqueness, we must guarantee global uniqueness.

There are probably some things that we can do in due time to help for your specific case though, like a contacts API that gives out capability handles for users, and lets you search/autocomplete amongst your contacts and interact with them (like sending email, or other messages).

**Comment by kentonv** [comment]
Unfortunately global handle uniqueness is just not compatible with Sandstorm's federated identity goals.

However, many use cases for this can be solved in different ways.

For @-mentions, we would eventually like Sandstorm to support an autocompletion overlay which searches over the user's Sandstorm contacts, without the app needing to know about those contacts. When the user chooses someone, the app would receive a contact _object_, not just a name, with information like user ID. Sandstorm could also notify the target user and share the grain with them automatically. The autocompletion dialog would not require unique handles as it would show all matches and let the user choose the one they intended (much like mentions on Facebook or Google+, neither of which have any notion of unique usernames).

I don't know when this will be implemented, though. My suggestion for now is to uniquify by appending digits and deal with the ugliness. In practice I suspect that collisions will be rare -- probably if there are two users of one particular grain with the same handle, it's because they are actually two accounts owned by the same person.

**Comment by mitar** [comment]
Related: #1859
