### ISSUE TITLE
How about add check box in "App Market" to support install multiple application.

### ISSUE THREAD

**Issue by nhducit** [sandstorm-io/sandstorm#1044]
Scenario: a programmer just heard about how Sandstorm awesome is and he wants to migrate all separate applications to Sandstorm. When he wants to install an application, he goes to application admin dashboard and click "Install... from App Market" button, click on application button and waiting download progressing. Over and over again.

We can provide a checkbox and let him tick which application he wants to install then click "Install" button to get them all.

**Comment by paulproteus** [comment]
Hi @nhducit ,

One thing I _think_ you can do at the moment is to open each install link in a new browser tab. Does that seem to work?

If so, and if we can document that somewhere, would that meet your needs?

You may notice in the above I'm trying to get out of writing new code. (-: I'm trying to do that because I think mass-install is an important use-case but I'm not sure how to make mass-install easy without also complicating the single-install interface. So I'm not totally against writing new code/UI for this, but I want to try other avenues to meet your needs first.

**Comment by nhducit** [comment]
@paulproteus Yes, We can open "install" button link in new window. :)

**Comment by mitar** [comment]
I think this is related: #1830

**Comment by mitar** [comment]
Opening in a new window is so not mobile friendly. :-)
