### ISSUE TITLE
more helpful [400] error text

### ISSUE THREAD

**Issue by jadeqwang** [sandstorm-io/sandstorm#1065]
Let's say I'm trying to share access to something that I don't have access to (total edge case, I know, but there might be other ways to trigger it). I get this error:

![image](https://cloud.githubusercontent.com/assets/1584904/10652136/d982f8fc-7808-11e5-97a5-e1b5e8c4c38e.png)

A more helpful error might be: "Error: [400] You do not have permission to share this grain."
That is, unless there are other cases where this error message comes up. @dwrensha ?

**Comment by zarvox** [comment]
I think the clearer thing to do would be to disable the "Share access" forms entirely when you're looking at a view for a grain that you don't actually have access to.

**Comment by jadeqwang** [comment]
:+1:

**Comment by neynah** [comment]
Tested this today:
1. Attempted to access grain while logged out
2. Clicked "Share access"
3. I knew it wouldn't go anywhere useful but I copied the link since it told me to
4. Arrived at "Invalid token: null"

At the very least I think we shouldn't provide a link in this case.

![1](https://cloud.githubusercontent.com/assets/855341/14054959/00c54b88-f29b-11e5-9225-c377db0a5aef.jpg)
![2](https://cloud.githubusercontent.com/assets/855341/14054961/0487d16e-f29b-11e5-98d4-9df200cb48e8.jpg)
![3](https://cloud.githubusercontent.com/assets/855341/14054966/088d2b38-f29b-11e5-83ba-6e9ff96731f3.jpg)
