### ISSUE TITLE
Grain titles being petnames confuses people

### ISSUE THREAD

**Issue by kentonv** [sandstorm-io/sandstorm#1087]
Currently, Sandstorm grain titles follow a petname model: when you receive a document shared from another user, initially the title is a copy of the title as seen by the sender, but subsequently you can change the title, and the changes are only visible to you (and people you later share with).

This is totally different from how most cloud services work, and it confuses people.

Petnames have some nice properties, though, and I'd be sad to simply throw them out. In particular:
* If someone sends me an overly-generically-titled grain (e.g. "My todo list", or "Untitled Etherpad"), I'd like to rename it for the purposes of my grain list.
* If I'm looking for a document that I've opened before, I'll probably be looking for the title I remember it having. If the owner can change that, I might be confused.
* There may be a phishing threat if a malicious user can rename a grain in my grain list to spoof some other grain that they know I have.

Note that petnames are analogous to what happens when someone e-mails you a file: the filename is initialized based on the sender's filename, but once on your system, the sender can't change it, only you can. Another analogy is to variable names in a programming language: when a value is passed from one function to another, the name often changes, and this is considered a good thing, since the name is meant to identify the value *relative to* the context.

But that's all theory. Back here in reality, it seems that users do expect that the title (as shown in the top bar, at least) is part of the grain's _content_ and therefore is up to the grain owner to choose and change at will. We've seen plenty of examples of people being confused by the current behavior -- clearly it needs to change somehow. The question is, can we come up with a compromise that keeps the nice properties above but also makes sense to people?

Some questions to think about:
* Do people have different expectations for the topbar title vs. the grain list title? My issues mostly revolve around how the grain is shown in the grain list, but I think most of the complains focus on what appears in the topbar when the grain is open. Could these be disassociated somehow?
* Could we solve my problems by showing more information in the grain list and top bar that provide sufficient context to avoid confusion? For example:
    * What if we always show the author's name? "From Bob: My todo list" largely solves the problem of bad/ambiguous titles. It solves the phishing problem *if* we separately prevent people from spoofing names, which may require a petname system for identities, but that's something we probably want to do anyway. There is a possible problem, though, in that it's not clear that we are always allowed to reveal owners' identities to sharing recipients.
    * Could we solve the searchability problem by matching search queries against all of the document's previous titles? Could we show "Was: [old title]" in the UI somewhere?
* Should recipients still be given the option to specify their own title if they actively choose to do so?

**Comment by wtogami** [comment]
Discussion about this issue had a prior assumption that in 95% of cases titles never change.  I see Google Docs and Sandstorm (with Etherpad, Wekan, etc.) as collaboration tools.  Nearly always while developing content I find myself refining not only the content but also the title as I better understand the purpose of the document.

**Comment by dwrensha** [comment]
> Do people have different expectations for the topbar title vs. the grain list title? My issues mostly revolve around how the grain is shown in the grain list, but I think most of the complaints focus on what appears in the topbar when the grain is open. Could these be disassociated somehow?

It seems natural to me to keep both the concept of a grain title and of a shared grain petname. Maybe the grain title is what shows up in the topbar and can only be edited by the grain owner, while the petname is what shows up in the grain list (and maybe the grain title shows up there too, as hover text or something).

**Comment by kpreid** [comment]
I recall from early discussions of the Sandstorm vision the suggestion that organizing grains into folders would (be possible and) be handled by folder-grains that store caps to other grains. As an enthusiastic practitioner of organizing things in folders, I very much want the names inside any given folder to be consistent with each other. In a capability system, objects may be in more than one folder and therefore have more than one name.

I bring up the above because I think “what happens when we have folders, not just a grain list” is an important perspective from which to consider possible answers to this problem.

One possible answer is that grains have a shared mutable title (wait, isn't that gratuitous authority? shouldn't all mutation be controlled by the app code?), and the user also has a petname (or more than one) for the grain, and the UI shows both if they are different, and depending on context (explicit folders vs a "newly shared with me" list) possibly automatically syncing them.

Let me expand on that "gratuitous authority" part: every grain getting a title everyone sees updates to is additional authority, which steps outside of the model of the application implementing all of the things-which-can-be-mutated. Just think about: who gets access to edit the title? What if a grain has highly distinct facets (e.g. a user facet and an admin facet) such that the context-appropriate title is different?

Given such problems that I've now thought of, I'd like to express the opinion that whatever solution is chosen should _not_ take the form of a shared mutable title. And now I have thought of a concrete proposal:

* Grain titles, or rather petnames, _functionally_ stay as they are now, and possibly the UI is tweaked to emphasize that they are filename/address-like (e.g. mentioning them in context of an enclosing folder/"my grains", where that context might be a visual-language sort of thing rather than explicit).
* _Document-like_ apps, i.e. most centrally Etherpad, have shared mutable titles _implemented by the app._ There is a standard protocol to ask a grain “what's your title”, or for the grain to push out a title value which is cached.
* The shell/folders have support for querying grains for such titles, if the app supports them, and displaying them in addition to the petnames, even syncing petnames to them if the user asks for such.

**Comment by paulproteus** [comment]
When I move _some_ events around on Google Calendar, I see this message:

![are-you-sure](https://cloud.githubusercontent.com/assets/25457/11161613/90af0270-8a36-11e5-8d25-3511f351f5f8.png)

We could incorporate something like that into a solution. (This message on the issue does not constitute an assertion that I am confident about what exactly that solution should be!)

**Comment by mitar** [comment]
I would vote for having only one title for a grain, shared between all users.

We could allow subtitles or notes to be added which would be visible only to a given user.

**Comment by kentonv** [comment]
I'd like to propose a solution that hopefully satisfies all parties:

* If the petname and original title are the same, we just display it.
* If the sharing recipient has explicitly modified their petname, we show their petname as the title, with subtext of "renamed from: [upstream title]". This allows the user to assign their own title if they need to disambiguate the grain, though most of the time they probably won't.
* If the sharing recipient has *not* explicitly modified their petname (i.e. it is a clone of the title from the time of sharing), but the upstream title has changed, we show the upstream title, with subtext of "was: [petname]". This allows the user to understand how this grain whose title they don't recognize arrived in their grain list.

I also agree with Asheesh's suggestion that we warn the user when they are setting a petname that only applies to themselves.

Implementation details:
* Along with any petname, we store a boolean indicating whether it originates as a copy of the grain's title or from a non-owner renaming it.
* When the owner of a grain renames the grain, we denormalize the new title into all user-owned ApiTokens. This way, we don't have to do an ad hoc Mongo join to display the grain table (something that was worrying me here).

@neynah Do you have any thoughts on how to style the title subtext? It should probably show up on the title bar and in the grain table, but I don't think it needs to show in the sidebar.

@wtogami Does this sound like a reasonable solution? Sorry that this has taken a very long time, but we've had a lot on our plate and I've struggled a bit to come up with something that didn't have a bunch of problems.

**Comment by zarvox** [comment]
A couple questions:

* when we say "upstream name", is that a global bit of information (the grain owner's name), or is it the person-who-shared-with-you's petname for the grain?
  * If the former, then it's basically "only the owner can rename the grain for everyone", so a resharer might rename their copy, but no one else will see their change.  On the upside, they'll see the "renamed from" `<global title>` message, so they'll at least have a name that everyone else can use.
  * It's probably not the latter, because the sharing graph is a graph, so there's not a unique "predecessor" for a given user in the graph.

* Could we rephrase the "Was: <old upstream name>" case to switch the placements of the two titles, and change the subtext to "Now: <current upstream name>"?  The intent there is to make the user's name for the thing always be the big text, and the upstream name always be the subtext.  Having to parse both names and subtext each time, especially if their roles may vary between items in the list, seems like more cognitive load than I want to do myself, let alone ask users to do.  If I know I'm looking for my name for a thing, it'd be nice to know to focus on the big text or the little one.

**Comment by kentonv** [comment]
@zarvox 

* The "upstream name" would be the owner's title, as stored on the Grains table.
* In the "Was:" case, the recipient has not set any title of their own. The "Was:" is identifying the owner's previous title. I don't think it makes sense to promote the owner's original title over the owner's new title; that seems like the opposite of what @wtogami wants. I think you are thinking of the second case (where an explicit non-owner rename has taken place), in which case my proposal is to prioritize the recipient's custom title over the owner's title.

**Comment by zarvox** [comment]
As discussed in person: okay, that seems reasonable, so long as search searches over both names. :)

One last thought: if the user renames the grain to a title which matches the owner's title, then maybe treat that as an expressed intent to remove their petname and rely on the upstream title.  Basically, set the boolean `isUpstreamName` back to true, where any other petname change would set the value to false.

**Comment by paulproteus** [comment]
Thanks for taking the time to dig into these questions. I have some further questions (not to be mistaken for qualms).

- When @jacksingleton and I discussed this a few months ago, we noticed that in Google Docs, when the user sets the form title within the app (rather by editing the document title in the Google Docs UI), the form app changes the document's name accordingly. Detailed proposal here: https://github.com/sandstorm-io/sandstorm/issues/1475 . I think this is compatible with the @kentonv proposal on this issue; curious if you agree, Kenton?

- If Alice makes a grain ("Untitled Etherpad Document"), then renames ("Alice's title"), then shares with Bob, then Bob renames (to "Bob's title"), then Bob shares with Charlie (who sees "Bob's title"), then Bob renames back to "Alice's title", then Alice renames to "Alice's title 2", would Charlie see "Alice's title 2" as the grain title? Just trying to make sure I understand how the sharing graph affects this.

- In e.g. Google Docs, I believe that anyone with "Owner" permission on a document can rename it in a way that is global to others. I can go verify that in a moment. Kenton, in your proposal, is there a way that the owner can delegate the ability to do a global rename? Can we make this be a permission bit the app can set which changes shell behavior?

**Comment by kentonv** [comment]
@paulproteus 

* Actually, reviewing #1475, I think that proposal is problematic in itself. I have commented there. That said, I think that proposal is overall orthogonal to this one.

* Bob's rename _after_ sharing with Charlie would not affect Charlie's title. Charlie's initial petname is copied from Bob's, but from then on Charlie is treated no differently than if he had received the share directly from Alice and then renamed it to "Bob's title" himself. While in theory we could do a complicated thing where Bob's renames are propagated downstream, I think this would not be very useful and would have too many corner cases (e.g. what if Charlie also received a copy from Dave...).

* In my proposal, only the owner can make renames that are visible to others. While you could certainly argue that the owner should have the ability to delegate this power, I don't think we've seen strong demand for that, therefore I'd rather not implement it for now. A future implementation could, I think, take the form of a platform-defined permission bit which the app can declare is granted to certain roles (just like with app-defined permission bits). (I don't think we should present a checkbox to the user when sharing -- this would be too distracting.)

**Comment by ocdtrekkie** [comment]
After somewhat following this issue, I am now confused by petnames.

**Comment by kpreid** [comment]
> If the sharing recipient has not explicitly modified their petname (i.e. it is a clone of the title from the time of sharing), but the upstream title has changed, we show the upstream title, with subtext of "was: [petname]". This allows the user to understand how this grain whose title they don't recognize arrived in their grain list.

Thank you for paying attention to this case.

**Comment by mitar** [comment]
What about simply allowing user to expand a list of titles the grain had? So by default latest is displayed, but you can see (and search) older names as well?
