### ISSUE TITLE
Suggestion: move "restore backup" to Grains menu rather than Apps menu

### ISSUE THREAD

**Issue by jadeqwang** [sandstorm-io/sandstorm#1108]
At Kenton's suggestion, I'm moving my active usage to testrock in order to be a canary for new features, so I've been doing a lot of downloading backups and restoring them.

I find that I'm intuitively looking for "restore backup" under Grains rather than Apps, even though I intellectually know where the button is, because naturally, I'm restoring the backup of a grain, not of an app.

/cc @zarvox

**Comment by paulproteus** [comment]
I am theoretically very +1 on this, but upon attempting to implement it, I found myself staring at https://oasis.sandstorm.io/grain and having no idea where to put the "Restore..." button that we have.

Thoughts:

* I think it should be a link, not a nicely-designed button, since it's not a common activity.

* I agree that on "Grains" makes more sense than on "Apps".

* Given that I don't know where to put it, I humbly request to you @jadeqwang that you ask @neynah to figure out where to put the link. Once such a decision is made, it's easy to implement.

I think addressing UI "paper-cuts" like this sooner rather than later, if possible, is a good way to keep a design usable.

**Comment by jadeqwang** [comment]
I have a suggested location for a smaller version of the button that already exists:

![image](https://cloud.githubusercontent.com/assets/1584904/10871119/17ea8cf8-8093-11e5-822a-3426d787a3e9.png)

But I defer to @neynah for where she thinks it should go. :)

**Comment by dwrensha** [comment]
One nice thing about the current design is that it nicely meshes with the distinction between guest users and users with actual accounts --- actions that any user can take fall under "Grains", while actions that only account-holding users can take fall under "Apps". Guest users have no quota, and are therefore not allowed to upload backups.

After this change, the division would not be so tidy. That's probably okay, but worth keeping in mind.

**Comment by neynah** [comment]
If we were to have this button on the grains page I would put it in the top right corner and style it consistently the same as the "Uninstall" button on the detailed app page. People's eyes will scan left to right and the back-up button should be out of the way as the grain summary info is more important.

@dwrensha I agree the division won't be so tidy. I don't have a solution in mind but hopefully someone does. :D

![restore-backup](https://cloud.githubusercontent.com/assets/855341/10918822/873fa2e8-821c-11e5-83e3-65522cf22280.png)

**Comment by dwrensha** [comment]
Done in https://github.com/sandstorm-io/sandstorm/pull/1362.

**Comment by paulproteus** [comment]
Thanks for taking good care of the bugs when I forgot to!​
