### ISSUE TITLE
System for Accessing Grain Name

### ISSUE THREAD

**Issue by rosatolen** [sandstorm-io/sandstorm#1117]
Hi!

We're looking to change and get (or sync) the Grain Names from our [Sandstorm application](https://github.com/sandforms/sandforms) so that when the administrator changes the name of the instance of our app, it reflects both in the admin panel and in our app.

Is there currently a system for doing this? Maybe I didn't look hard enough. :(

Thanks,
Rosalie

**Comment by jadeqwang** [comment]
I think the discussion in the thread for issue #1087 is related. @kentonv ?

**Comment by paulproteus** [comment]
Just to clarify here, #1087 is definitely related. On that ticket, kpreid
suggests one way to move forward, which is that document-type apps can
"own" the title and pushes updates out. Curious what @kentonv makes of
that. @jacksingleton seemed to think on IRC that it would meet the needs of
SandForms.

It has the weird disadvantage that if the user manages to edit the title
from Sandstorm rather than from SandForms, then the titles can get out of
sync.

**Comment by ocdtrekkie** [comment]
Fixed in #3220. Docs for it are now in https://docs.sandstorm.io/en/latest/developing/path/
