### ISSUE TITLE
`primaryEmail` can be inconsistent with verified email list

### ISSUE THREAD

**Issue by kentonv** [sandstorm-io/sandstorm#1197]
* When linking a new identity which has a verified email address, if the current primary email is *not* verified, we should automatically switch the primary email to the new address. (Note that currently, it's not even possible to make this change in the UI because the radio button defaults to the one verified address even though it is not primary, and you can't change it.)

* If, after unlinking an identity, the primary address is no longer verified, but other verified emails exist, we should switch the primary email to one of those other addresses.

**Comment by dwrensha** [comment]
The idea behind the current implementation is that an account's primary email is a computed value. If `user.primaryEmail` is a verified email of the account, then that value is the primary email. Otherwise, the account's primary email is the first in its list of verified emails. If you ever want to use the primary email, you have to call `SandstormDb.getUserEmails()`, which does this computation for you.

I think this approach is cleaner than trying to maintain the validity of the `user.primaryEmail` field.

**Comment by kentonv** [comment]
Hmm, I guess that makes sense.

There is a somewhat weird thing that can happen:
1. I have verified foo@example.com and bar@example.com, and foo is my primary.
2. I remove foo's identity. Now bar is my primary. Note that I am unable to explicitly select bar as primary because it is already by computed primary. That is, I cannot, though the UI, affect the value of the `primaryEmail` field.
3. I re-add foo. Now foo immediately becomes primary again.

But this is unlikely to happen enough to be worth fixing.
