### ISSUE TITLE
Feature request: Custom home page

### ISSUE THREAD

**Issue by jenmei** [sandstorm-io/sandstorm#1244]
Would be great to have a homepage (or homegrain). Could act like a README file. For example, if I have a group of volunteers that are using Sandstorm to collaborate, track, and share stuff, it would be great if the homepage could let folks know what the org is about, what is stored in which apps, links to specific docs (e.g. links to Etherpad or Ethercalc docs), and who to contact w/ questions.

An easy to edit static page would be nice. A grain might be nicer (e.g. Media Wiki).

**Comment by kentonv** [comment]
I think #1275 fulfills part of this: It will allow specifying a background for the login page when the user is not logged in. However, once logged in we still redirect users to the grain list.

Perhaps we could add an option to set an alternative redirect URL for logged-in users? You could then have it redirect to a grain or a static page or whatever you prefer.

**Comment by paulproteus** [comment]
Hi @jenmei ,

A few Sandstorm installs now have custom home pages. Examples:

- https://oasis.sandstorm.io/

- http://oet.sandcats.io/

- https://oucreate.sandcats.io/

They're following this documentation:

https://docs.sandstorm.io/en/latest/administering/faq/#can-i-customize-the-root-page-of-my-sandstorm-install

Given that, I'm going to mark this as closed (as resolved), since there is now a way to have a custom home page. @jenmei if you disagree, then by all means please re-open, and if you think there should be other new features as well, let me know and I (or you) can file a bug for the other new features!

Thanks for filing this, and to @neynah for noticing the issue is basically resolved.
