### ISSUE TITLE
Sharing auto-complete chips: up/down should work too

### ISSUE THREAD

**Issue by kentonv** [sandstorm-io/sandstorm#1288]
When navigating through chips in the new share-by-identity interface, you can use left/right to navigate, but the chips are usually arranged vertically, so it's more natural to use up/down. Both should work.

**Comment by jparyani** [comment]
This is actually very hard to support, since completed contacts are just a `ul`, and the rows are created by virtue of the layout in the browser. We could try to introspect the DOM to see what row the user is on at any given moment, and what contacts is "above" or "below" it, but it would definitely be a bit complicated.

**Comment by kentonv** [comment]
I think at least having up/down scroll through the items in order would be better than the status quo.
