### ISSUE TITLE
When an update of Sandstorm occurs, have a possibility to postpone.

### ISSUE THREAD

**Issue by noci2012** [sandstorm-io/sandstorm#1297]
Got an update while working in sandstorm....
Now the sessions is disconnected and then the session needs to be reloaded.
imho a better option would be to have it allowed / confirmed in stead of just happening.
Not sure what happens when a larger transfer is actually busy when the update occurs.

Like a notification as there are for applications.

**Comment by kentonv** [comment]
Hi @noci2012,

Sorry that an update disrupted you.

What do you mean by "sessions is disconnected"? Which app were you using, and what did it say exactly?

Generally, when an update occurs, the topbar will change to the red "click here to reload", but apps should continue to work in the meantime. If not, that's a bug that we should fix.

That said, even if apps aren't disrupted, we do need to improve some things:
- Reloading should restore the same set of tabs you already had open, so that you don't have to go open them all again.
- Ideally we wouldn't hide the topbar. The reason we do that currently is because if there were backwards-incompatible changes to the client<->server protocol, the most likely place for them to appear is in functionality available through the topbar. But as we stabilize, we should probably think more about making sure each update is fully backwards-compatible so that there's no immediate need to refresh the client side.

**Comment by noci2012** [comment]
There was a popup "Session Disconnected, attempting to reconnect" for about 20 seconds.
Afterwards there was the top bar with the renewal request. 

And indeed only the active grain is visible on the left side after the update. (only one left, while i had 4 where is was switching among them).
A reload of haproxy isn't noticable, a restart (sopt. start) of the server has the same effect

**Comment by kentonv** [comment]
@noci2012 Could you tell me which app it was that reported "session disconnected"? Apps are supposed to be tolerant of brief disconnects, so we'll want to file a bug against that app.

**Comment by noci2012** [comment]
Ethercalc.
