### ISSUE TITLE
Notifications so a non-focused grain can request human attention, in "multigrain" view

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#1400]
This ticket tracks the creation and documentation of some Sandstorm notifications API that allows a grain to request the user's attention when the user is looking at some other grain.

Use case: As a **Sandstorm user**,

- In order to stay attentive to chat while getting work done,

- When I have a Rocket.Chat grain open in a Sandstorm window,

- And I _also_ have an Etherpad grain open in the same window,

- And the Etherpad grain is focused,

- And someone pings me in Rocket.Chat,

- I would like some kind of visual indication that the Rocket.Chat grain wants my attention,

- So that I can switch back to it and respond to my colleague's chat message.

Context from IRC:

```
16:03 < TCF> multitasking would be a good addition
16:04 < TCF> or is the notification the idea of that?
16:05 < asheesh> If we have multi-tasking, then would that mean you can view mltiple grains at once? Or 
                 that you can switch between them?
16:06 < asheesh> If "switch between them", you can already do that, via the little tabs on the left.
16:06 < asheesh> Though it might not work on mobile yet.
16:08 < TCF> I'm thinking more in terms of: if someone chats you on rocket chat that you can do that chat 
             while you are on another grain etc
16:09 < asheesh> I don't know how to do that in a general fashion, but I like the idea.
16:11 < asheesh> One thing I was thinking is that we could let apps indicate activity so you at least know 
                 to click back to them.
16:11 < TCF> yes
16:11 < TCF> Thats a good start
16:11 < asheesh> So then the Rocket.Chat could blink or something to tell you that even though you're on 
                 an Etherpad, it's time to look at chat again.
16:11 < asheesh> I'll file a bug requesting it. Thanks for asking about that!
16:11 < TCF> :)
16:11 < asheesh> I don't know when we'll be able to do it, but I hope it's soon.
```

**Comment by ocdtrekkie** [comment]
I am not sure how related/unrelated this is, but I think one of the big things something like a mail app needs is a way to indicate an unread state to the shell. Even if the grain is closed. (Similarly, a document might want to let me know someone else has edited it since I was last there as well.)

Maybe this 'unread changes' state should work whether or not your grain is open. But if it is open, it depends on whether or not you're focused on it as well.

**Comment by kpreid** [comment]
<gripe> Why can't Sandstorm just leave it to the user to have multiple _browser_ tabs and let all the mechanisms that already exist for that be used (changing page title/favicon, notification API, etc), instead of reinventing tabs inside a page?

**Comment by paulproteus** [comment]
50% of the time, I would prefer that Sandstorm not bother with
"multi-grain", aka reinventing tabs in a page.

50% of the time, I appreciate that the "multi-grain" interface makes it
easier to keep my Sandstorm-related tabs together for easy switching
between different grains.

So the answer anyway is, "So that users can have multiple Sandstorm grains
open at once without the perceived cost of new tabs, and with the improved
usability of having the grains be all located together which can be nice if
you're working on a few grains at once."

I wonder if we can use TARGET e.g. <a target="_sandstorm"> in support of
this sort of thing, anyway.

**Comment by kentonv** [comment]
I have always imagined we'd do something like rocket.chat itself does in its sidebar, but for the grain tabs -- if there's unread activity in a grain, highlight it, and if the user has received direct pings in the grain, show a little number of those directly on the tab.

Perhaps, then, we could convince rocket.chat to add a one-room-per-grain mode, which would be great for security.

@kpreid - I totally understand your viewpoint. The thing is, we're trying to minimize as much as possible the friction of designing fine-grained apps. Before we had the sidebar tabs, I couldn't convince anyone -- even Sandstorm team members -- that chat apps like Rocket.Chat and Let's Chat should be one-room-per-grain, because people perceived the ability to fast-switch between rooms using the sidebar as important, and that browser tabs were too heavy-weight for this. After extending Sandstorm itself with a tabbed UI, the conversations have become a lot easier (although admittedly it hasn't quite happened yet).

To me it is absolutely essential that apps buy into fine-grainedness, so that justifies "reinventing tabs".

And as it turns out I rather like the UI this way. It might seem silly logically, but in practice it seems to help.

**Comment by dwrensha** [comment]
Closing, as notifcations landed in https://github.com/sandstorm-io/sandstorm/pull/2174.
