### ISSUE TITLE
When filling out user profile with an invalid handle, error message does not clarify what change user should make

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#1421]
Steps to reproduce:

- Create an account on a Sandstorm install

- Type a "handle" with uppercase letters

- Attempt to submit

Expected behavior:

- See some indication of how to fix one's handle.

Actual behavior:

- Message appears saying "Please match the requested format."

Relevant links:

- https://stackoverflow.com/questions/11866910/how-to-force-a-html5-form-validation-without-submitting-it-via-jquery

- https://github.com/w3c/web-platform-tests/issues/993

- Or we could clarify somewhere what the requested format is, on the page.

![bad-error](https://cloud.githubusercontent.com/assets/25457/12534277/97899d4c-c205-11e5-81af-3df86706c5a5.png)

**Comment by neynah** [comment]
Do we have a requested format for the full name?

To improve accessibility, I think it'd be better to display the requested format message on the page(instead of within a tool tip). E.g. display it as part of the label field. We could then highlight and focus the field and requested format message in a red colour it if it doesn't validate.

I'm sure @zarvox has some good insights.

**Comment by paulproteus** [comment]
@neynah - you can "inspect element" and see the current format, fwiw! Can show you tomorrow too.

**Comment by zarvox** [comment]
FYI, this is the result of using HTML5's `pattern` attribute on an `<input>`.  I suspect we'll want to drop the pattern specifier, and use a real form validation library.

**Comment by paulproteus** [comment]
As a sidenote,
https://stackoverflow.com/questions/10361460/how-can-i-change-or-remove-html5-form-validation-default-error-messages
suggests that if we add a title= then the browser might show that.
