### ISSUE TITLE
Grain upgrade offering

### ISSUE THREAD

**Issue by noci2012** [sandstorm-io/sandstorm#1425]
After an app was updated (ethercalc) i noticed that old behaviour was still in the old grains. 
(No problem there w.r.t. Sandstorm). But no notice to ask if this should be upgraded.

Only when creating a NEW grain, a notice was visible that there were still grains using the old version with the Q, if they needed to be upgraded.
Should this notice be displayed on ALL grains that still use old code?

**Comment by kentonv** [comment]
The notice appears on the app details page, which is usually the first thing you see after installing/upgrading a package. Did you find yourself somewhere else after installing? Or did the app details page actually not show a notice at all?

**Comment by ocdtrekkie** [comment]
@kentonv If you upgrade apps from the notification, you'll never be directed to the Upgrade Grains button.

**Comment by kentonv** [comment]
@ocdtrekkie If you upgrade from the notification, it automatically upgrades all grains.

**Comment by ocdtrekkie** [comment]
@kentonv I don't recall that being my experience.

**Comment by noci2012** [comment]
In this case i uploaded a supplied SPK.
I have the URL for some often used grains ready in a shortcut page.
So i don't pass the app page.

**Comment by jparyani** [comment]
@ocdtrekkie 

I believe grains should be upgraded automatically if you click the auto-update notification's "Apply Updates" button. Just to be sure, I went and looked for the line that should be doing this upgrade (https://github.com/sandstorm-io/sandstorm/blob/10202bfb42f2daef1f20377e664be8289b1a589b/shell/packages/sandstorm-autoupdate-apps/autoupdate-apps.js#L88)

Please create an issue if you see this not working correctly.

**Comment by ocdtrekkie** [comment]
I will keep a closer eye on the behavior, @jparyani

**Comment by noci2012** [comment]
I got an update .spk outside of the app-"shop" from the ethercalc maintainer and updated with that image. Which behaviour of updates triggered me to issue this.

**Comment by kentonv** [comment]
Perhaps what would be less confusing is if we always updated existing grains *unless* the user has chosen to pin them somehow. Not sure how such a pinning interface should look.

**Comment by paulproteus** [comment]
I would love for there to be an (i) (i in a circle) on the app details page
(which is where I typically look for info about grains), which would let
you see more complicated stats about the grain, like CPU use/RAM use/etc.,
and also configure version pinning etc.

**Comment by ocdtrekkie** [comment]
@kentonv I'd be totally fine with grain autoupgrade if the methodology to undo it existed. People never expect the next update to totally trash their workflow.

**Comment by kentonv** [comment]
@ocdtrekkie I agree but making that work is technically difficult. Apps often do migrations at initial startup, after which downgrading may not work or may even damage the data, so we need a way to snapshot before the upgrade and then revert to the snapshot, which will take a while to build...

**Comment by ocdtrekkie** [comment]
I think in the short term, @kentonv, you might be overengineering the problem. Because for a large number of apps, the data format is simple. Davros is just a file folder, some are just text files. Some apps the data format just rarely ever changes. Ideally, a downgrade feature should snapshot and such, but if 95% of the time you can "just" downgrade, it should be allowed. Maybe a warning interstitial could be displayed that recommends backing up a grain first (or offers to do it for you).

The other perk to allowing this capability, is that developers have an incentive to maintain reasonable compatibility. Migrations, while sometimes necessary, should be rare. And if your format is relatively backwards-friendly, users can preserve their edits during a revert.

As an additional thought, perhaps at some point apps could specify a format API of their own (which might be useful anyways for the whole 'other apps using another app's grain type' that's been discussed), so an app could specify whether or not it was safe to downgrade a file. You might increment your app's API version only when your update performs a migration and has a breaking change, in which case, since we know a revert won't work, we disable the button. (And maybe avoid auto-upgrading over an API version, perhaps?)

**Comment by ocdtrekkie** [comment]
I am reminded of this issue because of mnutt/davros#51

**Comment by noci2012** [comment]
>2 year inactivity closing.
