### ISSUE TITLE
Limit Google OAuth to a GApps domain

### ISSUE THREAD

**Issue by craftbyte** [sandstorm-io/sandstorm#1435]
It would be really nice to close off logging in from unauthorized domains as well as to make people from a certain domain invited users automatically.

**Comment by kentonv** [comment]
Hi Anže,

This is actually a feature we're planning to build soon (in the next month or two) as part of our Sandstorm+Business offering.

Out of curiosity, are you using Sandstorm at work, or is this a personal domain?

**Comment by craftbyte** [comment]
Personal domain

**Comment by kentonv** [comment]
Hmm, would you mind describing your use case a little more?

I want to make sure we don't leave personal users out in the cold by putting features they want into the paid product, but we do need to make a profit somehow. So I'd like to figure out what we might use to distinguish your use case with that of a typical business user.

**Comment by craftbyte** [comment]
I was thinking of mainly using this to prevent other people from signing in. It would be a good idea to maybe limit GApps login to max 10 users?

**Comment by ocdtrekkie** [comment]
@craftbyte Out of curiosity, would simply not letting people log into your server at all unless invited equally meet this need, as a personal user? The reason login is allowed is so you can share your documents to other people, but I see that sort of request a lot.

**Comment by kentonv** [comment]
@craftbyte If you haven't shared anything with the user nor given them permission to install apps then they can't actually do anything once they log in. Is there a reason you'd like to block login entirely?

**Comment by paulproteus** [comment]
As a sidenote, one way to implement this is that viewing a sharing link
authorizes the visitor to create an account.

Under that circumstance, when a visitor shows up to a Sandstorm install but
has no grains shared with them, and logs in for the first time, Sandstorm
would show the visitor a message saying, "It's cool that you are
{{userName}} but you do not have an account here. Please ask someone to
share some data with you on this server, and then you will be able to get
an account. Have a nice day." (Or something along those lines.)

One could imagine this being a server-wide setting so that the current
behavior is the default.

**Comment by kentonv** [comment]
@paulproteus What we have right now is pretty close to that. When you log in you see:

![screenshot from 2016-02-05 17-50-19](https://cloud.githubusercontent.com/assets/4001805/12863795/f0f3e740-cc30-11e5-8f57-5f19d8dec1bb.png)

If changing the wording would help I'm all for that.

Perhaps it would also help to skip the first-login profile editor in this case, which I'd be OK with.

**Comment by paulproteus** [comment]
+1 to skip first-login profile editor in this case

I'd prefer different text. General notes:

- Delete or seriously de-emphasize "403 Unauthorized", that sounds just too
scary

- Emphasize actions people can take

Proposed text:

<h1>Ask someone to share a grain with you</h1>

<p>No one has shared anything with you on this server yet, so you cannot
log in. You authenticated as paulproteus on GitHub. If you think you are
seeing this in error, try a different login method.</p>

<p class="small">Status code: 403</p>

**Comment by dckc** [comment]
A business I consult for would benefit from this.

Especially if you offered some sort of HIPAA compliant hosting.

**Comment by ocdtrekkie** [comment]
AFAIK, this currently works as a Sandstorm for Work feature.

https://docs.sandstorm.io/en/latest/administering/for-work/

**Comment by kentonv** [comment]
Yes, this feature now exists in Sandstorm for Work: "Disallow collaboration with users outside the organization.", under "Organization settings". Enabling this feature prohibits anyone outside the organization from logging in at all.

Keep in mind that you only need this feature if you are worried that users in your organization might accidentally share outside. If you can trust your users not to break policy then there's no need to prohibit guest accounts, because guest accounts can't do anything unless someone shares with them.
