### ISSUE TITLE
For user-agent whitelist: Allow the server operator to add entries to it via sandstorm.conf or admin settings

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#1457]
Overview: App authors want to test arbitrary WebDAV/etc. clients with their 

- As an app developer, I want to allow apps of my choosing to connect to my testing Sandstorm server using HTTP Basic auth. This way, I can test if my WebDAV/CardDAV/CalDAV app works.

- To achieve this, Sandstorm would grow the ability to let the admin specify extra user agents to whitelist for HTTP Basic authentication. The password for Basic auth would be the same as now, namely, a Sandstorm access token.

- To make this useful, Sandstorm would log any HTTP user-agents that attempt to do basic auth, so the admin can find the correct strings to whitelist.

cc: @synchrone @mnutt

**Comment by synchrone** [comment]
Correction to point 1: as an app developer I want to allow apps to connect to sandstorm server using HTTP Basic auth. 
Not only for testing, for production as well, since Basic is a widely used api auth method.

If whitelisting is for some reason (I do not understand which reason exactly, forgive my ignorance please) wants to limit the client types from using Basic - it must do so by checking their behavior. I don't know which clients are considered unworthy of using HTTP Basic auth, so I can't say how to detect them.

Logging forbidden requests in this case is a must, I agree 100%.

**Comment by mnutt** [comment]
It seems like any client that is capable of executing javascript based on the responses should not be allowed basic auth. This is because some malicious content stored in the grain shouldn't be able to trick the user into executing itself. My example is a file tree viewer. If I sent you a malicious file and you were to preview it, it could use ajax + other API endpoints to delete the rest of the files in your grain.

We try to prevent this behavior by not allowing people to open these malicious HTML files via URL; instead they have to use ajax. Clients that respect CSP even _could_ be allowed, but it seems like there are just too many older clients out there to catch them all. And I can imagine other hacks (refuse to serve API responses with content-type `text/html`) but there are just too many edge cases to count on it working.

I think once you get past the development stage we could make it very easy to open a sandstorm PR to whitelist your client to open it for everyone in production. Would that suffice?

**Comment by paulproteus** [comment]
+1 to @mnutt 's comment; indeed we'd be very very open to adding a bajillion non-browser things to this whitelist, if you can handle a 1-week release delay.

Arguably it's useful to give you an opportunity to test that client. But anyway.

**Comment by kentonv** [comment]
@synchrone Another problem with basic auth is that browsers like to cache the credentials and then reuse them for all future requests to the host, which opens the possibility of XSRF. We'd really prefer that apps not have to think about XSRF, but if we're going to tell them that, we'd better make sure it's true. OAuth-style bearer tokens (`Authorization: bearer`) are not vulnerable to XSRF, so we want to push new clients towards them. Single-purpose clients that don't render any other web site (so, not browsers) are also safe, so we're happy to whitelist them, so long as we don't accidentally whitelist any browsers.

**Comment by dwrensha** [comment]
Closing. After https://github.com/sandstorm-io/sandstorm/pull/1547 we now have token-specific hosts where basic auth is always enabled.
