### ISSUE TITLE
"share access" is broken for incognito grainviews

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#1474]
Steps to reproduce:

- Create a grain

- Make a sharing link

- Open the sharing link in Firefox

- Stay incognito

- Attempt to create a sharing link

Expected result:

- A new sharing link appears

Actual result:

```
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create a0d9a91dcf35564c7ba2663523315432ef8900f3.js:3:3343
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create 9c8c669c14dd9621e504d254399e26662fa86a5d.js:3:3343
"e.makeErrorType/r@https://oasis.sandstorm.io/9c8c669c14dd9621e504d254399e26662fa86a5d.js?meteor_js_resource=true:3:3334
._livedata_result@https://oasis.sandstorm.io/9c8c669c14dd9621e504d254399e26662fa86a5d.js?meteor_js_resource=true:50:19802
u/o@https://oasis.sandstorm.io/9c8c669c14dd9621e504d254399e26662fa86a5d.js?meteor_js_resource=true:50:6561
._launchConnection/t.socket.onmessage/<@https://oasis.sandstorm.io/9c8c669c14dd9621e504d254399e26662fa86a5d.js?meteor_js_resource=true:50:567
A.forEach@https://oasis.sandstorm.io/9c8c669c14dd9621e504d254399e26662fa86a5d.js?meteor_js_resource=true:1:863
._launchConnection/t.socket.onmessage@https://oasis.sandstorm.io/9c8c669c14dd9621e504d254399e26662fa86a5d.js?meteor_js_resource=true:50:523
v</r.prototype.dispatchEvent@https://oasis.sandstorm.io/9c8c669c14dd9621e504d254399e26662fa86a5d.js?meteor_js_resource=true:49:1119
v</C.prototype._dispatchMessage@https://oasis.sandstorm.io/9c8c669c14dd9621e504d254399e26662fa86a5d.js?meteor_js_resource=true:49:14711
v</C.prototype._didMessage@https://oasis.sandstorm.io/9c8c669c14dd9621e504d254399e26662fa86a5d.js?meteor_js_resource=true:49:15601
v</C.websocket/o.ws.onmessage@https://oasis.sandstorm.io/9c8c669c14dd9621e504d254399e26662fa86a5d.js?meteor_js_resource=true:49:17702
"
```

**Comment by paulproteus** [comment]
The issue goes away when I'm not incognito ("incognito" in the Sandstorm sense), so that's probably the real bug - we probably shouldn't show "Get shareable link" if you're not logged in?

(Compromise? We show the very sharing link they're viewing?)

**Comment by dwrensha** [comment]
The "send an invite" stuff will probably be broken too. Maybe we should hide the whole "share access" popup for incognito.

**Comment by zarvox** [comment]
@dwrensha I like that.  I'd leave the button in the topbar, but would have the popup tell you that you can only reshare access if you're logged in and maybe (if it's redeemable by anyone) that you could pass on the URL.

**Comment by paulproteus** [comment]
@zarvox For what it's worth, I believe all sharing links are redeemable by anyone. Is that so? If so, then great; if not, then I'd like to know more!

**Comment by zarvox** [comment]
I was under the impression that share-by-identity links were restricted to redemption by the identity that they were initially shared to.

**Comment by kentonv** [comment]
Yeah, I think incognito should behave like anonymous. Since the full share link is still available in the address bar, the user can copy/paste it to share. Meanwhile, we don't know what email address to send a sharing email from. So, the sharing dialog is moot. I'd be in favor of not showing the button at all.

@zarvox Share-by-identity links cannot be accessed incognito. :)

**Comment by zarvox** [comment]
I agree that the user cannot make productive use of the "share access" popup when incognito.  However, I think showing the button in the topbar is superior to removing it outright for a few reasons:

* feature discoverability, if you're new to Sandstorm
* consistency of design
* it gives us a place to explain why you can't share access, rather than it just not being there, and send you on a more successful path if sharing is your goal (by suggesting you log in, or share the link you're already using.)

**Comment by kentonv** [comment]
@zarvox SGTM
