### ISSUE TITLE
How to configure a sandstorm server in DMZ network

### ISSUE THREAD

**Issue by vivienkit** [sandstorm-io/sandstorm#1483]
Hi all,

I recently installed a sandstorm server on a ubuntu server 15.10 to try self-hosting in my small company.
This server is located on a DMZ network (e.g. 192.168.10.0), where all machines have different public addresses. It goes on internet through a SDSL connection
The LAN is on a different IP sub network (e.G. 192.168.20.0), all machines go to the internet through the fiber with another public IP address.

I can access my sandstorm server from the outside, using my ***.sandcats.io URL. It works perfectly and I love it, but I need to access it from my company LAN and DMZ. 
It doesn't work using public or private IP address nor the sandcats.io URL

Can someone help me with this typical network configuration please ?

Many thanks in advance !

Vivien

**Comment by paulproteus** [comment]
Hi there! Thanks for filing this. I'll get back to you shortly.

**Comment by paulproteus** [comment]
Hi @vivienkit ! First of all, thanks for looking into Sandstorm!

(Also - salut! J'ai noté que votre profil dit que vous êtes à Grenoble. Les meilleurs croissants j'ai jamais eu étaient à Grenoble !)

I have a question. Is there a single IP address you can use that works in all the situations where you want to access the device?

You could try using `xip.io` as documented here: https://docs.sandstorm.io/en/latest/administering/faq/#how-do-i-use-sandstorm-with-an-internal-ip-address

Let me know if that works for you. I hope I can help!

If there is no single IP address that works for you, then you'll probably need something like https://en.wikipedia.org/wiki/Split-horizon_DNS so that you can have a hostname that resolves to one IP address when resolved inside your network and the same hostname resolves to a different IP address when resolved outside your network.

Alternatively, you could _probably_ configure something interesting involving nginx and reverse proxying, where you change the `Host:` header that Sandstorm receives. This is because Sandstorm expects that it has exactly one `BASE_URL` and `WILDCARD_HOST`.

Let me know if the `xip.io` approach <https://docs.sandstorm.io/en/latest/administering/faq/#how-do-i-use-sandstorm-with-an-internal-ip-address> works for you. If not, we will see what we can do next. Thank you!

**Comment by vivienkit** [comment]
Hi Asheesh !
Thanks for your answer, i ll try your solution and give you an update soon.

Ps : je suis bien de Grenoble et il faudra que vous me dites où vous avez
trouvé ces fameux croissants :)

Vivien
Le 13 févr. 2016 03:31, "Asheesh Laroia" <notifications@github.com> a
écrit :

**Comment by paulproteus** [comment]
Au sujet des croissants: Hélas, je ne m'en souviens plus ! Il y a quatre
ans depuis j'ai visité Grenoble !​

On the topic of Sandstorm and your IP addresses: Do keep us posted!

**Comment by vivienkit** [comment]
Hi Asheesh,

I tried using xip.io and It works in my LAN : I can access the sandstorm
server which is in my dmz network from my LAN, but this it is no longer
reachable from the outside.
Is there a way to configure xip.io with 2 IP adresses, in order to add the
public IP address ?

Many thanks in advance !
Best regards
Vivien

2016-02-13 21:16 GMT+01:00 Asheesh Laroia <notifications@github.com>:

**Comment by paulproteus** [comment]
Hi @vivienkit ,

For now there really isn't a way to do this, unless you implement something resembling http://jensd.be/160/linux/split-horizon-dns-masterslave-with-bind or https://en.wikipedia.org/wiki/Split-horizon_DNS for the hostname you use for Sandstorm.

Sorry that we don't have a solution for you built-in to Sandstorm. Even if we supported having two acceptable BASE_URL values, someone might send you a link to a Sandstorm document on one, but you would want to give them the other one. So I believe you're going to want to implement split-horizon DNS. 

I'm going to close this since I believe there is no Sandstorm feature that would help you. Thanks for filing the issue, and I wish we had something we could do to help.
