### ISSUE TITLE
Possibility to revoke and replace app key and app ID

### ISSUE THREAD

**Issue by JamborJan** [sandstorm-io/sandstorm#1501]
As discussed with @kentonv and @paulproteus over email: it would be good if app authors can use new keys to sign apps. The app store would need to know the mapping from the new and old key and ID.

Copied from our email conversation:

> I think what we want is a "key replacement / revocation list" that would be checked into the Sandstorm codebase, which maps old appids to new appids and indicates if the old ID needs to be un-trusted. When someone loses their key, they would send us a pull request to add a mapping to their new ID. Sandstorm would then consider the new app ID to be an upgrade to the old.
> 
> By making this part of the source code, we automatically get transparency / auditability, which reduces the security concerns somewhat.

As far as I can see the following changes:
- Line 1 in `sandstorm-pkgdef.capnp`
- App ID in `sandstorm-pkgdef.capnp`
- the file `.sandstorm/pgp-signature`

Optional if the whole app is e.g. merged from a volunteer to the upstream authors the file `pgp-keyring`might also change.

**Comment by kentonv** [comment]
FWIW I haven't forgot about this and am hoping to implement something in the next couple weeks.

**Comment by kentonv** [comment]
This was fixed by 1543.

Please follow the instructions in this file to get a new app ID:

https://github.com/sandstorm-io/sandstorm/blob/master/src/sandstorm/appid-replacements.capnp

If you send me a PR by the end of the day Friday, I'll make sure it lands in this weekend's Sandstorm build, and then you'll be all set to do a new release!
