### ISSUE TITLE
Unable to install sandstrom in my ubuntu 14.04

### ISSUE THREAD

**Issue by vsagar9944** [sandstorm-io/sandstorm#1523]
While i am trying to install sandstrom using command 
curl https://install.sandstorm.io | bash 
I am getting following error
Sorry, the Sandstorm server currently only runs on x86_64 machines.

My System architecture (Using command **uname -a**)
Linux ist116 3.13.0-65-generic #106-Ubuntu SMP Fri Oct 2 22:12:08 UTC 2015 i686 i686 i686 GNU/Linux

**Comment by kentonv** [comment]
Hi Vidya,

Your uname indicates that you are running a 32-bit kernel (i686, whereas 64-bit would say x86_64). Sorry, but Sandstorm currently only supports x86_64 -- not because it would be hard to make it work on 32-bit machines, but because app packages include binaries and we don't yet have tooling that would allow them to be multi-architecture.

**Comment by paulproteus** [comment]
Perhaps one take-away is that the error message should link to a web page
indicating what a 64-bit machine is, vs what a 32-bit machine is, etc.

**Comment by vsagar9944** [comment]
Thanks @kentonv  i have installed in 64 bit machine working fine.
