### ISSUE TITLE
i got template error while loading second page of mailpile 

### ISSUE THREAD

**Issue by fathimashaibal** [sandstorm-io/sandstorm#1649]

**Comment by kentonv** [comment]
Hi @fathimashaibal,

Are you running Mailpile on Sandstorm? Where did you get it? There is no Mailpile package on the app market currently. We used to have one a long time ago, though, and AFAICT that one still works (though it has a bunch of other issues which is why we stopped distributing it for now).

Can you provide a screenshot of the issue you're seeing?

**Comment by ocdtrekkie** [comment]
I'm just going to close this one since there was neither a description, nor a response.
