### ISSUE TITLE
https not working

### ISSUE THREAD

**Issue by n-a-m-e** [sandstorm-io/sandstorm#1700]
https doesn't work after running install script.
Any help solving this is appreciated :-)

Steps to reproduce:
1. Did a debian 8.3 net install, did not install any extras.
2. Installed sudo, curl, bash
3. Added username to sudo group
4. Ran installer
5. Installer said it finished successfully told me to go to my sandcats subdomain

https of subdomain never loads and times out
http of subdomain prompts for username and password

went to the local address of my server to look at ssl certificate

firefox says:
<pre>
192.168.1.103 uses an invalid security certificate.
The certificate is not trusted because it is self-signed.
The certificate is only valid for client-does-not-support-sni.sandstorm-requires-sni.invalid

Error code: SEC_ERROR_UNKNOWN_ISSUER

https://192.168.1.103/
Peer's Certificate issuer is not recognized.
HTTP Strict Transport Security: false
HTTP Public Key Pinning: false
Certificate chain:
-----BEGIN CERTIFICATE----- MIIDAzCCAeugAwIBAgIBATANBgkqhkiG9w0BAQUFADBFMUMwQQYDVQQDEzpjbGll bnQtZG9lcy1ub3Qtc3VwcG9ydC1zbmkuc2FuZHN0b3JtLXJlcXVpcmVzLXNuaS5p bnZhbGlkMB4XDTE1MDkwMTAwMDAwMFoXDTI1MDkwMTAwMDAwMFowRTFDMEEGA1UE AxM6Y2xpZW50LWRvZXMtbm90LXN1cHBvcnQtc25pLnNhbmRzdG9ybS1yZXF1aXJl cy1zbmkuaW52YWxpZDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAJLk qqC97AhQs51xEnQ9OS/JfNabuQ4ZUHD6cKM0+IhvJGq+HKQwxa4d0T9bs6HZRw62 kRMMpF6pBjyRnCRjvQf4dfajc7amEAYP96mC0+dY7qyc6r8jWjBMtH4pBU4I3rSM rgsDPMIGekB+oklfoEqcQFFyggFppk3skHIkenx+1OCIHWc3KgazFDbrvTfLsL4q SExMfJRvgtNCFbS3cdWx8vxhRJreaFYjTou5IciszX/H4PTZq15aNb/az5HaiR7M EoTNgpjWtu/n+SD1qUdm6cEWU6SbAdvOF0f2CWe9L6dVb/Oe1Tn+VlFulbQvLQWr Uo1BgX/2wMPxvBzd5UcCAwEAATANBgkqhkiG9w0BAQUFAAOCAQEADs/4PukIoNid kBq/2j1htG9a/0hNFO4BKjO6U286aYVRJXS5KyV7U1aCcCd/sFVTCs1mYzObeEpy +Lvs/nzeaL3TyxOWBCIVv2NUbS4ljx61vQsrquYfD2x8oA1FhxVxfguHyhWjinPP 0b0L98CJghK2gZpWw2tHEljuK1oZOOVKxXI1A0gZCEmWCbs5pHPzf/G5+ExuOTfO iyLRgQXp5hCrPtzyerEmdSSS9P2dxEfIs8XAPogOA21ShhD8VhL9O458ltzKzuP8 guLg5DAwB9H0edNLM2/BG5nfA7o1CmP7Ee0gBj4BfZpCQQgytV/llwDoE2r8KtSN GOn61PiN9Q== -----END CERTIFICATE----- 
</pre>

chromium says
<pre>
Common Name (CN)	client-does-not-support-sni.sandstorm-requires-sni.invalid
Organisation (O)	<Not Part Of Certificate>
Organisational Unit (OU)	<Not Part Of Certificate>
Serial Number	01
Issued By

Common Name (CN)	client-does-not-support-sni.sandstorm-requires-sni.invalid
Organisation (O)	<Not Part Of Certificate>
Organisational Unit (OU)	<Not Part Of Certificate>
Validity Period

Issued On	Tuesday, 1 September 2015 at 10:00:00
Expires On	Monday, 1 September 2025 at 10:00:00
Fingerprints

SHA-256 Fingerprint	4E 1B FD DA E9 28 6F 8E 0B DF 7D 17 ED A3 4C 57
53 64 3B 64 60 C0 32 CC 70 7D FD 53 CE 88 43 AD
SHA-1 Fingerprint	E0 62 82 F2 A6 9D CA D6 D1 83 5E 35 C1 4E E2 77
D8 7C DB 42

</pre>

**Comment by kentonv** [comment]
Hi,

The certificate errors are because you are trying to access an IP address, but your HTTPS certificate certifies a hostname (specifically, the sandcats host), not an IP. So, let's focus on why the hostname doesn't work.

> https of subdomain never loads and times out

You probably need to open port 443 on your router, as Sandcats will map to your public IP.

> http of subdomain prompts for username and password

This could be an indication that your router has a common bug in which it does not correctly reply to requests addressed to the public IP when those requests originate from the internal network. It may be trying to show you the administrative interface on your router.

But I recommend trying to map port 443 and then try opening your sandcats server from both internal and external addresses (you can test external by e.g. turning off wifi on your phone and then accessing it over the mobile network).

Let us know how it goes.

**Comment by n-a-m-e** [comment]
THANK YOU :-) once i opened port 443 on my router everything worked. Now i'm just left wondering why I didn't think of this myself...
![727411](https://cloud.githubusercontent.com/assets/10303400/14034071/c23e87fc-f273-11e5-9e6d-8e423f420d15.PNG)

**Comment by kentonv** [comment]
Nah, honestly I think we do a bad job of making it clear to people that they need to open a port. Everything else is so automatic. We'd like to set up some automatic reachability test so that we can find out if there's a firewall in the way and warn you, without bothering people who don't have such a thing. It'd also be cool to support UPnP to automate it.

Anyway, glad it's working now! I'll close this bug.
