### ISSUE TITLE
Duplicate (copy) grains

### ISSUE THREAD

**Issue by zeigerpuppy** [sandstorm-io/sandstorm#1703]
In some applications (ShareLaTeX for instance), it makes sense to be able to duplicate grains.
For example, I may have a template LaTeX document (grain) that I would like to copy and then edit into a new document.
As a general option, it would be really helpful to be able to duplicate grains in this fashion.

**Comment by kpreid** [comment]
I was going to comment that this could potentially break assumptions by apps (that they are the sole holder of some private key / cap / secret) and then I noticed that this is already possible by way of requesting a backup and then immediately uploading the backup. Therefore, duplicating should definitely be supported to make this obvious. :)

Maybe this can be a non-core function implemented by pluggable grain managers/folders like there are supposed to be someday?

**Comment by kentonv** [comment]
Yep, cloning grains is on the roadmap.

Note that often it's the case that you really want to copy _someone else's_ grain, and that's more complicated. We'll need the app to tell us what permissions are required for it to be safe to make clones, and some apps may need to implement code for this rather than just let their storage be cloned directly, in case they store secrets.

**Comment by kpreid** [comment]
Hm, a hazard: an app using fancy storage strategies, or with deletion bugs, or internal backups, could have stored stale data that looks like it was deleted from the UI but can be extracted from the backup.

**Comment by ocdtrekkie** [comment]
My notion is that in a just world, grains do not have any secrets that would not be intended to be cloned with that app. You may wish to clone a password storage grain to give someone all your passwords, for instance. But your grain that talks to some external server with authentication should be using the Powerbox, and not storing secrets in the grain.

I definitely think the way to go is for apps to define certain roles a "can clone" permission. Document-based apps like Etherpad, EtherCalc, and Hacker Slides would be great examples where their data would make a ton of sense to share cloning rights publicly but not allow editing the grain itself, for instance. I'd want to be able to let people clone the slides from my Sandstorm talk, for example.

**Comment by ocdtrekkie** [comment]
@kpreid I don't think anyone can ensure a grain is definitely sanitized of its history, and I think we should assume and maybe warn as necessary that a cloned grain may potentially include all history of that grain. 

As it is, the download backup method circumvents any attempt to fully prevent users from cloning data by sending it to someone outside Sandstorm, but I would think if an app author thought their grain contents of their app shared too much data with a potential cloner, they could simply not grant any roles the permissions to clone the grain, so only the owner could do it (who, I believe, has all permissions by default).

**Comment by ocdtrekkie** [comment]
I would also suggest 'clone' and 'download backup' be offered by the same permission. Reason being that while on Oasis, non-subscribers could clone, if I wanted to allow people to make copies of a public document on my own server, they would not be able to create grains on my private server without an invite. They'd need to download the grain instead.

**Comment by kentonv** [comment]
Generally agreed with all of the above. But here's an example of where things can go wrong: Currently, when you open an Etherpad grain anonymously, you are assigned a random ID stored as a cookie. All requests bearing that ID are assumed to come from the same person, and so will be highlighted with the same color, etc. The IDs are stored in cleartext in the database. Therefore, anyone who can read the underlying database can potentially spoof other (non-logged-in) users.

This example is a very minor security problem, since in this case it only allows spoofing of users who were not logged in. But, it illustrates the kind of unexpected problem that can arise if cloning based directly on storage is allowed by non-authors. Other apps could easily have more serious problems. So, we have to be careful to educate app authors on these things. For people who are packaging someone else's app, it may be very hard for them to judge whether the app has any issues like this.

(FWIW, with the introduction of `tabId`, I should now change the Etherpad code to stop storing a secret token at all and instead rely on `tabId` to identify requests from the same user, since it can't be spoofed.)

Also, I think it's actually not entirely clear what should happen when cloning a grain that has outgoing capabilities. Should the clone get copies of the capabilities or not? I'm actually not sure; it probably depends on the app. But I do know that if it is not receiving copies, then copying the raw grain storage gets increasingly risky. While the capability tokens stored within it would not be valid in the context of any other grain, there is a question of whether you could make a copy, extract the tokens, and then somehow trick the original grain into using those tokens in an unexpected way.

**Comment by zeigerpuppy** [comment]
I agree these issues will be important.  App authors/porters should be made aware that they need to consider a cloning policy.  From the users perspective, it would makes sense to have an option on cloning to either:

a) enable capabilities of parent grain
b) copied grain has no sharing enabled

**Comment by zeigerpuppy** [comment]
a minimum use case at the moment may be to allow cloning of only grains that the user owns.  This would be useful in of itself.

**Comment by ocdtrekkie** [comment]
@CaptainCalliope mentioned he does the download/upload dance for making Office Hours notes.

**Comment by zenhack** [comment]
Was thinking about this again recently. Proposal:

- By default, grains may only be cloned by their owner, and any capabilities are broken.
- We add some options to the pkgdef to allow an app author change this default. The collections app will probably want to do this. The default is not to do so, since currently apps can assume that capabilities are not clonable (backups will break the caps).
- Later we can make cloning a permission that can be delegated to non-owners, though app authors will have to explicitly indicate in the pkgdef that this is safe. This makes it harder for an app author to not realize that this can happen, and prompt them to consider the implications.

One nice thing about the above is that it is implementable piecemeal; we can start by just implementing the first point and that will be itself useful.

---

Another question regarding capabilities occurred to me: what should happen to capabilities *provided* by a grain? i.e. suppose grain A holds a capability that is provided by grain B, and I clone grain B to make grain C. If A tries to use the capability, which grain should sandstorm invoke? Maybe we just pick the old grain and call MainView.drop for the capability in the new grain?

**Comment by kpreid** [comment]
As a user I'd be surprised if cloning a grain resulted in there being any references to it. In general I would expect the model to be that a copy is a snapshot (insofar as any grain is) until you start modifying it.

**Comment by ocdtrekkie** [comment]
I agree with said proposal wholeheartedly. Big thing as I mentioned above for when we allow app authors to add permissions for this, is that download backup and clone should be handled with the same permission, since it's not a safe guarantee someone on a given server can launch their own grains even if permitted to clone them. (And if they could, and successfully cloned them, they could also download a backup anyways.)

**Comment by kentonv** [comment]
The capabilities question seems really complicated. Should a clone (or backup) of a collection be shallow, or deep? (That is, should it clone each grain within it?) The answer, I think, depends on the use case -- I guess it should be presented as an option to the end user via the UI.

But then what if you have a more complicated application and you want to deep-copy some capabilities within it, but shallow-copy others?

I'm starting to imagine a UI here where you're presented with the whole capability graph and you choose where to draw the split between what's cloned and what's referenced. But that's kind of ridiculous. :)

Of course, the immediate goal should be just cloning a single grain, breaking all outgoing capabilities, as @zenhack suggests.

I agree with @kpreid that *incoming* capabilities probably should not be affected. They always continue to point to the old grain. But yeah I guess that means the clone needs to receive a series of "drop" messages when it first starts -- that's interesting.

**Comment by zenhack** [comment]
How would deep cloning even work? One wrinkle is that the owner of a collections grain is not necessarily the owner of all of the grains it points to, so the owner may not have permission to clone the referents.

**Comment by ocdtrekkie** [comment]
I'm going to close this, I think it's fair to say it's accomplished. (Some day, I'd like to be able to give other people the ability to clone/download grains, but that's a separate issue.)

**Comment by zenhack** [comment]
Quoting Jacob Weisz (2020-08-03 16:14:54)

>    (Some day, I'd like to be able to give other people the ability to
>    clone/download grains, but that's a separate issue.)

Yes, we should open issues about further improvements.
