### ISSUE TITLE
Grains fail to execute on fresh install on Debian 8.3, specifically with Scaleway default kernel

### ISSUE THREAD

**Issue by patrickod** [sandstorm-io/sandstorm#1759]
Setup: Debian 8.3 on Scaleways

```
root@scw-ca9206:~# uname -a
Linux scw-ca9206 4.4.4-std-3 #1 SMP Tue Mar 8 17:31:34 UTC 2016 x86_64 GNU/Linux
```

Symptoms: Sandstorm installs normally, and runs as expected allowing apps to be installed. However each time a grain is executed it fails, reporting an RPC error in the sandstorm interface like so:
```
Error: remote exception: expected result >= minBytes; Premature EOF
C++ location:(remote):??
type: failed
```

Inspecting the logs of the individual grains we see the following:
```
** SANDSTORM SUPERVISOR: Starting up grain.
*** Uncaught exception ***
sandstorm/supervisor.c++:1131: failed: seccomp_load(ctx): Invalid argument
stack: 0x5c12ee 0x5c071e 0x5e8fc9 0x5e8fba 0x4a84cf
```

Appears the issue is lack of support for seccomp on the default Scaleways installations.

**Comment by paulproteus** [comment]
Hi @patrickod ,

Thanks for filing this bug!

I'm hopeful that we can use this bug to get the attention of Scaleway.com support staff to add seccomp support to their default kernel. So for now, let's keep the issue open here, on the Sandstorm issue tracker, until we can provide a decent experience for users of Scaleway.

As context for Scaleway people: Sandstorm is open source Linux server software that lets users make collaborative or personal documents using a Google Docs-like interface. The Sandstorm community, rather than core team, maintains the apps that users use to create those documents, so the Sandstorm core team focuses on building a consistent user interface to any app, and making sure it's safe for users to run those apps. (There are many other accurate summaries of Sandstorm, but perhaps that's the most relevant one for now.)

Sandstorm uses seccomp to decrease the Linux kernel's attack surface, so that one app can't attack another app. Right now, since Scaleway servers disable seccomp, Sandstorm crashes before it can launch an app.

Over the past two years of me watching people set up Sandstorm, Scaleway is the only service provider I have seen that actively disables seccomp by default.

At this point, the Sandstorm team has a few options:

- Accept that Scaleway will keep seccomp disabled, and print a big sad failure message early-on during the install process to tell people Scaleway's kernels don't support Sandstorm, but if they do the complicated step of switching to a different scaleway.com kernel, then maybe it will work.

- Convince Scaleway to enable the seccomp syscall by default, so their users can get use Sandstorm on Scaleway servers without complicated fiddling.

I'd rather make Sandstorm useful to Scaleway customers than print a failure message. However, I'm not personally a Scaleway customer! Patrick, can you pass this along to Scaleway support, and see if you can convince them to add seccomp support back into their default kernel?

If they're concerned about security, please make sure they see the following articles.

- Why Sandstorm uses seccomp: https://sandstorm.io/news/2014-08-13-sandbox-security

- Why Google Chrome uses seccomp for sandboxing: http://blog.cr0.org/2012/09/introducing-chromes-next-generation.html

- How Sandstorm mitigated 95% of web app security, in our analysis: https://sandstorm.io/news/2016-02-29-security-track-record

- Sandstorm's overall security documentation: https://docs.sandstorm.io/en/latest/using/security-practices/

If they want to discuss this with me or other Sandstorm team members like @kentonv, I would be very happy to do that! Public or private discussion is fine, whatever works. I'm reachable on this ticket, and at asheesh@sandstorm.io.

P.S. I think Scaleway is great! I hope we can fix this technical issue.

**Comment by patrickod** [comment]
Have opened an issue with scaleway about this. Their internal reference is `I0ZTSR01`

**Comment by paulproteus** [comment]
Thanks so much, @patrickod ! I imagine it'll take 1-14 days to hear back conclusively, and I'm excited for that, whenever you do hear back conclusively.

**Comment by kentonv** [comment]
This has been fixed on Scaleway's end. (Though I'm not sure what their release schedule is like.)
