### ISSUE TITLE
Setup wizard: "Begin Standard Setup" after feature key already loaded

### ISSUE THREAD

**Issue by kentonv** [sandstorm-io/sandstorm#1774]
If the server already has a feature key, but we go back to the beginning and choose "Begin Standard Setup", we actually get Sandstorm for Work setup.

Either:
1. We should disable/hide "Begin Standard Setup" if there's already a feature key.
2. We should ask the user if they wanted to delete the feature key, and if so, do that.

**Comment by zarvox** [comment]
I favor option 1.  Disabling the button sounds like the right choice, since the copy for the Sandstorm for Work choice references the features of the Standard Setup choice.

Also, it's straightforward to implement, and I don't think people will actually go "I uploaded a feature key but what I really want is to get rid of these nice features" before finishing the setup wizard.
