### ISSUE TITLE
Admin Panel Redesign: User Accounts

### ISSUE THREAD

**Issue by neynah** [sandstorm-io/sandstorm#1822]
Required to ship User Accounts:
- [x] change "Guest" -> "Visitor"
- [x] "created" and "last used" dates should align vertically center
- [x] look into user accounts: DOM representation
- [x] add label "Show" above/beside role filter checkboxes
- [x] stack & left-align role filter checkboxes
- [x] add number count to role filter labels
- [x] figure out a way to communicate what "A" "U" "V" icons are
- [x] uncheck "Visitors" by default

Out of scope:
- [ ] pagination so that the table doesn't extend forever

Current mock-up:
![user-accounts4](https://cloud.githubusercontent.com/assets/855341/14724593/0f1ee5c2-07cc-11e6-8c05-760aaa2410e8.png)

Required to ship Manage User:
- [ ] change radio buttons to buttons that say "Upgrade to Admin", "Demote to User", etc.
- [ ] display more labels about status of each identity: "Can log in", "Org Member", "Demo"
- [ ] add save button at the bottom (disabled until changes are detected)
- [ ] change "Guest" -> "Visitor"
- [ ] any user can be upgraded to Admin
- [ ] cannot demote Admin to User or Visitor, cannot demote User to Visitor

Out of scope:
- [ ] deactivate identity
- [ ] assume role
- [ ] display identity IDs / other server-relevant details
- [ ] show warning for demoting roles
- [ ] enable some sort of re-parenting of grains for demoted Admins

Current mock-up:
![manage-user4](https://cloud.githubusercontent.com/assets/855341/14724547/cf8f0978-07cb-11e6-8497-966b26296e02.png)
[Previous mock-up](https://cloud.githubusercontent.com/assets/855341/14655098/a4cfffea-0635-11e6-9467-d0e0f6302272.png)
Note: status labels will get pushed to the next line only when there isn't enough horizontal space available

**Comment by neynah** [comment]
Perhaps we can have a single row that displays the current status (in this case "Admin") and then have 
"Make User" etc. as buttons in that row. I would still like for there to be an indication of what permissions each user has but perhaps that can be displayed in the same column as each button. Maybe you have other suggestions. :)

**Comment by zarvox** [comment]
I find the "Role" section a bit unclear.  I think I'd find it clearer if the role enumeration/explanation was separate from which-role-is-this-user and buttons-to-make-user-a-different thing.

It's also possible that we want to hide the "Visitor" section entirely under certain server settings.  Oasis, for instance, has no concept of visitors, due to having the `allowUninvited` setting set.

Today, there is only one bit which determines if you are an admin or no: `isAdmin`.  So that's easy to toggle.

On the other hand, there are several bits that affect your "is user vs. visitor" status:

* demo users, if enabled on the server, exist but expire (and IIRC are eventually removed?  I'll have to look at the code)
* `allowUninvited` (which is true on Oasis) implies open signups, which makes everyone into full users.  I think mrdomino might also have this enabled on his server.
* org membership makes you a user
* lastly, if your account has a `signupKey`, it is a user.

The only thing that you can reasonably modify on this page is `signupKey`, since it's the only thing that affects just the user you're looking at.  I haven't thought through what to do about demo accounts here, but I guess a "expired at $DATE" label would be reasonable.

I guess we could compute if the user is only a user *because* they have a signupKey, and only enable a "demote to visitor" button then?  We could show a message indicating why you can't demote the user when one of the other settings prevents it.

**Comment by neynah** [comment]
@zarvox Alright, I revised the mock-up above to display the details below the role actions. I do think this is cleaner & also more clear.

Are there cases where we'll have the disabled "Make Visitor" button? If so, what are your thoughts on providing additional information as to why that action is disabled?

I can adjust the design to include demo identities in the case that we'll be able to display some reasonable information about them.

**Comment by zarvox** [comment]
The top section feels better, thanks. :)  I may make slight adjustments to the copy explaining the roles, since today admins can't strictly speaking view all grains, but I'll take that on.

Some things that I intend to change in the user details page (but maybe don't need a mockup iteration for):

* Make the "User Accounts" breadcrumb in the header be a link back to the user accounts list page.
* Maybe change "User Accounts" to just "Users".
* Remove the Save button.  There are no changes to be taken here that aren't already buttons, unless we were expecting that admins would be able to edit user profile fields, which I think we can punt on until someone asks for it, especially since we don't support it today.
* Expand the content in each identity row to also include:
  * Each of the identity's verified email addresses.  For example, my GitHub identity has five verified email addresses, whereas my Google identity has just the one verified email address.
  * The identity's handle.
  * If we had icons for them, I'd maybe add an icon for preferred pronoun.

Some things to keep in mind for the future (ie, requires additional backend feature work, so orthogonal to this, but possibly will appear in the future):

* A button to deactivate/reactivate a user (prevents login, maybe prevents their grains from starting up?)
* A button "Log out all sessions" to expire all of the user's sessions and force them to log in again.
