### ISSUE TITLE
WILDCARD_HOST misconfigured

### ISSUE THREAD

**Issue by ojosedo** [sandstorm-io/sandstorm#1836]
I'm using Debian 8 for self-hosting sandstorm at my home and I'm having infinite loading grains and this alert in the settings page:

![wildcard problem](https://cloud.githubusercontent.com/assets/6635227/14517112/7334b440-01cf-11e6-9059-cb44e7cfd30c.png)

#### this is my sandstorm.conf:

```
SERVER_USER=sandstorm
PORT=80
MONGO_PORT=6081
BIND_IP=0.0.0.0
BASE_URL=https://catalepsofilia.sandcats.io
WILDCARD_HOST=*.catalepsofilia.sandcats.io
UPDATE_CHANNEL=dev
ALLOW_DEV_ACCOUNTS=false
SANDCATS_BASE_DOMAIN=sandcats.io
HTTPS_PORT=443
```

#### this is the log in the grain:

```
...** SANDSTORM SUPERVISOR: Starting up grain.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
```

#### I have open this TCP port:

80,443,6080,30025

I'm missing something?

**Comment by kentonv** [comment]
Strange, your server looks good from here: I can confirm the wildcard is responding as expected. But the symptoms you describe definitely sound like it isn't working from your browser, which is odd.

Are there any errors in the Javascript console? (Press F12 to open it.)

Are you using any unusual browser extensions? Sometimes we see extensions that purport to "block tracking" by blocking all cross-origin requests, even to subdomains, but that will break Sandstorm.

What happens if you open https://foo.catalepsofilia.sandcats.io directly in your browser? You should see: `No such grain for public ID: foo [404]`

**Comment by ojosedo** [comment]
Thank you, I solve the problem, it was a wildcard problem

my router do not hairpinning so I edit /etc/hosts but this do not support wildcards.

I found [this](http://stackoverflow.com/questions/20446930/how-to-put-wildcard-entry-into-etc-hosts) solution, thank you again, your suggest was the key.

**Comment by kentonv** [comment]
Great, glad you solved it!
