### ISSUE TITLE
Allow custom domain

### ISSUE THREAD

**Issue by mitar** [sandstorm-io/sandstorm#1845]
If I create a grain and share it with other users, I think it would be great if we could all use some custom domain to point to this our shared grain. Otherwise it is really tricky to open it: you have first go to Oasis, find it, click it, and so on. Similarly URLs in e-mail notifications could be nicer. And bookmarks.

cc @wrought

**Comment by kentonv** [comment]
Sandstorm is all about having lots of small grains and (soon) connecting them to each other. It doesn't make much sense to put a single Etherpad document on its own domain. We aren't really aiming to host the kind of monolithic apps that make sense to have their own domain. We might support it someday, but since there are already lots of great hosting services out there for that kind of thing, we prefer to focus on what Sandstorm can do differently.

There is also the problem that much of what Sandstorm does wouldn't work on a custom domain. We would not be able to display any Sandstorm UI at all on your custom domain because you as the domain owner would be able to tamper with it.

We do plan to support "short URLs" at some point; see #1680.

**Comment by mitar** [comment]
Could it be at least a redirect? So that I as an owner could create a custom redirect to that one grain.

**Comment by ocdtrekkie** [comment]
I'm trying to determine if there's a special need beyond "have a redirect to a grain link". Because you can always create a redirect that leads to a URL, and you could use a sharing URL for it. Like sandstorm.io/vote goes to a Sandstorm grain, but that's of course not set in Sandstorm itself.

**Comment by wrought** [comment]
Allow me to elaborate on a use case:

1. Our organization, [Omni Commons](https://omnicommons.org/) is attempting to use web collaboration tools.
2. We have people of all age / skill / experience levels, etc. We will have to provide training / support.
3. In the past, apps like Rocket.Chat or Wekan or Etherpad might have been nice to install and run ourselves, but the overhead of hosting these services is too great given our all-volunteer structure! Sandstorm.io specifically starts to address this issue, and enables us to have a platform where new apps can be easily adapted and deployed.

We are starting to use Sandstorm.io's hosting service as a test case of our primary collaboration tools. We created a user account called "omnicommons" and that user is hosting the primary grains we intend to use, essentially as a google doc is used--shared with collaborators one by one. 

However, there are certain aspects, features, and some bugs, that make the experience a bit less ideal for utilizing sandstorm.io in this way for group collaboration. Most of them are navigational issues!

Being able to use a custom domain would help alleviate this issue.

I also think that looking at WordPress (not on a technical level, but on a cultural level) would be a good lesson here. Let users create brands, identity, and custom domains on your platform or using your software. Then, they will actually want to use it!!!

;)

**Comment by zarvox** [comment]
FWIW, you can, today, configure something like nginx to 302 redirect your custom domain/paths to the appropriate Sandstorm grain URIs or even a sharing link so that new users can gain access if you want something to be public-ish.  For instance, @mrdomino runs a radio station out of a Groovebasin grain at https://r.wholezero.org/ (which redirects to the mrdomino.sandcats.io sharing link).  He links to it from https://radio.wholezero.org/ .  Does that approach sound like it'd work for your usecase?

You can also publish static content at arbitrary URLs, though the setup involves adding a DNS record (so Sandstorm knows how to route inbound requests for that URL).

**Comment by wrought** [comment]
@zarvox thanks, that's interesting, but indeed my issue is *navigation* not *redirection* -- it would be better to enable our users to more easily navigate to and between a handful of grains (pun intended!)
