### ISSUE TITLE
Look into suborigins

### ISSUE THREAD

**Issue by mitar** [sandstorm-io/sandstorm#1846]
I see that Sandstorm is creating new origins for new sessions. I think you might like this spec being worked on: https://w3c.github.io/webappsec-suborigins/

**Comment by kentonv** [comment]
Yes, we're aware of this and will keep our eye on it, as it could perhaps avoid the need for a wildcard host -- though only with sufficiently-new browsers.

Sorry, I'm closing this issue because it isn't a bug nor feature request. It would be great to send these kinds of things to the mailing list rather than file issues. Thanks.

**Comment by mitar** [comment]
Will do.
