### ISSUE TITLE
Are usernames unique?

### ISSUE THREAD

**Issue by mitar** [sandstorm-io/sandstorm#1849]
In [documentation it is not clear](https://docs.sandstorm.io/en/latest/developing/auth/) if usernames are unique. It is written that handles are not. But are usernames?

**Comment by zarvox** [comment]
`X-Sandstorm-Username` is the user's chosen display name and is not unique.

`X-Sandstorm-User-Id` is derived from the user's identity and is unique.  Use this if you want a unique user identifier, or (since you've been asking about Meteor) look at https://github.com/sandstorm-io/meteor-accounts-sandstorm

**Comment by mitar** [comment]
So none of user-friendly display name/usernames are unique? This pretty defeats the purpose of them. At least handles should be unique. So that one can change them through Sandstorm and all apps can automatically update them. Now an app might have a different handle because of the unique constraints. Also, now app have to handle updating it every time they update in Sandstorm. So it has to check for changes on every request. Tricky, tricky.

**Comment by ocdtrekkie** [comment]
The problem is that a Sandstorm server cluster like Oasis may have hundreds of thousands of users who will never interact outside of their own social circle. Saying I can't be "jake" because there's some other customer named jake who I can't even see the profile of is silly. The other problem is that sometimes the same user has multiple identities on a server via GitHub or Gmail or what have you.

Users should be identified by their unique User ID, and then you use the username or handle as appropriate for display. You always want to use the User ID to as your key for that user. In the case where it's possible for two users to have the same handle in your grain, you may wish to add a number of something within your app to distinguish them. The handle field is kinda their "preferred" handle, so they don't have to select one the first time they join a grain that uses it, but it's not authoritative.

**Comment by zarvox** [comment]
Adding on to what @ocdtrekkie said - in the brave federated future, you again can't enforce uniqueness on *any* user-chosen identifier, unless it chains into some other globally-unique namespace (like DNS domains + email addresses).

On [Zooko's triangle](https://en.wikipedia.org/wiki/Zooko's_triangle), you can only get two of three of (human-meaningful, decentralized, secure/unique).  X-Sandstorm-User-Id is decentralized and unique.  X-Sandstorm-Username is human-meaningful and decentralized.  If we give up decentralization as an attribute of user identifiers, then we cannot make federation automagically work in the future.

@mitar For questions like this, can I ask you to write email to the mailinglist at sandstorm-dev@googlegroups.com in the future?  It seems a more suitable forum than opening a dozen issues with questions on GitHub. :)
