### ISSUE TITLE
Use Blaze Components

### ISSUE THREAD

**Issue by mitar** [sandstorm-io/sandstorm#1854]
Shameless plug. :-)

But I think the UI would have much more consistency if you would use some components system, like Blaze Components. You can migrate slowly, because it is nicely integrated with Blaze.

**Comment by zarvox** [comment]
Sorry, but I don't think this one is going to happen.

To elaborate: I find Blaze very lacking in ergonomics.  The design of template helpers and data context inevitably makes *reading* Blaze templates a painful experience.  Additionally, event dispatch is bound by selectors rather than to specific elements.  You cannot understand the behavior of the JS without looking at the HTML, and you cannot understand the behavior of the HTML without looking at the JS.  And whenever you need to jump from one to the other, the only thing that binds them together is string matching across files.  This is problematic because the tooling for finding these sorts of errors is also lacking in the Meteor ecosystem.

While Blaze Components appears to have some provisions for improving event dispatch, it doesn't appear to do anything about limiting the scope of template helpers, which means the predicting the behavior of the HTML still depends on the entirety of a codebase's JS.  If the UI is to migrate to another system, it will much more likely be React, which thoroughly solves these sorts of scoping problems and has excellent ergonomics, while providing a much richer and precise set of lifecycle hooks.

I've thus far avoided writing a 9000-word rant on how Blaze is fundamentally the wrong design for maintainable frontend components, but I'd consider crystallizing all of my frustration into a reasoned critique some time if you'd appreciate hearing it. :)

**Comment by kentonv** [comment]
Yeah, if we are going to slowly migrate our UI code to something more-organized, it might as well be React.

**Comment by mitar** [comment]
I think the issues you are bringing out are addressed by Blaze Components, and I think porting effort is much smaller than what would porting to React require. Not sure what " it doesn't appear to do anything about limiting the scope of template helpers" exactly means, because In Blaze Components helpers are methods on the component.

But, I do not want to open a big discussion here. I wanted to point out that, and because I am currently looking into Sandstorm, I could help with this a bit, if there would be interest. But if there is none, no problem. :-)
