### ISSUE TITLE
Support for owner without all permissions

### ISSUE THREAD

**Issue by mitar** [sandstorm-io/sandstorm#1857]
I am trying to port my group decision making/voting app to Sandstorm. In that setting, the person who setups the decision making process would create a grain and invite all members of the community to join and make a decision, with permission to vote. But in many cases the owner/admin themselves should not be allowed to vote, because they are staff person/officer just facilitating the process. So in this particular instance, owner should have right to invite other people, give them permission to vote, but themselves should not be able to vote. In some way they should be just managing permissions/access. Of course, they could misuse this and invite themselves under some other account, but this is more problematic than what I care about, which is that the app should not be providing UI to the admin user to cast a vote in the first place. And how I have it currently, if you do not have a permission, you simply do not even see the ballot to vote.

So, is there a way to create owners which can give permissions to others, but them themselves do not have that permission exposed to the app?

I see one workaround, which is a negative permission, something like `cannot_vote` which would only admin have (because they get all permissions) and they override the permission `can_vote`.

**Comment by kpreid** [comment]
The problem with negative permissions (whether explicitly a feature or implied by something else) is that you can always make another identity that doesn't have them. That was my first thought.

Then I realized that this makes sense in an organization where new accounts are created administratively and not by just anyone.

A capability-pattern suggestion for how to obtain this functionality without complicating Sandstorm's core: Eventually it should be possible for grains to create other grains. Then the author of the poll would not create the grain themselves but ask a “trusted poll-creator grain” to do so — this would be _instead of_ having the poll app in their app list. That grain holds admin access to the individual poll grains but nobody else does. The creator grain would, in the minimal-involved-entities case, be owned by the administrator of the Sandstorm server. (You can't do better than that since the server owner can always get at the grain files directly.)

**Comment by mitar** [comment]
> The problem with negative permissions (whether explicitly a feature or implied by something else) is that you can always make another identity that doesn't have them.

That is not a problem, I just want to make owner have them, so that I disable them having a permission by default.

> The creator grain would, in the minimal-involved-entities case, be owned by the administrator of the Sandstorm server.

Yes, but that creator would still have full UI available, even if they would not be using it. Not nice.

**Comment by kpreid** [comment]
> Yes, but that creator would still have full UI available, even if they would not be using it. Not nice.

The creator would be another grain, not a person. It might have the _permission_ to edit the poll grain, but its _behavior_ would be to not do so.

Again, this always bottoms out in whichever humans administer the Sandstorm server; you can't not trust them, but this mechanism means that it's not _convenient_ for them to mess with things.

**Comment by kentonv** [comment]
Sorry but the owner can do absolutely anything they want with the grain. They can reach in and flip bits on storage if they want. There's just no feasible way in our model to enforce that the owner can't do certain things that other people on the grain can.

You can, of course, design your app to display a UI to the owner that is more-restricted than the UI given to other people. The owner could still hack the storage if they really wanted, but sometimes just making it hard from the UI is good enough.

**Comment by mitar** [comment]
> You can, of course, design your app to display a UI to the owner that is more-restricted than the UI given to other people. The owner could still hack the storage if they really wanted, but sometimes just making it hard from the UI is good enough.

But how can I know just from the list of permissions that somebody is an owner? You do not expose that fact.

**Comment by mitar** [comment]
Also, it would be great if that fact that the app expects owner to not do anything except manages users (of course they can, but there is big difference between what is social contract and what is enforced, I tend to believe most people do adhere to a social contract - they just have to be informed what it is - for example, by UI not showing them stuff to do) be also conveyed in Sandstorm UI.

If owner is seeing that they have all permissions in Sandstorm UI, but then app denies them those permissions it does not look very consistent.

So there are two types of permissions, enforced and advisory permissions. I agree that the platform should be strict on enforcement, but this is not only permissions which could be supported. Advisory permissions can help user mistakes. So permissions which are not there to protect against malicious users, but are there to protect against mistakes.

This is why creating usable and user friendly security is hard. Because it is not all in enforcement. It is also in how you communicate permissions over. There is difference between "you have those rights and feel free to execute them" and "you could do all this, but it is not really expected from you to do so in normal operation of the app, so don't".

**Comment by kentonv** [comment]
> But how can I know just from the list of permissions that somebody is an owner? You do not expose that fact.

Define a permission that is not part of any role. Only the owner will have it.

Mitar, you have a lot of really great suggestions and I appreciate the feedback you've been giving us. But there are a few things you are asking for that just don't fit with our model or our plans, or the potential benefit is just too small to warrant working on the idea vs. other things we could be doing. I know you feel strongly about your ideas and so you want to prove them by debate. Unfortunately I just do not have time to debate every one of these issues at length -- I've literally spent the last six hours or so replying to your threads and I'm out of time. So, I'm afraid I'm going to need to cut short the threads that definitely aren't going to work out so that we can focus on the threads that are actually constructive. I hope you understand.

In any case, sorry, we won't be implementing any explicit support for "grain owner with restricted permissions" in Sandstorm.

**Comment by mitar** [comment]
> Define a permission that is not part of any role. Only the owner will have it.

Yes, this is what I wrote as a workaround in the first post of this ticket:

> I see one workaround, which is a negative permission, something like cannot_vote which would only admin have (because they get all permissions) and they override the permission can_vote.

Not really perfect.

> In any case, sorry, we won't be implementing any explicit support for "grain owner with restricted permissions" in Sandstorm.

I think I found a better model which could be more aligned with your capabilities models in [this comment](https://github.com/sandstorm-io/sandstorm/issues/1852#issuecomment-212886748). If app could know how capabilities are shared between users, and if owner capabilities (genesis capabilities) would be able to be recognized, then the app could decide on how to handle a given capability.
