### ISSUE TITLE
Sync app permissions wich list of permissions in the code

### ISSUE THREAD

**Issue by mitar** [sandstorm-io/sandstorm#1865]
Currently, I have [permissions defined in the code](https://github.com/mitar/council-app/blob/master/packages/core/documents/user.coffee#L87), but then I have to keep them in sync with [sandstorm-pkgdef.capnp](https://github.com/mitar/council-app/blob/master/sandstorm-pkgdef.capnp#L164). It would be great if when creating a Sandstorm package, Sandstorm builder could somehow dynamically get the list of permissions.

**Comment by zarvox** [comment]
If the app spoke the capnproto UiView protocol directly, rather than using `sandstorm-http-bridge` to bridge to a TCP socket, it could respond directly to `getViewInfo()` (which enumerates the grain's' supported permissions and roles) with something dynamically generated in the target language however it likes.  To do that with node, you'd need to add support for implementing a capnproto RPC server to [node-capnp](https://github.com/kentonv/node-capnp/).  This would admittedly be a lot of work.

A more practical intermediate option might be implementing something with node-capnp that reads your existing permissions and writes out an up-to-date `.capnp` and then adding running that script to your `build.sh`.  Since capnp files can reference others, you could have your app's main `sandstorm-pkgdef.capnp` import a build-time-generated permissions table.

That said, it's not clear to me where you currently keep things like human-readable text labels for permissions and roles, so I'm not sure how you'd write such a script to do the autosyncing.

**Comment by mitar** [comment]
At least for Meteor apps: maybe Meteor app, that protocol could maybe be embedded into a DDP connection? Meteor could then connect to some Sandstorm endpoint with DDP? Or Sandstorm to the app, and call `getViewInfo` method or something?

**Comment by mitar** [comment]
>  Since capnp files can reference others, you could have your app's main sandstorm-pkgdef.capnp import a build-time-generated permissions table.

Any pointer how you reference another file?

> That said, it's not clear to me where you currently keep things like human-readable text labels for permissions and roles, so I'm not sure how you'd write such a script to do the autosyncing.

I do not yet have them, I was planing to just use internationalization library to do that. (So translation key is the computer string, which gets translated based on the language.)

**Comment by zarvox** [comment]
> Any pointer how you reference another file?

You can reference other files by importing them.  So if you generated some file `generated.capnp` with the contents:

```capnp
@0xd1993123a170dfde;
using Spk = import "/sandstorm/package.capnp";

const testCommand :Spk.Manifest.Command = (
  # Here we define the command used to start up your server.
  argv = ["/sandstorm-http-bridge", "8000", "--", "/opt/app/.sandstorm/launcher.sh"],
  environ = [
    # Note that this defines the *entire* environment seen by your app.
    (key = "PATH", value = "/usr/local/bin:/usr/bin:/bin"),
    (key = "USER", value = "sandstorm"),
    (key = "SANDSTORM", value = "1"),
    # Export SANDSTORM=1 into the environment, so that apps running within Sandstorm
    # can detect if $SANDSTORM="1" at runtime, switching UI and/or backend to use
    # the app's Sandstorm-specific integration code.
  ]
);
```

you could reference that from `sandstorm-pkgdef.capnp` like so:

```capnp
using Generated = import "generated.capnp";

# other stuff...

const myCommand :Spk.Manifest.Command = Generated.testCommand;
```

You could do the same with the permissions and roles, which you can import from `/sandstorm/grain.capnp`.  In particular you'll want to define a [constant](https://capnproto.org/language.html#constants) which is of type `List(Grain.PermissionDef)` for permissions and one of type `List(Grain.RoleDef)` for roles.

> I do not yet have them, I was planing to just use internationalization library to do that. (So translation key is the computer string, which gets translated based on the language.)

Cool!  Note that while Sandstorm has some [data types intended for localized text](https://github.com/sandstorm-io/sandstorm/blob/master/src/sandstorm/util.capnp#L29..L45) we haven't yet done the work to actually show the right localization (or indeed, anything but `defaultText`) yet.  But hopefully that gives you the right framework to target so things can upgrade smoothly with no breakage. :)

**Comment by mitar** [comment]
Oh, there are docs for the file format. Good. :-)

Thanks!

**Comment by paulproteus** [comment]
Hi @mitar,

Does the fact that there are docs for this obviate the need for Sandstorm itself to have the permissions sync feature, since apps and their build systems can implement this themselves?

For now, I will close it since apps can do this themselves, but if you disagree, feel free to re-open.

**Comment by mitar** [comment]
(Just a comment: I cannot reopen myself, but I can complain to be reopened.)

**Comment by mitar** [comment]
Otherwise, I am OK with permissions being managed through a script. I think it would be more useful if there would be documentation and examples how to do that, or even if default file would be setup so that it includes permissions list from another file. Because I still have now to manually figure all this out. @zarvox was very helpful here, but I do not expect issues should serve as documentation.

**Comment by mitar** [comment]
My current main issue related to this is #1851, which cannot be solved at "compile time" with a script.
