### ISSUE TITLE
Sandstorm for Work: Google Apps Integration Fails

### ISSUE THREAD

**Issue by johnjelinek** [sandstorm-io/sandstorm#1890]
I have my instance connected to Google Apps. After I login, I get redirected to the login page while on desktop. On my android phone, I get redirected to seeing my apps/grains as expected. I have restarted the service in systemd and rebooted the server. Same results. How should I troubleshoot this issue?

**Comment by johnjelinek** [comment]
Nevermind, it started working again ❓

**Comment by kentonv** [comment]
Hi @johnjelinek,

One possibility is that on desktop you were logged into a gmail account rather than your Google Apps domain account, and you have your Sandstorm server configured to disallow outside-of-organization accounts. Currently if you try to login through Google using an outside-domain account then it'll just drop you back to the Sandstorm login page with no explanation, which is a bug. Is that possibly what you were seeing?

**Comment by johnjelinek** [comment]
Nope, I was only logged into my Google apps account.
