### ISSUE TITLE
Remove "Home" label on the top bar when not signed into Sandstorm

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#2051]
Context:
- Right now, the home page of every Sandstorm install shows the "top bar", which has two items in it - "Home" and "Sandstorm" - but clicking either of them doesn't really do anything.
- See e.g. https://rose.sandcats.io/ for a non-splash-page example.
- See e.g. https://oasis.sandstorm.io/ for a splash-page-ful example.

Therefore, @paulproteus plans to submit a PR removing the top bar from being visible on the homepage. As this isn't something I'm going to do this _second_, discussion is very welcome.

**Comment by ocdtrekkie** [comment]
I am like... -0? I feel oddly attached to the top bar, but I don't know if I have a good reason for being so. (It's been with me since 2014?)

Thoughts:

- I feel like just having a login box in the middle of the screen (see rose.sandcats.io) is going to look super odd. You might need to expand the top of the Sign in box to at least say Sandstorm somewhere if you take it away.

- What about admin warnings? Are they visible and/or useful to people before they sign in?

- Will it be likely Sandstorm server owners might want to put other things on that bar or that other features might use that bar that make sense to display on the home page eventually? I guess if people wanted to add links or something up there on the right side, they could just use a splash page.

**Comment by zarvox** [comment]
Also -0 on dropping the topbar; it is arguably weird that if you're anonymously viewing a sharing link, and you click the Sandstorm logo at the top left, you get sent to a page that does not have that logo/affordance.

If we think the "Home" label is confusing/distracting/not useful, I'd be +1 on removing that.

I agree that having the <del>admin alert</del> maintenance message on the root page is reasonably desirable.

**Comment by neynah** [comment]
I'd be satisfied with just removing "Home". If other parts of that topbar provide meaningful functionality users don't want to lose then we should keep it. I can think of other ways to make the splash page as a whole look less fussy without removing the topbar entirely.

**Comment by kentonv** [comment]
Agreed with the -0 sentiment.

In addition to losing the maintenance message, you'd lose access to the "about sandstorm" link. While you can argue that neither of these is terribly important on the home screen, it seems likely that we'll add other things in the future that are important.

**Comment by ocdtrekkie** [comment]
The lead developer and the designer at the time agreed that the right answer here is to not display the word "Home". This is a very bite size fix. In fact, as far as I can tell, if you're signed in, you'll never see "Home", you'll always be at either "Apps" or "Grains" or some other page... Can we fix this by "just" blanking out the word Home (and equivalent in each i18n file, of course)?
