### ISSUE TITLE
On app install page: Remove top "Install {{appName}}?" question

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#2060]
Rationale: The question is embedded within the button at the bottom.

**Comment by neynah** [comment]
Current looks like:
![install-wekan](https://cloud.githubusercontent.com/assets/855341/15914774/7c5795e8-2d98-11e6-83e1-ecf2b7db8e66.jpg)

**Comment by neynah** [comment]
Proposal:
![image](https://cloud.githubusercontent.com/assets/855341/15914924/c7383832-2d99-11e6-937d-04a29c091057.png)

**Comment by paulproteus** [comment]
@neynah ah hah, I like your Proposal 2. Question: What do you think of moving the button to the right side as a Proposal 3? I prefer it there, but I am under the impression that we are already inconsistent.

**Comment by neynah** [comment]
I think moving it to the right would be slightly worse for most people and much worse for those with large screens. Worse because it will require more effort to find.

More about eye tracking [here](https://www.nngroup.com/articles/f-shaped-pattern-reading-web-content/) if you're curious.

![image](https://cloud.githubusercontent.com/assets/855341/15915191/02bae7b8-2d9c-11e6-80eb-75cb52837097.png)
![image](https://cloud.githubusercontent.com/assets/855341/15915223/5cf70fea-2d9c-11e6-9d1b-6509c7f57bc5.png)

**Comment by ocdtrekkie** [comment]
Strongly approve of keeping it on the left. I have a 27" screen.
