### ISSUE TITLE
Add a way to deactivate users

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#2078]
Right now, if a Sandstorm for Work team wants to disable a user account, and they are using email confirmation code login, then there is no way to "disable" the user account.

Proposal:

- In admin settings, under users, allow any Visitor or User or Admin to be changed to a state called Deactivated, where they can no longer log in, and where their session gets immediately terminated.

Curious for thoughts from @zarvox & @kentonv. This request comes in via a user; I am the messenger, but also I like this prospective feature.

**Comment by zarvox** [comment]
Strong +1.  This is essential for dealing with when someone is leaving a company, or when their account is believed to be compromised.

Would we also expect for grains owned by deactivated users to fail to start, or to still run if accessed by someone other than the deactivated user?  e.g. does a Piwik instance stop answering API requests if the owner's account is deactivated?

**Comment by paulproteus** [comment]
There are a few options.

- The grain could fail to start.

- The grain could run, but since the owner can't access it, any access
settings are frozen in time (but they can be delegated downstream as
always).

If we do the second of these -- what does this mean for the sharing graph?
The user could have made sharing links to their non-corporate identity just
before quitting. So... hmm.

**Comment by germakoci** [comment]
folks, I'm a non-tech, but from the user perspective to have the ownership settings frozen is not that good especially if you want to back-up and reload the entire grain or simply kick out accounts that indeed may be compromised and taken over (arrest among many other things?)

also, dosen't play well with the bus test, what if the owner dies or starts a non-tech diet ?

I think when reaching a certain number of collaborators on a given grain, the system should actually force the owner of a grain to choose who to share ownership with from the list of collaborators; 

or even better, for the collaborators getting access to the grain to be offered to choose a second owner, majority of nominations wins

**Comment by zarvox** [comment]
I agree that deactivating a user is not the end of the story here - there will also likely need to be a way for an admin to intervene, and (with a significant audit trail) perhaps migrate grains to new ownership, or start a user session impersonating the user in question.  Deactivating a user is one piece of that, though.

FWIW, I don't think forced sharing or a pool of collaborators being able to override the owner's wishes is the right way to handle this case.  If you want some sort of organizational override to deal with issues of process, that 1) probably needs to be worked out within some social structure, and that might be "the boss of the organization wins" or "democratic vote" or something else entirely.  I am much more comfortable with leaving that power with the site admin in an auditable fashion (as mentioned above), since the user already more-or-less has to trust the admin, so there's no new trust issue being created.

**Comment by germakoci** [comment]
@zarvox thanks for the comment, I now understand that an owner can back-up the grain, send it to someone else who could install it and take ownership. this was not clear to me.

**Comment by jparyani** [comment]
This is done by suspending accounts now. Fixed by #2402
