### ISSUE TITLE
Failed Linux Ubuntu Trusty installation.

### ISSUE THREAD

**Issue by scheung38** [sandstorm-io/sandstorm#2085]
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty

# curl https://raw.githubusercontent.com/sandstorm-io/sandstorm/v0.148/install.sh > install.sh
bash install.sh  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 73062  100 73062    0     0   130k      0 --:--:-- --:--:-- --:--:--  130k
# 
*** INSTALLATION FAILED ***

Your kernel does not appear to be compiled with support for unprivileged user 
namespaces (CONFIG_USER_NS=y), or something else is preventing creation of user 
namespaces. This feature is critical for sandboxing. Arch Linux is known to 
ship with a kernel that disables this feature; if you are using Arch, you will 
unfortunately need to compile your own kernel (see 
https://bugs.archlinux.org/task/36969). If you are not using Arch, and don't 
know why your system wouldn't have user namespaces, please file a bug against 
Sandstorm so we can figure out what happened.

You can report bugs at: http://github.com/sandstorm-io/sandstorm

**Comment by paulproteus** [comment]
Hi! Thanks for reporting this issue with the install script. To help further, I need as much of the following information as you can share.

- Is this on a hosting company, like Linode/Digital Ocean/Amazon/etc.? If so, what company?

- What Linux distribution are you using?
    - Actually, I see you say Ubuntu 14.04.3, so that's plenty helpful!

- Why did you use v0.148 of the installer, rather than the latest, and can you try again with the latest version of install.sh? See https://sandstorm.io/install for our recommendation on how to get the latest version of the installer.

- Since you are having user namespaces problems, I wonder: Are you also using Docker on this system? Docker is known to sometimes conflict with Sandstorm, but it should be possible to get past those problems, but it's helpful for me know that so I can debug accordingly. Any details you can provide about how you're using Docker are appreciated.

Thanks so much!

**Comment by paulproteus** [comment]
Hi @scheung38 ! I was hoping you could answer my questions above. Let me know!

**Comment by paulproteus** [comment]
Hi @scheung38 ! I'm going to close this issue for now, since I haven't heard from you in a few weeks. Let me know if you have more information, and we can re-open it and get your problem solved!
