### ISSUE TITLE
Mobile dropdown menu (from hamburger icon) apps & grains are missing icons

### ISSUE THREAD

**Issue by neynah** [sandstorm-io/sandstorm#2126]
Additionally,

**Mobile dropdown menu (from hamburger icon) blocks the entire screen**
- navigation becomes more difficult if you can't remember/see what your current UI view is

Current screenshot (Nexus 5):
![image](https://cloud.githubusercontent.com/assets/855341/16214613/14d531f2-370f-11e6-832e-ad7efe17742b.png)

I've also been wondering why we haven't aren't displaying the profile pictures for the user in the top bar or hamburger menu.

Suggested UI:

![image](https://cloud.githubusercontent.com/assets/855341/16287694/fe3e47e4-3899-11e6-8891-08b5d63d6828.png)

Although eventually I we may want to re-order the items in the list and style grains, apps, and account differently.

**Comment by zarvox** [comment]
Fixing the missing apps and icons grains is easy.  Adding the user avatar next to the account button is medium easy.

Changing the width and toggle behavior is *hard*, due to tradeoffs made in attempting to use a single DOM for both desktop and mobile.  The two have logically separate stacking contexts, but the browser binds stacking contexts to DOM structure.  My personal opinion is that there's really no good way around having two copies of the DOM for this.

Is it okay if we separate that second part into a separate issue, possibly separate from https://github.com/sandstorm-io/sandstorm/milestone/14 ?

**Comment by neynah** [comment]
> Is it okay if we separate that second part into a separate issue, possibly separate from https://github.com/sandstorm-io/sandstorm/milestone/14 ?

@zarvox That's more than OK. :)
