### ISSUE TITLE
Sessions do not refresh when apps update

### ISSUE THREAD

**Issue by kentonv** [sandstorm-io/sandstorm#2175]
When updating the app associated with a grain, it seems that already-open sessions do not refresh. We need them to refresh to get the new client code.

**Comment by kentonv** [comment]
(Pretty sure this is a regression. Maybe we need to hash package ID into the session?)

**Comment by dwrensha** [comment]
I think this is due to #2105.

**Comment by dwrensha** [comment]
To be clear: the grains themselves do restart and the *backend* sessions do get refreshed. The issue is that clients don't automatically refresh, because they just go through the usual "resume session" logic.

After hitting some difficulties in #2183, I'm now wondering whether it's actually worthwhile for Sandstorm to worry about this. Many (most?) apps should already be able to cope. E.g. Meteor has the [reload package](https://atmospherejs.com/meteor/reload). And I imagine that many app updates don't actually want an client refresh to occur.

**Comment by kentonv** [comment]
I think automatic refreshing is desirable for most apps, although I could imagine an app opting out of it.

Here's another solution: Whenever a grain's package is modified, store a new randomly-generated "salt" on it, which is hashed into the session ID. The salt is not derived from the package ID, so this no longer leaks info about the package. The salt doesn't even need to be kept secret, and can even be shared by multiple grains (making mass-update easier). If in the future we add a feature whereby apps can opt out of auto-refreshing, then it can be accomplished by not changing the salt.
