### ISSUE TITLE
grains should be allowed to offer capabilities to anonymous users

### ISSUE THREAD

**Issue by dwrensha** [sandstorm-io/sandstorm#2190]
`SessionContext.offer()` [currently fails](https://github.com/sandstorm-io/sandstorm/blob/3d882d1cc5a2dd33b1c1594b0fd0e809f531af96/shell/server/hack-session.js#L82-L85) for non-logged-in users. This implies that when an anonymous user opens a Collections grain, they have no way to actually navigate to the grains in the collection.

**Comment by zarvox** [comment]
There's an interesting usability tradeoff here, in that by making it possible to interact with large sets of objects anonymously, many users may not bother logging in, which works against them and their teams longer-term, since:

* they'll likely lose track of the grain, since it can't be added to their grain list when they're anonymous
* they may make changes, which apps will not be able to display any useful authorship information around
* we lose audit trail information - all we can say is that a capability passed through a token
* it's unclear to me what notifications, if any, anonymous users should receive (right now, I think the answer is "none")

It's not immediately clear to me precisely what anonymous users should be able to do.  There's a bit of prisoner's dilemma going on with logging in - nobody wants to do it if they're not required to, but everyone else benefits from the additional context when you do.

**Comment by kentonv** [comment]
I think it's pretty clear at least that anonymous users should be able to read a collection and open the grains within, which seems to be the subject of this issue. Whether they should be able to modify the collection is more debatable.
