### ISSUE TITLE
Sandstorm crashed while trying to update

### ISSUE THREAD

**Issue by mnutt** [sandstorm-io/sandstorm#2199]
I unfortunately don't have a lot to go on here, but sometime yesterday (7/10) my production sandstorm instance found a new automatic update, and crashed while trying to load it:

```
** Restarting to apply update
** Shutting down due to signal
*** Uncaught exception ***
sandstorm/util.c++:310: failed: unlink(path.cStr()): Device or resource busy; path = ../var/sandstorm/tmp/deleting.1467936000.0/proc/cpuinfo
stack: 0x44a872 0x44a872 0x44a872 0x4d57e5 0x4d54b0 0x4d53ed 0x48a4e4 0x48a2ba
```

I `sandstorm start`ed it back and everything is working fine now, but thought I'd mention it in case it's an obvious issue.

**Comment by paulproteus** [comment]
Thanks for reporting this. We'll look into it!

**Comment by paulproteus** [comment]
@kentonv +1 from me.

However, I notice that `tryRecursivelyDelete()` in `run-bundle.c++` also calls `recursivelyDelete()` and seems to be the thing that did the rename to `/var/sandstorm/tmp/deleting.", time(nullptr), ".", counter++`. It's odd that it wouldn't also check for `recursivelyDelete()` throwing an exception.

But since`../var/tmp` is at the start of the path that got deleted, it does seem that you fixed it in the right place, so +1.

**Comment by kentonv** [comment]
@paulproteus `tryRecursivelyDelete()` is only called from backend methods which could not possibly cause Sandstorm to fail to start up. I suspect that it had been called during a previous Sandstorm run, which is how the directory had been renamed to `deleting`, but that previous call failed, probably for the same reason.

The underlying error looks like it was caused by a package being deleted while a grain of that package was still running -- and that grain was presumably *still* running when Sandstorm restarted. I'm not entirely sure how that could happen.

@mnutt, were you doing anything interesting at the time the problem occurred?
