### ISSUE TITLE
Add curl & xz into Sandstorm bundle?

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#2214]
I've been experimenting with Sandstorm on Docker, and one thing I've noticed is it seems that Sandstorm depends on the host having `curl` (and maybe `xz`).

Specifically, when running Sandstorm in a Docker container that contains only the most bare-bones Ubuntu image, without `curl` or `xz`, I eventually see this in `/opt/sandstorm/var/log/sandstorm.log`:

```
** Updater died; restarting it
```

@kentonv I wanted to ask if you think that it's logical for us to, in the long run, bundle curl and/or xz into the Sandstorm bundle, so it's a complete system, and then could be run without any dependency installation using Docker. It's convenient if so, since it means that the base Docker image can be swapped-out willy-nilly.

CLARIFICATION: One thing I've noticed is the updater crash; I looked at https://github.com/sandstorm-io/sandstorm/blob/3ceb296eb6fd83929f0fa12fa1abf4d8b3ae956f/src/sandstorm/run-bundle.c%2B%2B#L301 to confirm that we call curl; I haven't verified directly that it's curl from the host.

**Comment by zarvox** [comment]
It's definitely curl from the host.

Could this be solved orthogonally instead by having the `Dockerfile` install the handful of dependencies?  I think we use curl/xz from the host because:

* the install script requires them to exist on the host a priori anyway
* the install can't modify itself from within the filesystem namespace applied by run-bundle without exposing a broader namespace somehow, which would break the self-containment.  The updater needs to be able to break the self-containment to apply the update, and since the assumption up til now had been that the host already had curl and xz, there was nothing to be gained by adding our own copy to the container.

**Comment by faddat** [comment]
@zarvox That's probably the best approach (having the Dockerfile install the utilities).

The next-best approach is pretty time consuming:  
use a system to build a docker image of only what is needed to run Sandstorm.  I'll know more when I finish speaking with @paulproteus soon :).

**Comment by kentonv** [comment]
Another possibility: When I finish my KJ HTTP bindings, we maybe wouldn't need to shell out anymore.

**Comment by paulproteus** [comment]
For what it's worth, I'm closing this issue to indicate I'm no longer requesting it.

I've written Docker-based instructions that are easy enough to follow without the need to address this issue: https://docs.sandstorm.io/en/latest/install/#option-6-using-sandstorm-within-docker

Thanks all!
