### ISSUE TITLE
id="grain-frame" attribute is not unique if there are multiple grains open

### ISSUE THREAD

**Issue by dwrensha** [sandstorm-io/sandstorm#2225]
I don't know if this actually causes any buggy behavior, but it did catch me by surprise when I was writing some tests!

**Comment by zarvox** [comment]
The id is only used for tests, and long-term we should move away from the tests using it at all.  It currently exists because IIRC there's not an ergonomic way to enter a frame with nightwatch other than by id.

I seem to remember there existing an alternative, multiple-step way to get your context into the grain frame from reading the spec/nightwatch code, but we haven't done the work of figuring it out and switching all the tests over to using it.

**Comment by dwrensha** [comment]
I was planning to put the grain ID into the iframe ID.

**Comment by paulproteus** [comment]
FWIW giving the grain-frame a name helps with docs, see e.g.
https://docs.sandstorm.io/en/latest/administering/self-signed/#common-problem-grains-dont-load
but I can live if it gets renamed.

**Comment by dwrensha** [comment]
@paulproteus: #2228 updates that doc comment to refer to the `grain-frame` class, which will remain as-is.

**Comment by paulproteus** [comment]
@dwrensha: You rule.​
