### ISSUE TITLE
Basic whitelabeling

### ISSUE THREAD

**Issue by kentonv** [sandstorm-io/sandstorm#2241]
We should add the ability to customize the following:

* Custom logo on the sign-in dialog.
* Ability to change the login button text and logo, especially for LDAP and SAML. E.g. you might want to change "with SAML" to "with Foo Corp Single-sign-on". Many organizations have a well-known internal name that they use for their SSO system.
* Remove the troubleshoot button, or modify its title text and link location.
* Remove the "send feedback" option in the upper-right menu, or change its text and link location.
* Use the server's title in the upper-left.

Whitelabeling should be a Sandstorm for Work feature: It's entirely cosmetic, and only really matters if you are presenting a Sandstorm server to a large audience.

**Comment by kentonv** [comment]
The following are not done yet:

* Ability to customize the text and destination of the "troubleshooting" link.
* Ability to customize the text and destination of the "send feedback" link.

Also, I had kind of intended that "use server title in upper-right" would affect everyone, rather than be an option.

**Comment by zarvox** [comment]
Sorry for the misunderstanding!  I understood the requirements stated in the ticket as being the set of requirements you received from a particular customer, so I interpreted the options listed there as being options given by the customer to us the implementers, rather than options given by us to the end user admins.  I guess I can implement the other bits (customizing the link text & targets) this week.

As for the "use server title in upper-left" by default: that intent wasn't clear from what was written above, and I'm not sure we should do that by default given that the default server title for all self-hosted servers is [the hostname from the BASE_URL](https://github.com/sandstorm-io/sandstorm/blob/master/shell/packages/sandstorm-db/migrations.js#L424).  Thoughts?

**Comment by valerytschopp** [comment]
I just tested with Sandstorm v0.173 and there a small issue with the logo customization.

I tried to upload this small PNG file: https://www.switch.ch/aai/design/images/switch-aai-small.png
But the **size** is not correctly handled, see:

![sandstorm-logo-customize](https://cloud.githubusercontent.com/assets/414099/17204207/7699c3f0-54a4-11e6-89ef-c8b942490402.png)

**Comment by zarvox** [comment]
Ahhhh, I must have only tested on square images.  This appears to be stretching to the image's height; we'd probably do better to preserve aspect ratio.

In the meantime, here's a 64x64 version of that PNG which I think approximately lines up with the "Sign in" text (link: https://cloud.githubusercontent.com/assets/307325/17225869/7e5247b8-54bb-11e6-914e-dbd4680aacab.png ):

![switch-aai-small-64x64](https://cloud.githubusercontent.com/assets/307325/17225869/7e5247b8-54bb-11e6-914e-dbd4680aacab.png)

And I'll write a patch today to make a smarter scaling behavior the default moving forward.

**Comment by paulproteus** [comment]
Per customer feedback, this options doesn't matter:

> Ability to customize the text and destination of the "troubleshooting" link.

This other option does matter, but I've moved it into a separate ticket because it's not as urgent (#2339).

> Ability to customize the text and destination of the "send feedback" link.

Given that, @kentonv can I ask you to close this ticket if you agree it's resolved? I figure since you re-opened it, you should be the one to close it. For that reason I'll assign it to you.
