### ISSUE TITLE
How to backup all grains (Without sandstorm codebase)

### ISSUE THREAD

**Issue by ahsanalishahid** [sandstorm-io/sandstorm#2272]
Hi There,

I was going through sandstorm docs. I can see that we have option to backup individual grain and complete sandstorm backup. 

Can anybody please tell me if I want to backup all grains only. Then what should I backup from /opt/sandstorm dir?

Thanks,
Ahsan

**Comment by paulproteus** [comment]
Hi @ahsanalishahid ,

Thanks for asking this question!

If you want to back up the grains themselves, you can find their data in `/opt/sandstorm/var/sandstorm/grains`.

However, take note - for this to be able to be restored properly, you will also need Sandstorm's own database. You can find that in `/opt/sandstorm/var/mongo`.

In my opinion, this kind of very fine-slicing backups is dangerous because it's easy to accidentally to not quite get enough data to restore everything you need. You could try backing up `/opt/sandstorm/var` as a way to back up just grain data. Sandstorm does carefully limit where it stores its own data, including grain data, into `/opt/sandstorm/var`.

Let me know if that answers your question, or if you need further help! I'll mark this as closed for now since the short answer is `/opt/sandstorm/var`.

**Comment by zertrin** [comment]
The documentation reads that
> In the long run, we'd like to enable automated backups as well.

Is there an issue or some roadmap item to track this? Couldn't find one by quickly searching.

Is it still on your radar?

From the documentation I undestand that doing a backup of a grain through the web UI is the "best" way of backing up an individual grain, ready to be restored on another server if needed.

> This will give you a ZIP file of the grain's contents. This contains the full writable state of the app, so you can restore it to any Sandstorm server.

Ideally I'd like to be able to script the generation of individual grain backups (as opposed to open every grain in the web interface and click on the button manually). Is there (or will there be) some kind of API for this?

**Comment by zertrin** [comment]
I'd like to add that backing up the full `/opt/sandstorm/var/sandstorm` does not only back up the grains, but also the apps. Since I can easily install apps from the app market, I'm not that interested in backing up this data, which can be voluminous in comparison to the grains.

For example on my server this is the data size repartition:

```
$ du -hd 1 /opt/sandstorm/var/sandstorm/
84M     /opt/sandstorm/var/sandstorm/grains
4.0K    /opt/sandstorm/var/sandstorm/backups
4.0K    /opt/sandstorm/var/sandstorm/downloads
2.8G    /opt/sandstorm/var/sandstorm/apps
4.0K    /opt/sandstorm/var/sandstorm/tmp
4.0K    /opt/sandstorm/var/sandstorm/socket
2.9G    /opt/sandstorm/var/sandstorm/
```

I am mostly looking for the 84M of grains, and don't want to backup the 2.9G of apps that I could reinstall from the app market if needed.

**Comment by ocdtrekkie** [comment]
Just backing up the `/opt/sandstorm/var/sandstorm/grains` should be adequate then. But you of course should be wary of whether or not the all the apps you have are available on the market. Or I suppose if there's any chance of them being delisted (though I do not believe there is currently a process by which a developer could do that).

**Comment by dwrensha** [comment]
> EDIT: Actually, not sure if that extracts the metadata then. :/

Grain metadata is stored in the Mongo database, so just grabbing the contents of `/opt/sandstorm/var/sandstorm/grains` would be insufficient.

**Comment by kpreid** [comment]
It would be good if grains _could_ be extracted individually and completely by file copy from a not-running Sandstorm instance. This is a useful fallback functionality for data recovery and migration.

Perhaps the grain metadata that is in the database could be copied into the filesystem for each grain (write-only, not 100% guaranteed to be in sync). Compare the precedent of the iTunes Library XML file.

**Comment by zertrin** [comment]
First question: Concerning the danger of having grain only backup, is the statement from the documentation 

> This will give you a ZIP file of the grain's contents. This contains the full writable state of the app, so you can restore it to any Sandstorm server.

to be understood as: 

 - _"to any Sandstorm server which has already the same app (and the corresponding version?)"_

or

 - _"to any Sandstorm server (the server will download the needed apps while restoring your grain)"_

?

Then I have a second question: what happens on the backend to prepare such a ZIP archive? I'm currently assuming the archive contains both the grain's own data and the sandstorm's grain metadata from mongodb.

And third question: Is there any way to get that ZIP via some sort of API call without needing to start the grain beforehand?

**Comment by ocdtrekkie** [comment]
You'll need either the same _or newer_ version of the app installed to restore the grain.

**Comment by dwrensha** [comment]
Right, if the grain's app is not installed, we currently do not try to automatically install it.

> Then I have a second question: what happens on the backend to prepare such a ZIP archive? I'm currently assuming the archive contains both the grain's own data and the sandstorm's grain metadata from mongodb.

Yep. Sandstorm fetches the metadata from Mongo and zips it up along with an archive of the grain's writable filesystem. The metadata consists of the app ID, the app version, and the grain title.
