### ISSUE TITLE
Make installer script more intuitive

### ISSUE THREAD

**Issue by kentonv** [sandstorm-io/sandstorm#237]
The installer script currently asks the user a series of questions to decide individual configuration settings. Defaults are offered for each setting, but the right choices vary widely depending on how the server will be used, and the defaults aren't even necessarily correct for any particular use case.

Instead, the install script should start by asking the user if they plan to use the server for production or development.

- **Production:** The server will be used to host the user's live data. BIND_IP should be set to 0.0.0.0 (or perhaps we should auto-configure nginx?) and BASE_URL and WILDCARD_HOST should be set to real hostnames (maybe we should actually verify that these hostnames work, as we've seen a lot of people enter bogus settings). The server does not need to start as root, though it may make sense to do so anyway if installing an initscript.

- **Development:** The server will be used to develop apps, or to hack on Sandstorm itself. BIND_IP should be 127.0.0.1 and BASE_URL/WILDCARD_HOST should be local.sandstorm.io. SERVER_USER should be the developer's own account, but the server must be configured to start as root as `spk dev` doesn't work otherwise. When we implement "local test accounts" (#150), those should be enabled in this mode.

**Comment by paulproteus** [comment]
Thanks for filing this, and I want to list a few other considerations while
we're making the installer script even more great. Overall I agree;
semi-apologies for the length of this comment.

## Other variables, and "nudges"

* We might want to set a variable like SERVER_NAME so that the invite
emails people send out can say "Welcome to {{ SERVER_NAME }}".

* We might want the installer to test that outbound SMTP works.
Alternatively, the Sandstorm shell could test this, as a background task,
and there could be a variety of post-install "Now that your Sandstorm
instance is running, do a few optional things to make it better" steps. I
for one am a big fan of pushing as much as possible into the Sandstorm
shell rather than into the install script. For the rest of this post, I'll
use the word "nudges" to refer to these hints that appear in the shell
about how to test/improve your Sandstorm server. I imagine they would be
like the notifications on e.g. LinkedIn, and you can dismiss or react to
them.

## Port binding/nginx/Apache

re: auto-configure nginx etc.: I'm torn about the best way to do this. Here
are some thoughts.

* In my opinion, most self-hosters are setting up Sandstorm on a machine
where they already have a web server. (Perhaps we can/should detect this.)
If they do have a web server listening on 0.0.0.0:80 then we should (in my
opinion) bind to 127.0.0.1 and tell them how to configure their web server
to pass traffic to Sandstorm. That way, their URLs never have to contain a
port number. We should detect nginx and Apache2 and offer configuration
snippets, that we conveniently leave in /tmp, and on Debian/Ubuntu we
should tell them what to type to add those to the running nginx/Apache
(e.g. `sudo a2ensite sandstorm.conf ; sudo service apache2 reload`).

** On the other hand, if they fail to set up nginx etc., they won't be able
to use Sandstorm. So that's kinda sad. So I guess for a setup intended to
be globally accessible, we should BIND_IP to 0.0.0.0:6080 by default, and
not say anything in the installer about nginx/Apache, and then we should
have a "nudge" that says, "Hey, 6080 isn't as good as 80. Set up port 80!"
and in that "nudge", link them to a Sandstorm wiki page about how to set
that up. Over time, we can automate more of that.

* If you don't have a web server already installed, Sandstorm could offer
to take over 0.0.0.0:80. I think the above actually would be fine even if
you don't have a web server installed. The "nudge" could detect if you do,
and change which wiki page it links to.

* For development mode, I guess we should avoid creating a service
listening on the global Internet, so probably we should BIND_IP to
127.0.0.1.

## On root or not

I like the idea of the production server not starting as root, which is
consistent with the current installer.We would need to use "sudo" to set up
the init script for now, though presumably in the future if they're using
systemd then this can be a user service rather than a system service. (cc:
@zarvox -- is it plausible to have a Sandstorm install be a user service,
just to avoid requiring the install script to run as root? would the user
service then be able to request to start on system start-up? also did I get
my systemd terminology wrong?)

Then again... the /usr/local/bin/sandstorm shim is super extremely
convenient, and it's worth requesting to be root just to install that
thing. So maybe we should still use root to do that. (Sample text: "This
installer uses sudo to set up Sandstorm to start on system startup and add
a helper program to /usr/local/bin. OK to do that? [yes]" but the existing
text might be OK.)

For development, it's kind of sad that we have to be root. I wonder if
using ptrace (via e.g. https://github.com/pgbovine/CDE ) would allow us to
do something other than the FUSE trick, for "spk dev". I can live with it
needing root in dev for now, anyway.

## Authentication

If we implement "password reset as login", then we probably want to prompt
for an email address and print out a one-time login key people can use. I
am under the impression we would permit this for development mode as well
as production mode -- @kentonv , is that your assessment too?

If so, I think this should be the default authentication mode, since the
alternatives are much harder to set up. So I think we should assume they
want that. So maybe we always want to ask for email address and to print
out a one-time login token.

## If you are installing Sandstorm in order to get an app

Just to think out loud -- if the reason you're installing Sandstorm is that
the (hypothetically) GNU MediaGoblin documentation, or the Sandstorm app
store, told you that was the easiest way to get GNU MediaGoblin, here's a
proposed flow:

Here's a proposed flow:

* User visits the app store listing for GNU MediaGoblin

* User clicks on "Create new Sandstorm install on my server to run GNU
MediaGoblin"

* User gets told, "Great! Go visit https://install.sandstorm.io/ in a new
tab and when you're done, copy-paste the address of your Sandstorm into
this form field: <input type="text" name="sandstorm_domain"></input>" and
then when they do that, a green "Install" button appears, and when they
click it, it redirects them to their Sandstorm instance with the existing
`install()` function, and their Sandstorm asks them the typical "Install
this app?" question.

In this case, it shouldn't matter if the user did dev mode or production
mode, so we don't have to worry about that.

It would be hypothetically nice if the install script could say something
like: "Thanks for installing Sandstorm, as a way to get GNU MediaGoblin!"
at the start of their install, but it might not be worth the bother.

## Defaults for SERVER_USER

* For production: create new SERVER_USER

* For development: use current user

## On hostnames

I think the script should verify the sandstorm shell's hostname actually
resolves.

I think we should make wildcard DNS configuration be a "nudge" within the
shell.

>

**Comment by paulproteus** [comment]
@kentonv -- I wrote this as a possible transcript for the new install script in production mode:

https://alpha.sandstorm.io/grain/oQgMvitLYC74fbcZ8FRNBb

I'll write up a proposed transcript for development mode once I get a +1 on this. My proposed transcript assumes that we implement "password reset as login" and sandcats.io before making these changes. I think it's OK to block these changes on those services, but want input on that.

@jadeqwang might have opinions too.

**Comment by kentonv** [comment]
Generally +1 to the above, but let's never tell the user "please type the following". We're already running on their machine. We can do it for them. :) (With their permission, of course.)

FWIW, at least on Debian, configuring a site in nginx is just a matter of dropping a config file in `/etc/nginx/sites-enabled`. We could automate that. I imagine Apache is similar.

I added some comments on your wave. In general let's think about how we can make the user read as little text as possible. :)

**Comment by paulproteus** [comment]
We got part of the way there with #359. I intend to reread this soon and see if we're actually done with this.

**Comment by paulproteus** [comment]
The installer now does the basic thing of asking if you're running a server, vs. developing apps, and so I believe it's now reasonable to mark this as closed. Future improvements can be separate tickets.
