### ISSUE TITLE
Document, somewhere, the mongo queries needed to simulate a user's usage amount

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#2370]
This ticket is "done" when there is some kind of documentation anywhere on how to use `sudo sandstorm mongo` to set and get a user's storage usage information. Documenting it on this ticket in a comment is :100: OK for the purpose of this ticket.

Context:

- In #2330 we will be implementing storage usage tracking within Sandstorm.

- However, we don't have it implemented yet.

- To allow Green Ant to begin testing immediately, before #2330 is ready, we can provide them some Mongo queries.

**Comment by jparyani** [comment]
Here is some rough documentation:

* Enter the sandstorm mongo shell by running `sandstorm mongo` in a terminal on the Sandstorm server.

* Find the id of the user you wish to edit. You can either do this from the browser by logging in as that user and running `console.log(Meteor.userId())` in a debug console, or from the mongo shell `db.users.find()` will list all users. It's a little bit confusing in the mongo shell since there are 2 types of users. The type you are looking for will have _id's that are 17 characters long, as opposed to 64+.

* Once you have a user._id, then in the mongo shell run `db.users.update({_id: "MY_ID"}, {$set: {storageUsage: 10000000}})`

**Comment by paulproteus** [comment]
@fgiorlondo I'd love if you can review this, and in the next 7-10 days, see if provides you enough information to manually test different quota situations.

It also might be obviated by #2372 or #2371 .

**Comment by kentonv** [comment]
This isn't necessary since the actual counting is now implemented.
