### ISSUE TITLE
Radicale multiple calendars

### ISSUE THREAD

**Issue by Wicked0ne** [sandstorm-io/sandstorm#2426]
I don't seem to be able to have more then one calendar per grain. Messing around with pure radicale it seems you are able to use a base url like http://site.com/radicale/USERNAME/ in your caldav client( I tested on davdroid on android and lightening in thunderbird). 

When I try this with the link that is generated from within the radicale sandstorm app, minus the ending /calendar.ics/ I get no errors and I can add a calendar from within a client. But if I create a new event on my phone and force a sync, the event never shows up within the radicale app. The same thing happens vice versa. 

Will it be possible to have multiple calendars in one radicale calendar grain?

**Comment by kentonv** [comment]
Hi @Wicked0ne,

Is there a particular reason why you want multiple calendars in one grain, rather than create multiple grains? In general, multiple grains is the way to go with Sandstorm apps.

**Comment by Wicked0ne** [comment]
I'm sorry if this comes off as noobish in regards to Sandstorm, but I run Sandstorm on an older machine and I'm trying to limit overhead. 

Also I've become accustomed to having multiple calendars(such as Work, Personal, Birthdays, etc) color coded and all displayed in one calendar interface. This way at a quick glance I can see what my week is like.

**Comment by kentonv** [comment]
The desire to have multiple calendars displayed together makes sense. Some day that would be possible using the Powerbox to connect calendars to each other, but that's not ready yet. We're also working on optimizations that should greatly reduce the overhead of having multiple grains of the same app running at the same time. But, these will both take a while.

The Sandstorm team does not directly maintain the Radicale package. It would be up to the maintainer to decide whether it makes sense to support multiple calendars as a temporary measure while waiting for Sandstorm to improve. It looks like there is actually a thread on this already:

https://github.com/synchrone/sandstorm-radicale/issues/17

Since that's a better place to discuss, I'll close this thread.

Thanks for the feedback!

**Comment by NicoHood** [comment]
I just came here by google, and I am not sure if my issue is the exact same as this issue. So let me describe my issue real quick:

I have multiple users with a calendar each. They all use it to report their events to me. For the final audience I'd like to have a merge of all those different calendars as caldav. This way nobody can manipulate the event of each other, making it harder for trolls and I can easily detect who is publishing fake events. I dont expect that to happen, but you never know!

Is that possible with radicale, and if not does this issue address it?

**Comment by ocdtrekkie** [comment]
So, as noted previously, the Radicale package for Sandstorm isn't maintained directly by the Sandstorm team, and actually isn't presently maintained at all.

@zenhack is making a new calendar app for Sandstorm called SandCal, and he might be interested in being aware of your use case, but I do not believe SandCal is close to meeting your needs at this time.

**Comment by zenhack** [comment]
Yeah, SandCal does not deal with this currenlty and I suspect would be lacking in many other ways. I've thought a bit about using the powerbox to tie multiple SandCal grains together they way @kentonv is discussing, but haven't moved on implementing any of it yet.

**Comment by NicoHood** [comment]
I reported the issue upstream then: https://github.com/Kozea/Radicale/issues/1193
