### ISSUE TITLE
grain backup and restore operations fail with "Operation not permitted"

### ISSUE THREAD

**Issue by dwrensha** [sandstorm-io/sandstorm#249]
On my Linode Arch Linux instance, when I try to back up or restore a grain the minibox subprocess outputs this error:
```
/ekam-provider/canonical/kj/io.c++:276: failed: miniposix::write(fd, pos, size): Operation not permitted; fd = 3
```

These operations used to work for me. The only thing I can think of that has changed is that I've upgraded my kernel from 3.16 to 3.18. Everything still works on my other VM, which is set up at kernel version 3.13.

**Comment by kentonv** [comment]
Can you build in debug mode (set CXXFLAGS=-g) to get a stack trace?

**Comment by dwrensha** [comment]
```
/ekam-provider/canonical/kj/exception.c++:59
/ekam-provider/canonical/kj/exception.c++:189 (discriminator 1)
/ekam-provider/canonical/kj/debug.c++:301
/ekam-provider/canonical/kj/debug.h:411
/ekam-provider/canonical/kj/io.c++:276 (discriminator 3)
/ekam-provider/canonical/sandstorm/minibox.c++:298
/ekam-provider/canonical/sandstorm/minibox.c++:199 (discriminator 1)
/ekam-provider/c++header/kj/function.h:212 (discriminator 4)
/ekam-provider/c++header/kj/function.h:136
/ekam-provider/canonical/kj/function.h:113
/ekam-provider/canonical/kj/main.c++:614
/ekam-provider/canonical/kj/function.h:136
/ekam-provider/canonical/kj/function.h:113
/ekam-provider/canonical/kj/main.c++:219
/ekam-provider/canonical/kj/exception.h:259
/ekam-provider/canonical/kj/exception.c++:464
```

So apparently it succeeds in writing to `/proc/self/uid_map` but then fails when writing to `/proc/self/gid_map`.

**Comment by kentonv** [comment]
Calling @amluto. Did something change in the kernel that breaks Sandstorm?

**Comment by paulproteus** [comment]
FWIW on my laptop I'm running a Debian 3.18 and running Sandstorm (as root)
successfully.

➜  ~  uname -a
Linux pathi 3.18.0-trunk-amd64 #1 SMP Debian 3.18.6-1~exp1 (2015-02-07)
x86_64 GNU/Linux


➜  ~  cat /opt/sandstorm/sandstorm.conf
SERVER_USER=paulproteus
PORT=6080
MONGO_PORT=6081
BIND_IP=127.0.0.1
BASE_URL=http://local.sandstorm.io:6080
WILDCARD_HOST=*.local.sandstorm.io:6080
MAIL_URL=smtp://localhost
UPDATE_CHANNEL=dev

**Comment by amluto** [comment]
It looks like minibox needs the same setgroups fix as everything else.

At some point, we should factor a bunch of this stuff out into a library.
For example, minibox should probably be using the seccomp sandbox as well.

--Andy

**Comment by dwrensha** [comment]
Yep, using the `setGroupsIfPresent()` function, like in supervisor.c++, fixes this for me.

**Comment by kentonv** [comment]
Oh duh, I forgot about minibox and it didn't occur to me that that's where the problem is here.

**Comment by kentonv** [comment]
> For example, minibox should probably be using the seccomp sandbox as well.

Eh. minibox is only used to run `zip` and `unzip` on user-provided data, to protect against tricks like "unpack a symlink and then unpack other things *into* that symlink, thus overwriting arbitrary parts of the filesystem". We don't run user-provided code inside minibox. So it's not as important to lock this down.

**Comment by kentonv** [comment]
> unpack a symlink and then unpack other things into that symlink, thus overwriting arbitrary parts of the filesystem

(To be clear, I have no proof that `unzip` has such a bug, although the error it gave when I attempted it looked more like is just coincidentally didn't work due to other implementation details, rather than being intentionally blocked.)

**Comment by jai6150** [comment]
After restoring back-up -- sandstormbackup.xva in XCP-NG, when trying to access the IP address - 10.0.0.213, I am getting this error -- 
“Sandstorm doesn't recognize this host name
If you we're trying to visit Sandstorm's main interface
If you are the server admin and want to use this address as the main interface, edit /opt/sandstorm/sandstorm.conf, modify the BASE_URL setting, and restart Sandstorm.”

Inside Console, I see this result -- 
![Screen Shot 2020-08-12 at 11 07 29 PM](https://user-images.githubusercontent.com/69599385/90050993-9baa9480-dcf4-11ea-98a0-5911ad67acbe.png)

Kindly support me with this issue, also how do i access to /opt/sandstorm/sandstorm.conf.

What exactly this issue is, and steps to solve this.

**Comment by ocdtrekkie** [comment]
@jai6150 You probably should file a separate issue rather than replying to an old/unrelated issue. Sandstorm does not work via IP address, you'll need to use some sort of DNS name. I assume this is a migration from the text, did you have a sandcats.io address or some other DNS name? You should be able to edit /opt/sandstorm/sandstorm.conf with the text editor of your choice from inside the machine. Something like `vi /opt/sandstorm/sandstorm.conf` perhaps.

**Comment by zenhack** [comment]
@jai6150, the section 'If you were trying to visit Sandstorm's main interface' should have a link to the correct host name; what happens if you click it?

**Comment by jai6150** [comment]
> @jai6150 You probably should file a separate issue rather than replying to an old/unrelated issue. Sandstorm does not work via IP address, you'll need to use some sort of DNS name. I assume this is a migration from the text, did you have a sandcats.io address or some other DNS name? You should be able to edit /opt/sandstorm/sandstorm.conf with the text editor of your choice from inside the machine. Something like `vi /opt/sandstorm/sandstorm.conf` perhaps.

Yes, Will file separate issue, thank you for the detail as well, this will help me getting into more details.

**Comment by jai6150** [comment]
> @jai6150, the section 'If you were trying to visit Sandstorm's main interface' should have a link to the correct host name; what happens if you click it?

yeah, that is the old version, and that works.. but I am trying to restore a backup which has all the grains.
