### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Snarkly** [sandstorm-io/sandstorm#2524]
Sandstorm could really use an social network like buddycloud or identi.ca Is it possible to add one of them to sandstorm? http://buddycloud.com/ https://identi.ca/

**Comment by paulproteus** [comment]
Hi @Snarkly ,

Short answer is - yes, slowly but surely.

The first one of these is "Mark", which is a federated social network for bookmarking. You can read more about it here:

**Comment by paulproteus** [comment]
...I managed to hit **Submit** early. I have now finished writing the comment before this one.

**Comment by paulproteus** [comment]
Also I'm going to mark this as "Closed" since there's no particular action to take from the Sandstorm dev team. Having said that, thanks @Snarkly for filing it! For conversations that aren't requests for a specific action by the Sandstorm team, the sandstorm-dev mailing list is a good place: https://groups.google.com/forum/#!forum/sandstorm-dev
