### ISSUE TITLE
Decide if we should rename "Identity providers" to "Login providers"

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#2584]
Context: In #2572 there is some discussion of the term "Identity provider(s)" vs "Login provider(s)".

Asheesh thinks we should consistently switch to "Login provider(s)." Drew is concerned that this would have impact on other places we say "Identity".

This ticket exists as a place to gather thoughts about what, if anything, should change. It can be closed once there is consensus on a plan. A separate ticket can be filed to track the work of _making_ the change technically.

It is OK if deciding takes a while. The fact that I'm filing this now is not a statement that I think it's urgent.

**Comment by ocdtrekkie** [comment]
Closing this because the admin panel already refers to these as "login providers", and the account settings refers to them as "linked credentials". I think much of the original Sandstorm team preferred login providers in the linked discussion, as it's easier to understand what it means.

Furthermore, in over three years nobody really seemed interested in adding any thoughts on this, and that is quite a while.
