### ISSUE TITLE
Nextcloud support?

### ISSUE THREAD

**Issue by Pseudonomy** [sandstorm-io/sandstorm#2600]
Are there plans to package nextcloud? Loving the software so far!

**Comment by ocdtrekkie** [comment]
Nobody is currently attempting it, though it should be possible to do so. However, the biggest question to me is how useful it would be in terms of Sandstorm. Because ownCloud is a large monolithic application which does a lot of things and has a lot of files and folders of data inside it, and Sandstorm prefers apps to be granular (do one thing per grain, more or less).

So it would not be taking the best advantage of Sandstorm to use the entirety of Nextcloud as an app. I suppose one could also try and break out the different features of Nextcloud into separate Sandstorm apps, but I suspect that would be a very large effort.

File sync using the ownCloud client (and I think one of the Nextcloud clients) is already possible with a Sandstorm app called Davros, and there are a couple of calendar and contacts type apps on Sandstorm that can be synced with by client apps as well. So a lot of the functionality you get from Nextcloud is already available in Sandstorm, and obviously all of those connectivity options would work with Nextcloud if someone were to package it.

So that's a long-winded way of saying it's possible but nobody's currently doing it as far as I know.

**Comment by dwrensha** [comment]
See also https://github.com/sandstorm-io/sandstorm/issues/89.

**Comment by ocdtrekkie** [comment]
I think I am going to close these. I gave Nextcloud a try recently, and it's very, very much more than ideally should run inside a Sandstorm container, to the extent that it's largely an app platform of it's own at this point. I know it's a popular request, so if someone was to successfully package it, I think it'd be sensible to allow it in the market, but I don't think we want to consider it an issue that it's not present or dedicate the Sandstorm community's limited resources to packaging it.
