### ISSUE TITLE
Davros X-frames issue (only in chromium)

### ISSUE THREAD

**Issue by zeigerpuppy** [sandstorm-io/sandstorm#2619]
When using Davros in chromium (OS X 10.9), icons and dynamic text (eg: client login links) do not display.  In the chromium javascript console, the following error appears:

I'm getting the error:
```
Invalid 'X-Frame-Options' header encountered when loading 'https://de9664es98236b60c932a0b26c8223bess.server.net/': 'ALLOW-FROM https://ss.server.net' is not a recognized directive. The header will be ignored. about:blank:1
Unrecognized Content-Security-Policy directive 'frame-ancestors'.
```

works fine in firefox

**Comment by dwrensha** [comment]
Which version of chromium are you using?

**Comment by kentonv** [comment]
Hi @zeigerpuppy,

[According to MDN](https://developer.mozilla.org/en-US/docs/Web/Security/CSP/CSP_policy_directives), support for `frame-ancestors` was added in Chrome 40, which shipped in January of 2015 (1.75 years ago). Is it possible your Chromium build is older than that? I highly recommend updating as there have been many security bugs fixed since then.

Since Chrome is an evergreen browser, the minimum version we support is the current stable version minus one. The current version is 53, so the minimum requirement is 52.

**Comment by dwrensha** [comment]
https://github.com/dwrensha/sharelatex/issues/11 leads me to believe that @zeigerpuppy is using version 30 of Chromium.

**Comment by zeigerpuppy** [comment]
the error occurs in v 41.0.2247.0 (64-bit) of Chromium in OS X 10.9.5

**Comment by kentonv** [comment]
@zeigerpuppy Does it happen in Chromium 52 or newer?

**Comment by zeigerpuppy** [comment]
in v56 it is fine

**Comment by kentonv** [comment]
@zeigerpuppy OK, thanks. Since this works in current browsers, I am closing this bug. Unfortunately, we are not able to support very-old browser versions. Sorry.
