### ISSUE TITLE
Consider splitting grain logs from backups

### ISSUE THREAD

**Issue by zarvox** [sandstorm-io/sandstorm#2636]
@zenhack on IRC noted that his irc-idler grain is currently running with debug logging, and as a result, he has a grain with 300MB of grain log and maybe 12k of actual sandbox content.  Downloading a grain backup, sadly, results in fetching all the logs to have a chance to look at the grain storage.

There is also no user-facing way to truncate the grain log other than deleting the whole grain.

A proposal:
- Make it possible to download the grain log, perhaps from the window that tails the debug log
- Then, don't include the grain log in the backup.  For the purposes of backing up and restoring grains, the log is not generally useful.  For the purposes of debugging, being able to view or download the whole debug log inline is probably better for users. 
- Possibly allow grain owners to truncate the log.

Another approach would be to make the logging code smarter and retain logs for a shorter window of time, rather than indefinitely.  This is a larger policy decision, though, and since we don't currently split the logs nor annotate them with any time information, this would probably be a bit more engineering work.

**Comment by ocdtrekkie** [comment]
It's also probably important because if someone has 300 MB of log, they may be shocked they are using their storage quota on Oasis with the content of their actual files, and have nothing they can do about it. (I considered suggesting not counting log content against the quota, but I think that could be abused.)

Is there any reason in normal operations that a grain should need to store 300 MB of log? Is it possible to specify a max size for the log?

**Comment by zenhack** [comment]
I think truncating the log at a somewhat arbitrary but generous limit would also be a good idea. Because of quota usage concerns, this probably ought to be size based rather than time. For reference, the 300MiB figure is logging *every* message that goes across the wire for an account that's been idling in channels with a total of > 2500 users, over the course of a month or two. Logs do not take up a lot of space, so it should be hard to find a bound that is neither burdensome from a debugging perspective, nor from a storage perspective.

For comparison, my OFTC grain has about ~70 users worth of traffic, and the logs are ~30MiB. So the growth may well be sub-linear.

**Comment by kentonv** [comment]
I've always intended that we should discard old logs, but never got around to implementing it.

I propose that we automatically truncate the logs to the last N kB on every supervisor startup.

Please tell me what N should be.

**Comment by zarvox** [comment]
Random stab at an answer: 2048kB (2MiB)?

**Comment by kentonv** [comment]
I could accept that, though I think my own random stab would be 64kB.

**Comment by zenhack** [comment]
2MiB sounds reasonable to me. Non-intrusive, but still very generous from a debugging perspective.

**Comment by zenhack** [comment]
But, re: doing it on supervisor startup, irc-idler is intended to be a (very) long-running daemon; modulo bugs I've found and upgrades there would have been no reason for me to shut it down the entire time that 300MiB log was being generated.

**Comment by kentonv** [comment]
Then I guess we need to define more specific behavior.

Stab: "Periodically, the supervisor checks the size of the log and, if it is over 2MiB, chops it to 1MiB."

Keep in mind that filesystems generally don't provide a "remove prefix" operation so we'll have to do a full copy of all the data we keep.

**Comment by zenhack** [comment]
Observation: If we're going to do this while the app is running, we need to take care to avoid losing stuff if the app logs something while we're copying things.

Any reason to not just use `logrotate(8)`? It seems to do what we need; we could just configure its rotation to be sized based, with a 1MiB cap, deleting things after the 2nd rotation.

**Comment by kentonv** [comment]
> Observation: If we're going to do this while the app is running, we need to take care to avoid losing stuff if the app logs something while we're copying things.

Since the app writes logs to stdout/stderr, which the supervisor redirects to the log, and the supervisor would also be the one implementing the rotation, this should not be a problem. The supervisor can stop receiving log messages temporarily while performing the rotation.

> Any reason to not just use logrotate(8)? It seems to do what we need; we could just configure its rotation to be sized based, with a 1MiB cap, deleting things after the 2nd rotation.

I suspect this would actually be very complicated to shoe-horn into the Sandstorm environment, whereas implementing some logic in the supervisor would be relatively easy.

**Comment by zenhack** [comment]
Fair enough; this sounds reasonable to me then.

**Comment by ar-jan** [comment]
Truncating the logs would be nice. I have a Gitlab grain which now has 1.3 GB of logs.

**Comment by zenhack** [comment]
My Freenode grain is up to 1.17 GiB now. Do folks have thoughts on a timeframe for this?

I'd consider it myself, but I haven't even had much luck building sandstorm from source in the past...
