### ISSUE TITLE
"About" page is maybe too indie, needs update

### ISSUE THREAD

**Issue by kentonv** [sandstorm-io/sandstorm#2722]
We may have outgrown our "about" page. The emphasis on our Indiegogo campaign is turning off our enterprise users.

Note that it's been over two years since the campaign and as such we are no longer obliged to show sponsor logos. Perhaps we should remove all the logos and pictures (including team pictures) and instead show "credits" as a textual list (inside a scroll box)? We may also want to update the copy at the top of the page.

**Comment by neynah** [comment]
Yeah I think we should probably scrap most of what's on this page (especially the Indiegogo campaign content). I also agree that the top text should be changed to reflect the language that we use on our website. Would be nice to give more room to the change log as well. I'm happy to propose specific styling changes/mock-ups but I probably won't get to it until sometime next week.

**Comment by ocdtrekkie** [comment]
I do not think we are still worried about being "too indie", though I still think it might make sense to move the Corporate Sponsors and Key Individual Sponsors into the scroll box with the rest of the backers. But I would be kinda sad to lose pictures/logos, because I kinda appreciate these entities a lot for helping get Sandstorm off the ground and I am used to seeing them there.
