### ISSUE TITLE
Static Publishing sends redirect on empty path with query params

### ISSUE THREAD

**Issue by mnutt** [sandstorm-io/sandstorm#2745]
I would expect the presence of query params to not affect the static file serving mechanism, but the presence of query params without a path results in a 303 redirect. I am serving a document at the root:

https://nb9yumstr4veb19ay29a.mnutt.sandcats.io/ (`200 OK`)

However when I add query parameters, it breaks:

https://nb9yumstr4veb19ay29a.mnutt.sandcats.io/?id=42 (`303 Redirect` to `//`)

The reason I came across this is I'm using a javascript-based photo gallery that uses History.pushState() with query parameters to change the URLs for individual photos. It works locally or in a regular webserver but doesn't work in sandstorm. As a workaround I can change the paths to `/#?id=42` but it would be nice if it worked with query params.

**Comment by kentonv** [comment]
It looks like the actual bug here is that the code in wwwHandlerForGrain() which appends "index.html" to paths ending in a '/' runs *before* the code that strips the query off of the path. So the appended "index.html" gets stripped off, and the path is left ending in '/'. Upon trying to read this file from disk, it is found to be a directory. So, a redirect is issued to append '/'.

Fix coming up...
