### ISSUE TITLE
Up token timeouts from 15 mins to 1 hour

### ISSUE THREAD

**Issue by kentonv** [sandstorm-io/sandstorm#2775]
In particular @ndarilek would like a longer timeout for e-mail login, but we should review other timeouts while we're at it.

**Comment by ndarilek** [comment]
Maybe there could just be a global `TOKEN_TIMEOUT` set to 60*60*24, that 
uploads/email tokens/other bits of the code use?

An hour seems good, but I'm genuinely wondering if it will be 
sufficient. Not everyone is glued to their technology, and I wouldn't 
put it past my parents and other non-technical folks I know to start the 
login process in the morning, forget that they did it, then be reminded 
when they check their email in the afternoon. When that fails, they'd 
start over again, but the sync delay they've imposed on themselves means 
at least a 20-minute wait (my mom was at 22 minutes with no email on her 
phone before I suggested switching to her laptop.) When login fails a 
few times, I then get grief because I don't just send my list as an 
email, use a Google Doc, or something everyone is more familiar with 
that just works. :) My parents live in the sticks, and only within the 
last few years had an internet connection that gave them more than 5-10 
gigs of data per month. Sounds terrible, but their previous alternative 
was a slow satellite link that failed regularly for days. It was a 
mind-opening experience to stay with them, to watch how it changed their 
habits, and to experience first-hand how it changed my internet usage 
patterns.

Thanks for considering this.
