### ISSUE TITLE
Can't invite others to use my sandstorm?

### ISSUE THREAD

**Issue by mpkosewski** [sandstorm-io/sandstorm#2796]
I'm trying to build my own cloud server and I finally managed to get mine up but I can't seem to figure out how to invite others to view my server and download stuff?

My buddy got the invite link I send to him, clicked on it and got to a menu to on sandstorm to send himself a login link and he gets a "internal 500 error". I have no clue how else I'm supposed to share my server? I'm using Davros right now as the app to share my stuff. 

Also, does anyone I want to share stuff with have to have sandstorm installed on their system as well or? I'm just wanting to share files, thats it.

any other recoomendations? Ideas? 
Thanks!

**Comment by neynah** [comment]
Hi @mpkosewski. Seems like email login might not be working for you. Could you go to your email configuration and attempt to send a test email?

**Comment by mpkosewski** [comment]
I'm looking at my email server options now. I can send a test email yes. This is what I get when I use mailgun to that particular person:

 },
  "reject": {
    "reason": "Sandbox subdomains are for test purposes only. Please add your own domain or add the address to authorized recipients in domain settings.",
    "description": ""
  },

**Comment by mpkosewski** [comment]
I sent an email to authorize my buddy and waiting for him to accept it. Not sure if that would be related but   figured it couldn't hurt. I do use mailgun as my smtp server. The login works and I can login via my windows 10 machine. 

-Mike

**Comment by kentonv** [comment]
@mpkosewski The "reason" message you see comes directly from your e-mail service. Since it mentions "sandbox subdomains", I'm guessing you are using Mailgun? As the message indicates, it looks like you've configured Sandstorm to send e-mail from a Mailgun sandbox subdomain. These domains are only intended for testing purposes and are only permitted to send e-mail to "authorized" addresses. Probably, your buddy's address is not authorized, hence the message was blocked.

The solution is to configure Mailgun with a "real" domain or authorize all recipient addresses that you need. I'm afraid I'm not too familiar with Mailgun so you'll have to study Mailgun's documentation on this.

**Comment by kentonv** [comment]
Closing because I think what I said above should solve the issue. Let us know if not.

**Comment by mpkosewski** [comment]
Sry for the late response, been swamped at work. I'll check it out tonight again. After looking into it a bit more it looks like that is the issue. I'll do more testing tonight but I did send my buddy an authorization email for Mailgun. Thanks for all the support btw! Still learning how all this stuff works exactly. If I run into further issues I'll let you know with more detail =) 

Mike
