### ISSUE TITLE
If the user visits Sandstorm at a host that shares an IP with the IP of the BASE_URL, redirect to BASE_URL

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#283]
Right now, when I surf to localhost:6080, I get:

```
Error looking up DNS TXT records for host 'localhost': queryTxt ENOTFOUND

This Sandstorm server's main interface is at: http://local.sandstorm.io:6080
```

I would prefer that this do a HTTP redirect to local.sandstorm.io:6080.

I'm open to figuring under what circumstances it should do this. Answers include:

* Always, if it's not a host that's part of the wildcard host spec.

* Only if the host where Sandstorm is being seems to DNS-resolve to the same IP address as the host of the BASE_URL

* Your idea here

**Comment by paulproteus** [comment]
@jparyani suggests that we special-case localhost, which would make fixing this simple, and probably suit me.

Another simple solution and low-breakage solution is to not do anything with a redirect, but make the `http://local.sandstorm.io:6080` thing be an `A HREF` so that I can click on it.

**Comment by kentonv** [comment]
The usual reason for seeing this error message is because you are trying to set up web publishing, and so you have intentionally made some other domain point at the same IP as your Sandstorm server, but you have not correctly set the TXT record. I think it would be bad to redirect in this case, as the user will have a harder time debugging the problem.

I think it would be OK to turn the URL into a link.
