### ISSUE TITLE
DNT header

### ISSUE THREAD

**Issue by zenhack** [sandstorm-io/sandstorm#2837]
I've noticed in the web-session.capnp schema, the DNT header is under the list of "never support," because:

> Sandstorm already prevents illicit tracking technically; no need for policy

I can think of at least one case where this reasoning doesn't follow: Piwik upstream respects the DNT header, but with sandstorm stripping it out, it will be unable to do so. Sandstorm prevents apps from performaing ilicit tracking of users of a grain, but it is still valuable to give grain owners the ability to respect the preferences of users elsewhere on the web.

**Comment by kentonv** [comment]
I believe Piwik on Sandstorm respects `Navigator.doNotTrack` in Javascript.

Generally, grains can export two kinds of HTTP interfaces: UIs and APIs. Grain UIs are, as you know, heavily sandboxed such that it wouldn't make sense to use them for tracking. Piwik instead uses an API endpoint. But API endpoints are also restricted such that you cannot really cause a browser to load resources from them. They can only be accessed via XHR requests (in order to add the proper `Authorization` header). Since XHRs are necessarily made from Javascript, this implies that the client has the opportunity to read the `Navigator.doNotTrack` value in Javascript.

In general I feel like with the modern web platform, headers are not the right place to communicate these kinds of things, and Javascript is. So I hesitate to go adding support for a bunch of headers, mainly because I want to keep the WebSession interface as simple as possible. But I could be convinced.

**Comment by zenhack** [comment]
I'm all for keeping websession as simple as possible, and I was unaware of the JavaScript API. I think it probably doesn't make sense to add it now; at most it would be a move from never to "maybe someday, but not important."

While not applicable to sandstorm I will point out that the header is still necessary to deal with non-js tracking mechanisms, so I think in this case just having the API probably wasn't an option.

**Comment by zenhack** [comment]
I'm going to go ahead and close this; might make sense to revisit if it ever becomes possible to contact a grain from the browser without javascript, but not applicable for now.
