### ISSUE TITLE
Integrate Sandcats into the Sandstorm installer, behind a getopt flag

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#286]
Context:

* https://github.com/sandstorm-io/sandcats is a dynamic DNS service written with Sandstorm in mind.
* Wildcard DNS is hard for people, see #114 

This issue exists to track the following changes:

* Modify the Sandstorm installer so that users can optionally automatically configure a hostname for their server.
* Place that behind a `getopt` flag, so that no one does this by accident for now, so I can do some testing/feedback-gathering.

**Comment by paulproteus** [comment]
Notes to self about implementation strategy here:

* sandcats uses a trust-on-first-use client certificate to authenticate.
* We're going to have to generate these in the Sandstorm installer.
* The easiest way to do this is to ask `/usr/bin/openssl` to generate a self-signed cert at install-time.
* Therefore, we'll want to make sure that program is available. On Debian/Ubuntu, we can do `sudo apt-get install openssl` if the user is OK with it.

**Comment by paulproteus** [comment]
*Please add comments with feedback from testing here*! Thanks!

**Comment by kentonv** [comment]
Neat, it works! (I registered kenton.sandcats.io.)

Misc comments:

* A lot of the regular configuration questions (like "expose to localhost only" or setting BASE_URL) no longer make sense to customize when using sandcats, so we should probably skip them.

* Is it time to start packaging nginx with Sandstorm, or offering to auto-configure the user's existing nginx install?

* I am pretty sure that if I didn't know that a key was generated, I might happily delete my new sandstorm install and start over in an attempt to configure things differently. But, if I actually did this, I'd lose my registration, because the key is in the install dir and we don't have a recovery mechanism yet. I wonder if it makes sense to make a copy of the key in the user's home directory or something, and/or suggest to the user that they back up this key. Or, maybe we just need to accelerate plans to implement recovery.

**Comment by paulproteus** [comment]
My take on the above is:

* re: remove config options (at least, by default): Yeah, I agree. I'll take care of most of those in this pull request.

* re: nginx bundle/config: I'm tentatively +1 on this. To me, it seems a separate pull request, though.

* re: recovery: I'm +1 on adding some verbiage about the importance of backing up that directory for now.

**Comment by ocdtrekkie** [comment]
This is done now, right?

**Comment by kentonv** [comment]
Indeed.
