### ISSUE TITLE
Failed to build from source in vagrant environment.

### ISSUE THREAD

**Issue by iramykytyn** [sandstorm-io/sandstorm#2897]
When I try to build sandstorm from sources in vagrant it is failing with next error:

install: sandstorm/sandstorm.ekam-manifest
test: capnp/fuzz-test
install: node-capnp/node-capnp.ekam-manifest
compile: node-capnp/capnp.cc
  /ekam-provider/canonical/node-capnp/capnp.cc:29:10: fatal error: 'node.h' file not found
  #include <node.h>
           ^
  1 error generated.
jstest: node-capnp/capnp-test.js
  full log: tmp/node-capnp/capnp-test.js.log
==== build failed. You might need to: make update-deps ====
Makefile:257: recipe for target 'tmp/.ekam-run' failed
make: *** [tmp/.ekam-run] Error 1

**Comment by kentonv** [comment]
I think this happens when Meteor has not yet installed the specific version required by Sandstorm.

I think if you cd into the `shell` subdirectory and run `meteor` (no arguments), it should install the right version. After it has done that, kill `meteor` and retry `make`.

Let me know if that works...

**Comment by iramykytyn** [comment]
Looks like cloning repo and building sandstorm from scratch resolved the issue.
