### ISSUE TITLE
Feature Request: robots.txt

### ISSUE THREAD

**Issue by zombiezen** [sandstorm-io/sandstorm#2910]
While I could run a reverse proxy to add it, it's inconvenient to do this when running with sandcats.io.  I'd love to have a checkbox in admin panel where I can say "add the minimal robots.txt to disallow web crawling".

**Comment by kpreid** [comment]
Since there are a few other things that want "put this file on your site at this path" maybe this should be implemented, if not exposed in the admin UI, as a means to add arbitrary static files?

**Comment by kentonv** [comment]
I'd be happy to accept a PR to add configuration of robots.txt, or one which just gives everyone a deny-all robots.txt (since Sandstorm isn't currently indexable anyway).

I'm less keen on arbitrary files. I worry that people could break things this way, if there are conflicts. Of course, you can always set up a reverse proxy that maps specific paths to whatever you want.

**Comment by zombiezen** [comment]
I'll take a look when I get cycles.
