### ISSUE TITLE
Install sandstorm, listening to port 80 

### ISSUE THREAD

**Issue by baloe** [sandstorm-io/sandstorm#2911]
I'm struggling to make sandstorm available through `sandstorm.mydomain.tld`.

I tried to follow the instructions on these two sites
- https://docs.sandstorm.io/en/latest/install/
- http://gemlog.ca/index.php/2-uncategorised/1-howto-self-host-sandstorm-io
and did the following:

1. Set up the subdomain `sandstorm.mydomain.tld` with SSL using Lets Encrypt
2. Enable wildcard `*.sandstorm.mydomain.tld`
3. At this point, when browsing `https://sandstorm.mydomain.tld`, I got to see a default web page and SSL is indicated to work fine. So I deleted the `index.html` file in the corresponding directory and now got the _403 Forbidden_ message.
4. I installed sandstorm via `curl https://install.sandstorm.io | bash` selecting `http://sandstorm.multus.io:80`. I did not receive any error message, but curiously `sandstorm.conf` lists Port 6080 while also using the above url indicating port 80.

Now, `https://sandstorm.mydomain.tld` still returns error 403 while  `https://sandstorm.mydomain.tld:6080` takes me to sandstorm.

How can I make sandstorm available through  `https://sandstorm.mydomain.tld`?

Thank you

**Comment by baloe** [comment]
I begin to realize that my installation won't work anyway for I am using Let's Encrypt which does not issue wildcard certificates.
That's a bummer.

**Comment by kentonv** [comment]
Hi @baloe,

It sounds like you have some other web server -- e.g. Apache or nginx -- running on your machine and using port 80. When the Sandstorm installer detects that someone else is already using port 80, it automatically switches to 6080 instead.

You will need to configure your other web server to proxy requests to Sandstorm. There are some tips on this in the docs here: https://docs.sandstorm.io/en/latest/administering/reverse-proxy/

Note that if you were going to use a sandcats.io domain, then you could simply uninstall your other web server and let Sandstorm take ports 80 and 443 directly. However, if you aren't using sandcats, then you need to keep your other web server as a proxy in order to do SSL termination, since currently Sandstorm doesn't provide any way to configure it with a non-sandcats certificate.

Unfortunately you are correct that Let's Encrypt will not work. :( However, if you use sandcats.io, we can issue you a free wildcard certificate. (I wish we could issue free certificates for arbitrary domains, but it would cost us too much!)

**Comment by kentonv** [comment]
(I'm going to close this issue since I think I answered your questions but feel free to reply if not.)

**Comment by baloe** [comment]
you are right about nginx and thanks for the link to the documentation which I will look into when I decide to purchase a wildcard ssl certificate.
For now I would go with the sandcats.io domain, but it still won't work giving me a "Your server never started listening... E_NEVER_LISTENED" error.
This time 6080 and 6081 are no longer blocked by the firewall. sandstorm.conf reads:
```
SERVER_USER=sandstorm
PORT=80
MONGO_PORT=6081
BIND_IP=0.0.0.0
BASE_URL=https://myname.sandcats.io
WILDCARD_HOST=*.myname.sandcats.io
UPDATE_CHANNEL=dev
ALLOW_DEV_ACCOUNTS=false
SMTP_LISTEN_PORT=30025
SANDCATS_BASE_DOMAIN=sandcats.io
HTTPS_PORT=443
```
I tried https://github.com/sandstorm-io/sandstorm/issues/2632#issuecomment-252371516:
```iptables -I INPUT -i lo -j ACCEPT```
without success.

When browsing myname.sandcats.io I get to see a default page set up by VESTA cp.

Any idea?
Thanks

**Comment by baloe** [comment]
`/opt/sandstorm/var/log/sandstorm.log` reads:
```
** Starting Sandstorm at: Tue Apr 11 21:07:55 2017
*** Uncaught exception ***
sandstorm/run-bundle.c++:1771: failed: bind(sockFd, reinterpret_cast<sockaddr *>(&sa), sizeof(sockaddr_in)): Address already in use
stack: 0x45d835 0x45aa79 0x459c39 0x459c2a 0x5033a3 0x503ea0
```

**Comment by baloe** [comment]
resolved the issue by changing the HTTPS_PORT in sandstorm.conf to one that nothing else listened to. **It would have helped if I had been asked to specify a port in the installation dialog**, but this way the installation could only fail. @kentonv
