### ISSUE TITLE
Sandstorm listens but not loads if you don't attach the :port at the browser url

### ISSUE THREAD

**Issue by erm3nda** [sandstorm-io/sandstorm#2915]
Hi, i am testing around Sandstorm and finally get stucked.

I can actuall load the webste using app.mydomain.com, but just create a script src into the dom, the title and nothing more.

If i attach the port number to url :6080 it totally works.
I have read a couple of redirection tricks, even tried to rewrite url (did nothing) and no one presented any change.

So, i wonder if there is any way to remove the :6080 port at the url. Of course i removed it from sandstorm.conf :-B before.

I suspect thats there's some cache at any point and not my nginx cuz the other url changes (even the wrong syntax) made a difference.

I can post all docs config if needed. It will be cool if i found a way to just config the sandstorm in other way, not really need to fix that from the nginx.

Regards.

**Comment by kentonv** [comment]
Hi @erm3nda,

It sounds like you installed Sandstorm on a machine which already has some other web server (like nginx or Apache) running on port 80. When Sandstorm detects this, it automatically moves to port 6080 instead.

You will need to configure nginx to proxy requests to your Sandstorm server. There is documentation on that here: https://docs.sandstorm.io/en/latest/administering/reverse-proxy/

I'm going to close this issue since it's not a Sandstorm bug, but feel free to ask further questions on the mailing list or IRC!

**Comment by erm3nda** [comment]
I alredy have a subdomain loading the content over the port 6080 port with nginx (vestacp).

The domain loads the sandstorm default content, but doesn't show anything. It only works if i do attach the port. It's working partially, and is something done in the sandstorm app routing.

Thank you.
