### ISSUE TITLE
Sandstorm Apps page with demo requires confusing login

### ISSUE THREAD

**Issue by TiagoFreitas87** [sandstorm-io/sandstorm#292]
If I go to https://sandstorm.io/apps , choose Demo then try to install an app, I get 

Failed to install app!
You must sign in to install packages.

I think this "Configure Demo Login" should be automatic for now, it's an unnecessary step and probably confusing because trying the other forms of login gives another error:

Failed to install app!
Sorry, Sandstorm is in closed alpha.  You must receive an alpha key before you can install packages.

**Comment by kentonv** [comment]
Hmm, I think we should change sandstorm.io/apps such that if you don't specify a host in the URL, instead of having you specify one at the top, we turn all of the "install" buttons into appdemo ("try it on sandstorm") buttons.

We should probably _also_ make it the case that if somehow you come across a link to `/apps?host=https://demo.sandstorm.io` without having gone through the demo, we do something reasonable, since I've seen some people post such links. I guess the `/install` links should, if the user isn't logged in but demo mode is enabled and the package in question exists, redirect to `/appdemo`.

**Comment by jparyani** [comment]
https://github.com/sandstorm-io/sandstorm-website/pull/53 fixes this for most cases. We still need to change the shell to handle the case where a user is not logged in but navigates to an install route. This could happen if they were linked to https://sandstorm.io/apps/?host=https://demo.sandstorm.io but never made a demo account.
