### ISSUE TITLE
spk pack: no file found to satisfy requirement

### ISSUE THREAD

**Issue by JamborJan** [sandstorm-io/sandstorm#293]
I'm currently finishing the sandstorm port of paperwork (https://github.com/twostairs/paperwork).

While ```spk dev``` runs as expected, generates a proper ```sandstorm-files.list``` and let's me use the app in dev mode, ```spk pack``` bothers me with a ton of files it claims it doesn't find. For example:

```
No file found to satisfy requirement: etc/php5/cli/conf.d/20-pdo_sqlite.ini
```

I have tested with some files, copying would help. I could now copy the files from my OS to a folder in the app but that shouldn't be the solution of the problem, or am I wrong?

I used @jparyani way of porting apps via Docker.

**Comment by kentonv** [comment]
It's possible that this is a file that existed a previous time that you ran `spk dev`, but no longer exists now. If that's the case -- meaning presumably you don't actually need this file -- then you can delete it from `sandstorm-files.list` and try again. If you find that there are a lot of such files, you may want to delete `sandstorm-files.list` altogether and then re-run `spk dev` to regenerate it (make sure to test all the features of your app so that all needed files are detected).

**Comment by paulproteus** [comment]
Hi JJ!

Some notes here:

* Try, if possible, to provide the full list of files that aren't being
found. That list of files can provide a pattern. I'm pretty familiar with
Debian/Ubuntu packaging tools so can usually quickly help debug given that
information.

* I agree with Kenton that the files probably existed last time you ran
"spk dev" but don't exist now, and can probably be removed from the files
list.

Thanks for working on this! I hope it's been informational, and I also hope
that you can give feedback on this (and future) packaging tools so that we
can make them truly easy to use.

**Comment by kentonv** [comment]
> Try, if possible, to provide the full list of files that aren't being found.

Sadly, `spk pack` currently doesn't provide this, as it throws an exception on the first file it can't find. But that's probably a bug we should fix...

**Comment by JamborJan** [comment]
Okay there are two things I didn't take that much care about:
- the ```sandstorm-files.list```grows and grows with every attempt you have trying to build your app. So I had a 3.4 MB big file instead of 4KB which it has now after creating it new
- the "Docker process" to build an app uses the exported Docker environment. You should delete this folder before running a new Docker build process otherwise you have kind of recursively /opt/app/dockerenv/opt/app/dockerenv/... in your app.

Building the app worked now. I'm not quite sure but maybe it would be good that ```spk dev``` would always create the file list from scratch. 

Thanks
JJ

**Comment by kentonv** [comment]
> So I had a 3.4 MB big file instead of 4KB which it has now after creating it new

Hmm, that's weirdly large. `spk dev` will not add duplicates to the list, so it sounds like you must have files that are changing names with every run -- maybe because you are precompiling assets that are named by their hash or some such?

> I'm not quite sure but maybe it would be good that spk dev would always create the file list from scratch.

That's something we're considering, but it has the down side that you have to be careful to test your entire app in the run immediately before `spk pack`, otherwise some files might not get included because they weren't used in that last run. For the moment, it seems better to have the developer to explicitly delete the list when that's what they actually want. This could be better-documented, though.

Hmm, maybe it would make sense for `spk dev` to check if `sandstorm-files.list` contains non-existent files and then ask the developer if they want to reset before running.

**Comment by JamborJan** [comment]
> so it sounds like you must have files that are changing names with every run -- maybe because you are precompiling assets that are named by their hash or some such?
Maybe it helps when you can compare the files:
- old big version: https://drive.google.com/file/d/0Bxqyo6yHmzb3dm1sbmdJblllVVk/view?usp=sharing
- new small version: https://drive.google.com/file/d/0Bxqyo6yHmzb3SDVJMEhVakNkNTQ/view?usp=sharing

One reason for a the size of the file was the dockerenv folder.

I got the point why it is not a good idea to create always a new list. So from what I have seen so far a message like "Your list contains non existing files, should these all be ignored?" would make sense.
