### ISSUE TITLE
Couldn't send UDP sandcats ping { [Error: send EPERM sandcats.io:8080]

### ISSUE THREAD

**Issue by MatheusRV** [sandstorm-io/sandstorm#2931]
Centos 7 with CWP

> # meteor --version
> -bash: meteor: command not found
> # npm -v
> 4.2.0
> # node -v
> v7.9.0
> # sandstorm status --version
> Sandstorm version 207

**/opt/sandstorm/var/log/sandstorm.log**
```
** Shutting down due to signal
** Restarting
** Starting back-end...
** Starting MongoDB...
note: noprealloc may hurt performance in many applications
about to fork child process, waiting until server is ready for connections.
forked process: 884
child process started successfully, parent exiting
** Back-end and Mongo started; now starting front-end...
Migrations already applied: 33/33
Couldn't send UDP sandcats ping { [Error: send EPERM sandcats.io:8080]
  code: 'EPERM',
  errno: 'EPERM',
  syscall: 'send',
  address: 'sandcats.io',
  port: 8080 }
```

My sandcats.io does not open, firewall 8080, 6080 6081 UDP and TCP ports are open.

**Comment by zenhack** [comment]
Could you add a bit of context? Where does this error show up, and under what circumstances?

**Comment by MatheusRV** [comment]
@zenhack srry updated..

**Comment by kentonv** [comment]
Hi @MatheusRV,

Sandcats sends pings to sandcats.io regularly in order to keep your IP address updated. It sends these on UDP port 8080. The EPERM error suggests that it was blocked by Linux firewall rules. Note that this is *outgoing*, not incoming, so may require a separate firewall rule from incoming ports.

It sounds like your problem may have resolved itself, so I will close this issue.
