### ISSUE TITLE
OAuth with Github/Google seems to fail

### ISSUE THREAD

**Issue by eubyte** [sandstorm-io/sandstorm#2949]
We tried to install Sandstorm under numerous settings (https or http, behind a proxy or directly, DNS or straight IP, etc.) and in each and every instance we were unable to complete the last step of the installation process where an admin account has to be created via either Github or Google.

Whenever we try to sign up with Github/Google we end up being redirected back to the 'Log in to create your admin account' screen... The system log shows the following:

{"line":"101","file":"oauth.js","message":"Unable to base64 decode state from OAuth query: undefined","time":{"$date":1497071345991},"level":"warn"}
{"line":"101","file":"oauth.js","message":"Unable to base64 decode state from OAuth query: undefined","time":{"$date":1497071345996},"level":"warn"}
{"line":"431","file":"oauth.js","message":"Error in OAuth Server: Failed to complete OAuth handshake with GitHub. bad_verification_code","time":{"$date":1497071345999},"level":"warn"}

Any help is very much appreciated!

**Comment by kentonv** [comment]
Hi @eubyte,

A common cause for this redirect behavior is if you've enabled the option "Disallow collaboration with users outside the organization" under "Organization settings", and the account you're trying to log in as is not in the organization. This setting prohibits anyone outside the organization from logging in at all. Currently there is no way to define Github users as part of the organization, so this in particular would block all Github logins. It would also block Google logins unless they were under the Google Apps domain you specified in the org settings. Unfortunately, due to a bug, no error message is shown to indicate the problem.

I recommend disabling the "Disallow collaboration with users outside the organization" setting and trying again.

Does that solve the problem?

**Comment by eubyte** [comment]
It solved it right away -- thank you so much!
