### ISSUE TITLE
Error: Error: remote exception: Peer disconnected.

### ISSUE THREAD

**Issue by hiromipaw** [sandstorm-io/sandstorm#2957]
Hi, 
all our pads are having the following error:

```
Error: Error: remote exception: Peer disconnected.
    at Error (native)
    at Error (native)
C++ location:(javascript):??
type: disconnected
```

Could you please advise? 

Thanks again.

**Comment by zenhack** [comment]
What shows up in the grain's console?

**Comment by isislovecruft** [comment]
It seems like there's not any way to get stuff out of the console, at least not through the UI

![snapshot228](https://user-images.githubusercontent.com/907241/28134213-d00f71e6-6731-11e7-9220-23458b4deb0b.png)

**Comment by zenhack** [comment]
I think you can only view the console for grains that you own; If you create a grain there should be an icon on the top bar next to the trash and key icons, of a monitor that says "debug log" on hover.

**Comment by kattor** [comment]
Here's the log from one of the grains. This is what I see after I go to our sandstorm instance and click a grain that I created.


Debug log: <grain title>

...e: userns
*** Uncaught exception ***
sandstorm/supervisor.c++:1330: unimplemented: netlink(ip link add dummy0 type dummy): Operation not supported
stack: 0x601885 0x5f8d52 0x5f870e 0x6099b9 0x6099aa 0x5017c3
** SANDSTORM SUPERVISOR: App exited with status code: 1
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
*** Uncaught exception ***
sandstorm/supervisor.c++:1330: unimplemented: netlink(ip link add dummy0 type dummy): Operation not supported
stack: 0x601885 0x5f8d52 0x5f870e 0x6099b9 0x6099aa 0x5017c3
** SANDSTORM SUPERVISOR: App exited with status code: 1
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
*** Uncaught exception ***
sandstorm/supervisor.c++:1330: unimplemented: netlink(ip link add dummy0 type dummy): Operation not supported
stack: 0x601885 0x5f8d52 0x5f870e 0x6099b9 0x6099aa 0x5017c3
** SANDSTORM SUPERVISOR: App exited with status code: 1
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
*** Uncaught exception ***
sandstorm/supervisor.c++:1330: unimplemented: netlink(ip link add dummy0 type dummy): Operation not supported
stack: 0x601885 0x5f8d52 0x5f870e 0x6099b9 0x6099aa 0x5017c3
** SANDSTORM SUPERVISOR: App exited with status code: 1
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
*** Uncaught exception ***
sandstorm/supervisor.c++:1330: unimplemented: netlink(ip link add dummy0 type dummy): Operation not supported
stack: 0x601885 0x5f8d52 0x5f870e 0x6099b9 0x6099aa 0x5017c3
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
*** Uncaught exception ***
sandstorm/supervisor.c++:1330: unimplemented: netlink(ip link add dummy0 type dummy): Operation not supported
stack: 0x601885 0x5f8d52 0x5f870e 0x6099b9 0x6099aa 0x5017c3
** SANDSTORM SUPERVISOR: App exited with status code: 1
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
*** Uncaught exception ***
sandstorm/supervisor.c++:1330: unimplemented: netlink(ip link add dummy0 type dummy): Operation not supported
stack: 0x601885 0x5f8d52 0x5f870e 0x6099b9 0x6099aa 0x5017c3
** SANDSTORM SUPERVISOR: App exited with status code: 1
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
*** Uncaught exception ***
sandstorm/supervisor.c++:1330: unimplemented: netlink(ip link add dummy0 type dummy): Operation not supported
stack: 0x601885 0x5f8d52 0x5f870e 0x6099b9 0x6099aa 0x5017c3
** SANDSTORM SUPERVISOR: App exited with status code: 1
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
*** Uncaught exception ***
sandstorm/supervisor.c++:1330: unimplemented: netlink(ip link add dummy0 type dummy): Operation not supported
stack: 0x601885 0x5f8d52 0x5f870e 0x6099b9 0x6099aa 0x5017c3
** SANDSTORM SUPERVISOR: App exited with status code: 1
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
*** Uncaught exception ***
sandstorm/supervisor.c++:1330: unimplemented: netlink(ip link add dummy0 type dummy): Operation not supported
stack: 0x601885 0x5f8d52 0x5f870e 0x6099b9 0x6099aa 0x5017c3
** SANDSTORM SUPERVISOR: App exited with status code: 1
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
*** Uncaught exception ***
sandstorm/supervisor.c++:1330: unimplemented: netlink(ip link add dummy0 type dummy): Operation not supported
stack: 0x601885 0x5f8d52 0x5f870e 0x6099b9 0x6099aa 0x5017c3
** SANDSTORM SUPERVISOR: App exited with status code: 1
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
*** Uncaught exception ***
sandstorm/supervisor.c++:1330: unimplemented: netlink(ip link add dummy0 type dummy): Operation not supported
stack: 0x601885 0x5f8d52 0x5f870e 0x6099b9 0x6099aa 0x5017c3
** SANDSTORM SUPERVISOR: App exited with status code: 1
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
*** Uncaught exception ***
sandstorm/supervisor.c++:1330: unimplemented: netlink(ip link add dummy0 type dummy): Operation not supported
stack: 0x601885 0x5f8d52 0x5f870e 0x6099b9 0x6099aa 0x5017c3
** SANDSTORM SUPERVISOR: App exited with status code: 1
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
*** Uncaught exception ***
sandstorm/supervisor.c++:1330: unimplemented: netlink(ip link add dummy0 type dummy): Operation not supported
stack: 0x601885 0x5f8d52 0x5f870e 0x6099b9 0x6099aa 0x5017c3
** SANDSTORM SUPERVISOR: App exited with status code: 1
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
*** Uncaught exception ***
sandstorm/supervisor.c++:1330: unimplemented: netlink(ip link add dummy0 type dummy): Operation not supported
stack: 0x601885 0x5f8d52 0x5f870e 0x6099b9 0x6099aa 0x5017c3
** SANDSTORM SUPERVISOR: App exited with status code: 1
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
*** Uncaught exception ***
sandstorm/supervisor.c++:1330: unimplemented: netlink(ip link add dummy0 type dummy): Operation not supported
stack: 0x601885 0x5f8d52 0x5f870e 0x6099b9 0x6099aa 0x5017c3
** SANDSTORM SUPERVISOR: App exited with status code: 1
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
*** Uncaught exception ***
sandstorm/supervisor.c++:1330: unimplemented: netlink(ip link add dummy0 type dummy): Operation not supported
stack: 0x601885 0x5f8d52 0x5f870e 0x6099b9 0x6099aa 0x5017c3
** SANDSTORM SUPERVISOR: App exited with status code: 1
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
*** Uncaught exception ***
sandstorm/supervisor.c++:1330: unimplemented: netlink(ip link add dummy0 type dummy): Operation not supported
stack: 0x601885 0x5f8d52 0x5f870e 0x6099b9 0x6099aa 0x5017c3
** SANDSTORM SUPERVISOR: App exited with status code: 1
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
*** Uncaught exception ***
sandstorm/supervisor.c++:1330: unimplemented: netlink(ip link add dummy0 type dummy): Operation not supported
stack: 0x601885 0x5f8d52 0x5f870e 0x6099b9 0x6099aa 0x5017c3
** SANDSTORM SUPERVISOR: App exited with status code: 1
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
*** Uncaught exception ***
sandstorm/supervisor.c++:1330: unimplemented: netlink(ip link add dummy0 type dummy): Operation not supported
stack: 0x601885 0x5f8d52 0x5f870e 0x6099b9 0x6099aa 0x5017c3
** SANDSTORM SUPERVISOR: App exited with status code: 1
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
*** Uncaught exception ***
sandstorm/supervisor.c++:1330: unimplemented: netlink(ip link add dummy0 type dummy): Operation not supported
stack: 0x601885 0x5f8d52 0x5f870e 0x6099b9 0x6099aa 0x5017c3
** SANDSTORM SUPERVISOR: App exited with status code: 1
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
*** Uncaught exception ***
sandstorm/supervisor.c++:1330: unimplemented: netlink(ip link add dummy0 type dummy): Operation not supported
stack: 0x601885 0x5f8d52 0x5f870e 0x6099b9 0x6099aa 0x5017c3
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
*** Uncaught exception ***
sandstorm/supervisor.c++:1330: unimplemented: netlink(ip link add dummy0 type dummy): Operation not supported
stack: 0x601885 0x5f8d52 0x5f870e 0x6099b9 0x6099aa 0x5017c3
** SANDSTORM SUPERVISOR: App exited with status code: 1
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
*** Uncaught exception ***
sandstorm/supervisor.c++:1330: unimplemented: netlink(ip link add dummy0 type dummy): Operation not supported
stack: 0x601885 0x5f8d52 0x5f870e 0x6099b9 0x6099aa 0x5017c3
** SANDSTORM SUPERVISOR: App exited with status code: 1
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
*** Uncaught exception ***
sandstorm/supervisor.c++:1330: unimplemented: netlink(ip link add dummy0 type dummy): Operation not supported
stack: 0x601885 0x5f8d52 0x5f870e 0x6099b9 0x6099aa 0x5017c3
** SANDSTORM SUPERVISOR: App exited with status code: 1
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
*** Uncaught exception ***
sandstorm/supervisor.c++:1330: unimplemented: netlink(ip link add dummy0 type dummy): Operation not supported
stack: 0x601885 0x5f8d52 0x5f870e 0x6099b9 0x6099aa 0x5017c3
** SANDSTORM SUPERVISOR: App exited with status code: 1
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
*** Uncaught exception ***
sandstorm/supervisor.c++:1330: unimplemented: netlink(ip link add dummy0 type dummy): Operation not supported
stack: 0x601885 0x5f8d52 0x5f870e 0x6099b9 0x6099aa 0x5017c3
*** lost connection to grain (probably because it shut down) ***

**Comment by zenhack** [comment]
Interesting. Could you tell us a bit more about the system you're running sandstorm on?

* Distro/version
* Kernel version (output of `uname -r`)
* If possible, kernel config; on many systems can be obtained via `zcat /proc/config.gz`.
* How you set up sandstorm
* Anything else you think might be relevant

Had it been working before, or did this start failing at some point? If the latter, had anything about the setup changed recently?

**Comment by hiromipaw** [comment]
Hi @zenhack 
We have had sandstorm installed for a long time now.

We are running Debian 8.8. 

```
$uname -r 
3.16.0-4-amd64
```

Kernel config: https://gist.github.com/hiromipaw/41b0f6cf8bd544c394ff29c6378fc210

Please let me know if is there something else you could find useful.

**Comment by kentonv** [comment]
Hi all,

The errors indicate that a syscall made by the Sandstorm supervisor to set up the network namespace is failing. Sandstorm has not changed lately so it seems like your system must have changed in some way. Did you recently set up selinux policies or something like that? They could be blocking functionality Sandstorm needs. If you haven't changed anything, then my guess is the distro changed something, but it's going to be hard to figure out what, exactly.

The functionality that is failing actually turns out to be unused, so perhaps I can simply delete it. I'll try to do that today and push a release.

**Comment by kentonv** [comment]
While deleting this code, I noticed that the code only executes if the `iptables` kernel module is loaded. So it could be that the code never worked on your machine (I still don't know why that would be), but this only came up recently because the `iptables` started being loaded, where it wasn't before.

In any case, I'm about to push a release deleting this.

**Comment by kattor** [comment]
Thank you @kentonv! We'll let you know how it goes.

**Comment by hiromipaw** [comment]
@kentonv it fixed it thanks. :100:
