### ISSUE TITLE
New build >0.67

### ISSUE THREAD

**Issue by JamborJan** [sandstorm-io/sandstorm#297]
I habe seen that it has been a long time since 0.67 was build. When will there be a new build? I'm specifically waiting for https://github.com/sandstorm-io/sandstorm/pull/247 to test apps also on iOS.

I have auto update activated.

Thanks.

**Comment by paulproteus** [comment]
​In my opinion, we should do builds automatically or at least
almost-automatically.

Unless we have a reason not to, we should follow the Chrome team's plans
for how long between builds.

Kenton, +1 -1 etc.?

Note that I'm OK with being responsible for being the person to do builds
and push them out to the dev channel.

**Comment by kentonv** [comment]
The problem here is just that I tend to forget to push releases and no one reminds me. :) Or I start the build but forget to finish it. The act of pushing release doesn't take any significant amount of time on my part, I just have to remember to do it and follow through.

(I was going to do a release today, but then I wanted to wait for Debian Testing to get yesterday's OpenSSL update (even though none of the patches are high-importance in Debian's case).)

I've added a calendar event to push a release every Monday at 11AM.

I believe Chrome pushes a new major version every six weeks, which is clearly way to slow for us. I'm not sure how often they push bugfixes.

**Comment by kentonv** [comment]
New build pushed. Sorry for the delay.
