### ISSUE TITLE
how to integrate installed app with sandstorm?

### ISSUE THREAD

**Issue by vhp1360** [sandstorm-io/sandstorm#2977]
Hi guys,
we installed wekan and rocket.chat before installing sandstorm.
could you please let me know, is there any way to add these apps to snadstorm without fresh installing them?

**Comment by kentonv** [comment]
Hi Hossein,

Unfortunately, there is not. Someone would need to write migration tools for this, specific to each app. I'm not aware of any such tools having been written for Wekan or Rocket.Chat. Sorry.

I'm closing this issue since this isn't actionable for Sandstorm itself, but it might make sense to raise issues on the individual apps asking for migration tools.

**Comment by vhp1360** [comment]
OK, many thanks Kenton for the quick reply.
