### ISSUE TITLE
This server seems to have its WILDCARD_HOST misconfigured

### ISSUE THREAD

**Issue by app-4-all** [sandstorm-io/sandstorm#2980]
I finally succeded to install sandstorm and login on it. But now when i install an app like "wekan" for example i can't use it. The loading is infinite. And when i go to the admin panel i have this error "This server seems to have its WILDCARD_HOST misconfigured. Until you fix it, you will not be able to use any apps."
Can you help me again please ? :)

![sans titre 8](https://user-images.githubusercontent.com/5772618/30239591-a0f06b10-9560-11e7-83ec-ca5bb0717509.png)

![sans titre 10](https://user-images.githubusercontent.com/5772618/30239592-a0f32d3c-9560-11e7-8c97-3bb26ebbfb94.png)

**Comment by kentonv** [comment]
Hi Willy,

You need to configure your DNS so that `*.example.fr` is mapped as a wildcard DNS entry pointing to your server. Most DNS servers/services support entering `*` as the hostname in order to create a wildcard.

Here's documentation on wildcard hosts:

https://docs.sandstorm.io/en/latest/administering/wildcard/

**Comment by ocdtrekkie** [comment]
Closing for lack of further response on troubleshooting work here.
