### ISSUE TITLE
Wild Card DNS issue

### ISSUE THREAD

**Issue by MartiniHenry1988** [sandstorm-io/sandstorm#3020]
I have a staging server based on Ubuntu 16. (Example address: **staging.chatapp.com**)

I also have a PHP based website running with apache2 on **staging.chatapp.com**

I have installed Sandstorm and selected the option: **A typical install, to use Sandstorm**

Here is my Sandstorm config file:

```
SERVER_USER=sandstorm
PORT=6080
MONGO_PORT=6081
BIND_IP=0.0.0.0
BASE_URL=http://staging.chatapp.com:6080
WILDCARD_HOST=*.staging.chatapp.com:6080
```

The issue is that when I visit the address with admin-token, it keeps loading, it does nothing and it doesnot work. Why is this so? Is this due to apache2?

**Comment by Michael-S** [comment]
Hello MartiniHenry1988 - I'm not a Sandstorm developer, just a user with my own hosted instance on Ubuntu 16.  I apologize if you have done all of these things or know them already, but here are my suggestions or notes:

1.  I think it's unlikely apache2 is the problem, unless you also configured it to use port 6080.
2.  If your server is hosted by some company like Linode or DigitalOcean, some of the hosting providers use custom kernels that don't work with Sandstorm.   I think Linode and DigitalOcean are actually fine, but we've had other people open issues or send email to the mailing list about provider problems.  The 'uname -a' command will help you check your kernel version, or you can just comment here with the provider name and we can try to look it up.
3.  Is it possible firewall settings are interfering?  As you probably know the default firewall tool on Ubuntu is 'ufw', so you can do 'sudo ufw status' to see the settings.  If ufw is disabled then probably everything is open (unless you're using another firewall), otherwise make sure 6080 is on the ALLOW list.  If you're going through a router or other firewall, does it have port 6080 open and the right configuration to forward traffic to the actual Ubuntu server?  If it's running on a virtual machine on one of your own servers, do you have the right network configuration for port 6080 traffic received by the host to be forwarded to 6080 on the hosted virtual machine?
4.  You can look for contents in /opt/sandstorm/var/log/sandstorm.log to see if it has any useful error messages.

Good luck.

**Comment by ocdtrekkie** [comment]
I'm going to close this because there was no further response and the details above aren't enough to identify a specific problem with Sandstorm.
