### ISSUE TITLE
Verify Latest Version

### ISSUE THREAD

**Issue by dmkjr** [sandstorm-io/sandstorm#3024]
I'm trying to find information to either update Sandstorm or at least view what version number we are currently on versus the latest.  I have an environment setup that is about 6 months old, but I don't see any update(s).  Although, I see it may have been setup for the dev_channel updates.  

Any help would be appreciated.

**Comment by kentonv** [comment]
Hi @dmkjr,

You can see the current version by visiting `/about` on your server. As of today, the latest version is 0.224.

**Comment by ocdtrekkie** [comment]
https://github.com/sandstorm-io/sandstorm/releases shows the latest Sandstorm release (though auto-update should only get you to 0.257 today) and as Kenton mentioned, on /about on your server the current version and changelog should be visible.

Closing because I don't think there's a place we need to improve here, and the original requestor never specified if there were any updating issues that needed to be addressed.
