### ISSUE TITLE
0.226 appears to have broken my TTRSS client

### ISSUE THREAD

**Issue by ocdtrekkie** [sandstorm-io/sandstorm#3050]
I'm on Oasis, so the Experimental Gateway should've already been enabled previously. The Windows client app no longer works on either my phone or my desktop. I was using it yesterday.

**Comment by kentonv** [comment]
API sessions weren't actually handled by the gateway before this release -- or rather, they were, but they were only trivially proxied through to the shell which ran the old proxy code. This release fully handles them the new way. I did a lot of testing with git and Gogs but forgot to test TTRSS. It turns out TTRSS is very old and requires a compatibility fallback that I failed to implement correctly. Embarrassingly I had written a TODO(now) to test it but forgot. (Uh, apparently my release script isn't correctly checking for TODO(now)s the way I thought, doh.)

Hotfix is on the way.
