### ISSUE TITLE
after v0.231 update, system keeps disconnecting for a few seconds 

### ISSUE THREAD

**Issue by germakoci** [sandstorm-io/sandstorm#3063]
we run our own instance (and we use a 2FA with SAML integration)

since the last update [v0.231] the system is going offline for a few seconds and back online again, and it's doing this every minute; (perhaps because of that, dokuwiki is giving 502 bad gateway while browsing wiki pages)

does anybody else experience this ?

**Comment by kentonv** [comment]
@germakoci Are there any interesting errors in `/opt/sandstorm/var/log/sandstorm.log`?

**Comment by kentonv** [comment]
I've just pushed v0.232 which fixes a couple of segfault issues. Most notably, it turns out that the version of Node which shipped in v0.231 has a bad interaction with Meteor that causes random segfaults! (Yikes.) v0.232 has a patched version. I also fixed one or two gateway-related crashes.

Let me know if things are improved, otherwise please send me your log file for further investigation.

**Comment by kentonv** [comment]
Hey @germakoci, I just pushed version 0.233 which fixes another crash problem which I suspect may have been the one affecting you. Please have your admins apply the update if you're still having problems.

**Comment by ocdtrekkie** [comment]
Closing because there was no further followup/response. And fixes were pushed which hopefully alleviated the issue successfully.
