### ISSUE TITLE
Installer tried to report E_CURL_MISSING using curl

### ISSUE THREAD

**Issue by jimcheetham** [sandstorm-io/sandstorm#3066]
I have a Debian 9 VM, that doesn't seem to come with curl by default.

The install script tests for curl, and if it isn't found, tries to report E_CURL_MISSING ... but tries to use curl to do so.

```
jim@ed:~$ bash install-sandstorm.bash 
*** INSTALLATION FAILED ***

Please install curl(1). Sandstorm uses it to download updates.

Hmm, installation failed. Would it be OK to send an anonymous error report to the sandstorm.io team so we know something is wrong?
It would only contain this error code: E_CURL_MISSING [yes] 
Sending problem report...
...install-sandstorm.bash: line 143: curl: command not found
Submitting error report resulted in strange HTTP status: 

You can report bugs at: http://github.com/sandstorm-io/sandstorm
jim@ed:~$ 
```

Seeing as you require bash, you will probably have access to /dev/tcp/ pseudodevices, and therefore might be able to make this error report without using curl (see https://falzon.me/en/post/burl-a-pure-bash-http-client/ for an example)

**Comment by ocdtrekkie** [comment]
This bug report is kinda funny, IMHO, but I am not sure how critically we need the error report in the case of curl not being installed. Any user experiencing this should get the pretty good error message requesting that you install curl, seen in your log.

The only loss by not fixing this is presumably that Sandstorm.io is not successfully collecting the percentage of install failures caused by the lack of curl. I have my doubts that anyone is currently looking at those anonymous error reports right now.

**Comment by zenhack** [comment]
Yeah, especially given that the instructions tell the user to fetch the install script *using curl*, I'm inclined to think this isn't worth bothering to fix.

**Comment by jimcheetham** [comment]
It wasn't so much that you're only using curl in the install script; but that your install script wants to report the problem, and tries to use curl to send the report. So yes the report is kinda funny :-) and so is the error condition ...

**Comment by zenhack** [comment]
You know what, I'm just going to fix this; if the error was because of a missing curl we should just not suggest reporting in. Stay tuned for a pr.
