### ISSUE TITLE
Language detection has lost effect

### ISSUE THREAD

**Issue by urakagi** [sandstorm-io/sandstorm#3081]
I'm not sure when this starts to happen, but my Sandstorm console goes back to English now.
I slightly checked `tap18n` related code, but it don't get any hint.
Has someone touched language or localization related code?

**Comment by ocdtrekkie** [comment]
AFAIK, there's been no changes to i18n. It's possible something in the Meteor upgrade messed with it, perhaps?

**Comment by urakagi** [comment]
@ocdtrekkie I notice this phrase in 235 update: "Due to Meteor 1.7 update, Sandstorm shell now serves different JavaScript to modern vs. "legacy" browsers, with the modern JS being leaner and faster."
Is it possible that modern browser will skip `shell-client.js` or something?

**Comment by ocdtrekkie** [comment]
@urakagi Nothing that drastic, Sandstorm still only has one shell-client.js, but you can maybe read a bit about Meteor 1.7 here: https://blog.meteor.com/meteor-1-7-and-the-evergreen-dream-a8c1270b0901

**Comment by kentonv** [comment]
This appears to be a side-effect of this error on the console:

```
Uncaught TypeError: Meteor.autorun is not a function
    at e614ff64b6b7e6dea1902bb9363cc72fd8cd4444.js?meteor_js_resource=true:189
    at a (e614ff64b6b7e6dea1902bb9363cc72fd8cd4444.js?meteor_js_resource=true:1)
    at HTMLDocument.u (e614ff64b6b7e6dea1902bb9363cc72fd8cd4444.js?meteor_js_resource=true:1)
```

Apparently, Meteor went and removed the Meteor.autorun() function, because it's called Tracker.autorun() these days, and Meteor loves to introduce these little breaking changes for no good reason. The exception is in notification-client.js, but because of it, the startup code in shell-client.js never actually runs. But enough startup has happened that everything "seems to work" and all the tests pass. Sigh.

**Comment by kentonv** [comment]
Pushed a release fixing this.

**Comment by urakagi** [comment]
Fix confirmed. Thank you!
Hard deprecating something without good reasons is really annoying :(
