### ISSUE TITLE
Cannot install sandstorm -> E_PKG_STALE

### ISSUE THREAD

**Issue by madd4mon** [sandstorm-io/sandstorm#3126]
I'm trying to install sandstorm via curl on one of my VPSs. Installation fails on every server I test it on. I'm only using default settings. Error message tells me that the "downloaded package seems to be more than a month old". It also gives me the error code "E_PKG_STALE". 

What do I do wrong and what can I do to fix this?

**Comment by ocdtrekkie** [comment]
This happens if the current Sandstorm release is more than a month old, which occasionally happens when @kentonv is busy being awesome elsewhere.

In the immediate term, you could modify the install.sh script yourself to extend the duration of this check, example being this PR: https://github.com/sandstorm-io/sandstorm/pull/3014/files

**Comment by madd4mon** [comment]
Thanks!
