### ISSUE TITLE
 What function to unpack spk file in sandstorm ui?

### ISSUE THREAD

**Issue by vinacart** [sandstorm-io/sandstorm#3139]
I will custom sandstorm code & need to find unpack spk function. My purpose is: copy some file that no ship with apk file by default. So i can add my code after unpack job complete, to copy my file in /opt/sandstorm/var/sandstorm/apps//

Thanks a lot.

**Comment by admicro** [comment]
please help?

**Comment by ocdtrekkie** [comment]
All of Sandstorm's apps are open source: Why not build a forked version of the app with your APK added? Trying to inject changes to the app via Sandstorm code is probably much more complicated and breakable.

**Comment by admicro** [comment]
thank for your response.
what apk file? i build much of spk files &  using sandstorm platform to run demo app with my spk (it's ok). but in my other app, i will create a task to unpack spk file so i don't want unpack this spk from sandstorm server.

show me snippet code from sandstorm code (meteor) or any cli tool to do this. thank a lot.
i found something but not sure:

+ https://github.com/sandstorm-io/meteor-spk  -> can do this?
+ sandstorm: programs/server/app/app.js
`
doDownloadTo(out) {
  ..
  request.on("end", this.wrapCallback(() => {
        out.done();

        if (hasher.digest("hex").slice(0, 32) !== this.packageId) {
          throw new Error("Package hash did not match.");
        }

        done = true;
        delete this.downloadRequest;
        this.updateProgress("unpack");
        out.saveAs(this.packageId).then(this.wrapCallback(info => {
          this.appId = info.appId;
          this.authorPgpKeyFingerprint = info.authorPgpKeyFingerprint;
          this.done(info.manifest);
        }), this.wrapCallback(err => {
          throw err;
        }));
      }));
   ...
}
`
but i wonder how to use this independent without run sandstorm server.

many thank to you!

**Comment by ocdtrekkie** [comment]
You mentioned an apk file, but I guess that was a typo.

Unpacking spk files is somewhat non-trivial since it uses Cap'n Proto as it's "format". I looked into doing this once, and it was more complicated than it was worth for me.

But my question is, why not build the spk files with whatever additional contents you need in the first place? Why are you trying to inject files into an already built spk file?

**Comment by admicro** [comment]
Oh, sory. because everything i pack inside spk file. So i just use same spk & unpack spk into other server to use my additional files.
if can't unpack spk without sandstorm, so any way to send socket to sandstorm server to download & unpack spk file from url (eg: https://mydomain/themes/theme-1.spk) that just inherit exist meteor code?
So in this way, i can `cd` & `copy` to my other server.

many thanks!

**Comment by zenhack** [comment]
The spk command line tool includes pack & unpack subcommands:

```
$ spk unpack --help

Usage: spk unpack [<option>...] <spkfile> [<outdir>]

Check that <spkfile>'s signature is valid.  If so, unpack it to <outdir> and
print the app ID.  If <outdir> is not specified, it will be chosen by removing
the suffix ".spk" from the input file name.

Options:
    --verbose
        Log informational messages to stderr; useful for debugging.
    --version
        Print version information and exit.
    --help
        Display this help text and exit.
```

```
$ spk pack --help
Usage: spk pack [<option>...] <output>

Package the app as an spk, writing it to <output>.

Options:
    -I<path>, --import-path=<path>
        Additionally search for Cap'n Proto schemas in <path>. (This allows your
        package definition file to import files from that directory -- this is
        rarely useful.)
    -k<path>, --keyring=<path>
        Use <path> as the keyring file, rather than $HOME/.sandstorm-keyring.
    -p<def-file>:<name>, --pkg-def=<def-file>:<name>
        Don't read the package definition from ./sandstorm-pkgdef.capnp.
        Instead, read from <def-file>, and expect the constant to be named
        <name>.
    --verbose
        Log informational messages to stderr; useful for debugging.
    --version
        Print version information and exit.
    --help
        Display this help text and exit.
```

The catch is that spks are digitally signed, so if you aren't the
original author, you can't just unpack, tweak stuff and then pack it
back up, since you don't have the signing key. You could re-label it as
a different app, but I agree with Jacob, basically all of the existing
sandstorm apps are open source, so rather than downloading the spk and
then modifying it, it would make more sense to fetch the source code for
the app, make modifications (including to the build system possibly) and
then build it yourself.

Quoting Admicro (2019-05-31 21:25:18)

> So in this way, i can cd & copy to my other server.

I'm not sure, but I'm wondering if we may actually be having a
misunderstanding due to a language barrier: do you really want to
extract the *contents* of the app from the .spk file and change it,
or do you want to extract the .spk file from an existing sandstorm
server, in order to upload it elsewhere?

**Comment by admicro** [comment]
thanks you! i will try it cli

**Comment by admicro** [comment]
SUPPORT DỊCH VỤ
1. Chat & hỏi đáp

Hotline/Zalo/Viber: 0987.342.124 | Facebook: facebook.com/hoangweb24:
https://hoangweb.bitrix24.com/pub/mail/click.php?tag=crm.eyJ1cm4iOiIxMzQ1NS1OMVRHMlYifQ%3D%3D&url=https%3A%2F%2Fwww.facebook.com%2Fhoangweb24&sign=9a0e6fac25be21c8c9b126e3821490efd6868daa1786d8fa6b13110af59adf9e

2. Theo dõi tiến độ công việc

Truy cập hoangweb.bitrix24.com để theo dõi nhiệm vụ và trao đổi kỹ thuật.

ĐỌC HƯỚNG DẪN:
https://hoangweb.bitrix24.com/pub/mail/click.php?tag=crm.eyJ1cm4iOiIxMzQ1NS1OMVRHMlYifQ%3D%3D&url=https%3A%2F%2Fwww.hoangweb.com%2Fcskh&sign=6b1ba4e473a4c103335a7fa3360e53e065303fc3e0ea17122a3519a7387f39f2

hoangweb.com/cskh

Trang chủ:
https://hoangweb.bitrix24.com/pub/mail/click.php?tag=crm.eyJ1cm4iOiIxMzQ1NS1OMVRHMlYifQ%3D%3D&url=https%3A%2F%2Fwww.hoangweb.com&sign=79f8d9b5555bc2bea1534aa1453849b0c23c9c2cf31e9f5455688648e32a1e82

Hướng dẫn thanh toán:
https://hoangweb.bitrix24.com/pub/mail/click.php?tag=crm.eyJ1cm4iOiIxMzQ1NS1OMVRHMlYifQ%3D%3D&url=https%3A%2F%2Fwww.hoangweb.com%2Fthanh-toan&sign=edd5f8de3dcdf921a622daac1e81e744fdd7e2fd87f6a3b469bff8e05eb70550

Trung tâm hỗ trợ:
https://hoangweb.bitrix24.com/pub/mail/click.php?tag=crm.eyJ1cm4iOiIxMzQ1NS1OMVRHMlYifQ%3D%3D&url=https%3A%2F%2Fwww.hoangweb.com%2Fcskh&sign=6b1ba4e473a4c103335a7fa3360e53e065303fc3e0ea17122a3519a7387f39f2

Bạn nhận được thư này bởi bạn đã đăng ký là khách hàng của Hoàng Web.
