### ISSUE TITLE
Serious problem as mongo won't start

### ISSUE THREAD

**Issue by SwapFaceL** [sandstorm-io/sandstorm#3150]
Hi,

I am totally lost :( so today I realized that the certificate of the sandstorm server was not valid anymore. After some tries I found out the problem was the sandcats.io-certificate renewal. 
As I changed a lot of stuff during this process of bug finding, I deleted the whole folder and copied the backup from yesterday night (whole directory /opt/sandstorm).

However, I am not able to start this backup. It fails with the log message:
"sandstorm/run-bundle.c++:2139: failed: **mongod failed to start. Initial exit code: ; status = 1; bailing out now."
Unfortunately the mongo.log is not created (so no log entry from mongo is produced).

I checked the file/directory permissions and everything seems fine for me.
Any idea how I can get back my grain data? I can see that all grains are in the backup but I am not able to access them :(( really need help!

Thanks a lot!

**Comment by kentonv** [comment]
Sorry about the certificate issue -- there was a Globalsign outage earlier this week, and apparently the Sandcats server was left in a confused state after Globalsign came back up. I rebooted the Sandcats server and now everything seems to be working.

As for your Mongo issue, is that really the only thing you see in the Sandstorm log? It's weird for Mongo to produce no log of its own and also not show anything in the Sandstorm log.

One reason Mongo sometimes doesn't want to start is because there is not enough disk space available. I think it wants there to be half a gigabyte available before it will evern start up. But I think it would still produce a log in that case.

Another thing you can try is installing a fresh Sandstorm server, and then replace all of /opt/sandstorm/var with your backup copy. That would rule out any issue where the MongoDB binary is broken, since you'd be using a fresh copy.

**Comment by SwapFaceL** [comment]
Hi @kentonv thanks for letting me know.

I managed meanwhile to do exactly that and now sandstorm is running at least again, I can see my apps and grains.
However with the new apache-reverse-proxy there still seems to be a problem. Whenever I click on any grain it just gives me a 502 Proxy Error.

1. Added a wildcard domain
2. obtain a valid certficate via certbot
3. Took and adjusted the template from here: https://github.com/sandstorm-io/sandstorm/blob/master/docs/administering/sample-config/apache-virtualhost.conf

Any suggestions where to search for the error?

**Comment by francis-specialeffect** [comment]
I'm having a very similar issue to this at the moment trying to migrate to a newly set up Ubuntu 18.04 server, initially wasn't able to recover my domain but now am since you rebooted it. But I do get an error message

> Some part of HTTPS autoconfiguration failed. Log data available in 
> var/sandcats/https/xxxxxx.sandcats.io/0.response-json

Attempting to then replace /opt/sandstorm with my backup I also get the same error in the sandstorm log and can't reach the site

> "sandstorm/run-bundle.c++:2139: failed: **mongod failed to start. Initial exit code: ; status = 1; bailing out now."

**Comment by SwapFaceL** [comment]
@francis-specialeffect my fault was that I copied the whole /opt/sandstorm folder and unfortunately there seems to be one file in var/sandstorm/socket/ which was not copied and caused the problem plus wrong file permissions check if they are set correctly to root:sandstorm or sandstorm:sandstorm.

**Comment by SwapFaceL** [comment]
I also fixed my issue with the Proxy, was wrong file permissions as well ;) but thanks for fast reply.

**Comment by francis-specialeffect** [comment]
@SwapFaceL Okay thanks, trying that now. Did you just replicate the permissions within the "sandstorm.empty" folder?
