### ISSUE TITLE
Saving more RAM ?

### ISSUE THREAD

**Issue by xet7** [sandstorm-io/sandstorm#3165]
Hi,
I did just read this article:

https://thenewstack.io/a-new-linux-memory-controller-promises-to-save-lots-of-ram/

https://news.ycombinator.com/item?id=21159004

There was this comment:
https://news.ycombinator.com/item?id=21162731
> The optimization is primarily aimed at systems with multiple cgroups, so think Docker-like container platforms.

So I think this also means Sandstorm, and there is some comments that this maybe comes to Linux kernel sometime at 2020.

Some questions:
- Is there possibility that this requires some changes to Sandstorm code itself? For example if something in cgroups changes?
- Or would this just reduce RAM usage just by updating to newest kernel? And no other changes required?

**Comment by kentonv** [comment]
Sandstorm actually does not use cgroups, so it sounds like this doesn't affect Sandstorm.

I had always intended to add cgroups to Sandstorm in order to control CPU and memory usage by apps. But, the cgroups system is hard to use without interfering with the rest of the system. On most modern systems, systemd controls cgroups; for Sandstorm to also create its own cgroups would be hard. (Though maybe the situation has gotten better in the last couple years; I haven't kept up with it.) Between that and the fact that it didn't seem like a pressing need, I never got around to using cgroups in the Sandstorm container engine.

(Sandstorm does use namespaces and seccomp, the other two major kernel features commonly leveraged by containers.)
