### ISSUE TITLE
install.sh hash

### ISSUE THREAD

**Issue by rsynnest** [sandstorm-io/sandstorm#319]
It would be nice if install.sh had a hash documented in the README, just in case people want to verify for extra security.

**Comment by kentonv** [comment]
Hi @rsynnest,

Thanks for the suggestion.

I think the threat model you're considering here is one where our server has been hacked and is serving an evil script.

First, FWIW, we already have something better than a hash of the installer in github: we have the actual script. You can grab `install.sh` from the repo root directory instead of https://install.sandstorm.io; it should be identical.

However, the installer itself in turn downloads the server binary bundle from `install.sandstorm.io`, and the auto-updater does as well. So the threat isn't solved yet.

Eventually we plan to improve this by signing each bundle. Then an attacker would both need to gain control of our server and steal our bundle signing key, which is perhaps harder than only hacking the server, though it's debatable how much (depends on how much effort we want to put into key storage).

Once we've done that, it makes sense to think about locking down the installer itself, to have an end-to-end secure install process bootstrapped from github, which is hopefully auditable.

For the moment, though, I don't think publishing a hash of `install.sh` actually adds any security. Let me know if I missed something.

**Comment by rsynnest** [comment]
You're right, and I like your ideas for eventual end to end security. I'm pretty inexperienced as far as signing/etc, was mainly trying to think of a way to make people feel better about piping to shell, sparked by discussion here: https://news.ycombinator.com/item?id=9318286

**Comment by kentonv** [comment]
To be honest, I think `curl | bash` bothers people more than it should. Security-wise, there's not much difference between it and, say, `npm install somepackage` -- either way, you're giving the package developer permission to run arbitrary code on your machine. Yet, somehow, people don't fear the npm case.

With that said, a legitimate concern with `curl | bash` is that it's a lot easier for a developer to screw up an installer script and make a mess than it is for them to screw up an npm package, since npm itself mostly manages how npm packages are installed. There's not really any way we can prove that our installer script is good except to have people read it, though.
