### ISSUE TITLE
Consider injecting the bridge into grains at runtime, rather than at build time.

### ISSUE THREAD

**Issue by zenhack** [sandstorm-io/sandstorm#3224]
This occurred to me a while back, and it came to mind again when talking to @ocdtrekkie about the fonts stuff in #3223:

We should consider injecting (the current version of) sandstorm-http-bridge into grains at runtime, rather than when building the `.spk`. This has a few advantages:

- We could ship fixes without existing apps needing to update their copy of the bridge.
- Apps would not have to actually include the bridge in their packages, which would make the files a bit smaller.

Thoughts?

**Comment by kentonv** [comment]
This would mean that we need to start being super-strict about not breaking compatibility in the interactions between sandstorm-http-bridge and the app. This layer is rather amorphously-defined, including a combination of HTTP and Cap'n Proto protocols and conventions outside of that. I think it would prove too easy to break old apps by accident, while probably also hindering changes we might want to make to sandstorm-http-bridge in the future. It's true that in general we avoid making backwards-incompatible changes at this layer since we don't want to cause problems when updating apps, but right now we have the ability to decide that some specific feature is OK to break because almost no app uses it -- we won't have that ability anymore.

So, I prefer to have only one layer where we maintain strict backwards-compatibility, which is the Cap'n Protocol protocol between app and supervisor.

**Comment by zenhack** [comment]
After sleeping on this a couple nights I think I agree; I don't really want to maintain strict compatibility for *both* layers. I guess I'll close this.

It's really kindof a shame though, since the layer we're maintaining compatibility for is the one almost nobody actually uses; If I could choose, I'd rather *only* maintain bridge <-> app compatibility, and treat the currently "stable" api as a private interface. But we're probably in too deep now :(.

**Comment by kentonv** [comment]
I dunno, I think there are advantages to maintaining compatibility at a _different_ layer than the API that people actually use, because it gives you some flexibility to fix mistakes in the API people actually use. An API that must maintain strict compatibility is likely to get gnarly over time, but that can be hidden by the app-bundled wrapper layer...
