### ISSUE TITLE
meteor-testapp seems to fail for me

### ISSUE THREAD

**Issue by kentonv** [sandstorm-io/sandstorm#3225]
Starting from a clean build, the spk I get seems to fail at startup:

```
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
** Starting Mongo...
2020-02-15T23:47:57.245+0000 I STORAGE  Engine custom option: log=(prealloc=false,file_max=200KB)
about to fork child process, waiting until server is ready for connections.
forked process: 10
child process started successfully, parent exiting
** Starting Meteor...
/programs/server/boot.js:356
}).run();
   ^

Error: The babel-runtime npm package could not be found in your node_modules 
directory. Please run the following command to install it:

  meteor npm install --save babel-runtime

    at meteorInstall.node_modules.meteor.babel-runtime.babel-runtime.js (packages/babel-runtime.js:37:9)
    at fileEvaluate (packages/modules-runtime.js:197:9)
    at require (packages/modules-runtime.js:120:16)
    at packages/babel-runtime.js:139:15
    at packages/babel-runtime.js:150:3
    at /programs/server/boot.js:303:34
    at Array.forEach (native)
    at Function._.each._.forEach (/programs/server/node_modules/underscore/underscore.js:79:11)
    at /programs/server/boot.js:128:5
    at /programs/server/boot.js:352:5
** HTTP-BRIDGE: App server exited with status code: 1
*** lost connection to grain (probably because it shut down) ***
```

cc @zenhack

**Comment by zenhack** [comment]
I was able to fix this by putting a cal call to `meteor npm install` just above this line:

https://github.com/sandstorm-io/meteor-spk/blob/bc9121a049e7f30c3bf075f4ebda5dcbd4cf1038/meteor-spk#L71

I don't think I understand why there's a similar call in the server directory, and whether that's entirely redundant with this or covers some other case that's important.

It seems like the fix though is to add that and then update meteor-spk.

**Comment by zenhack** [comment]
I'm tempted to suggest we junk meteor-spk for the purposes of the test app, and just use raw spk packaging. Reasoning:

This would unblock this issue on meteor-spk. Updating meteor-spk seems challenging, and not something that I otherwise want to spend time on. Frankly, I question the wisdom of trying to keep maintaining meteor-spk; We only have one app that's currently actively updated that uses it (Wekan), and @xet7 said on IRC he feels he can handle the upgrade issues himself, whereas a supported meteor-spk would have to build a more seamless upgrade experience. Also, especially given limited resources, I'd like to focus on supporting developer tools that are otherwise a good fit for Sandstorm (fast startup, easy automatic upgrading), and Meteor/MongoDB doesn't really fit that bill.

**Comment by ocdtrekkie** [comment]
There would be a certain irony to our Meteor-built platform not working well with Meteor apps, but yeah, people aren't really demanding support for Meteor apps. I am mostly concerned about Wekan at this point. It's just maybe a little sad too because we've done a bunch of demos in the past on how seamless/instant/automatic meteor-spk packaging was.

**Comment by zenhack** [comment]
Quoting Jacob Weisz (2020-02-23 13:58:39)

>    There would be a certain irony to our Meteor-built platform not working
>    well with Meteor apps, but yeah, people aren't really demanding support
>    for Meteor apps. I am mostly concerned about Wekan at this point. It's
>    just maybe a little sad too because we've done a bunch of demos in the
>    past on how seamless/instant/automatic meteor-spk packaging was.

Just for posterity, @kentonv said on the Call just now that he'd try to
update meteor-spk next weekend.

**Comment by ocdtrekkie** [comment]
> Just for posterity

Getting updates from the call communicated to issues on the list is a top notch thing! :D

**Comment by xet7** [comment]
Yes, up-to-date meteor-spk would of course make my work easier, and save me time.

**Comment by zarvox** [comment]
I believe this is fixed?  `meteor-testapp` appears to be at Meteor 1.10.1 now, and we seem to use `meteor-spk` 0.5.1 in the Makefile, and these tests are passing.  I'm gonna close this issue.
