### ISSUE TITLE
apps/web-publishing test is broken

### ISSUE THREAD

**Issue by ocdtrekkie** [sandstorm-io/sandstorm#3240]
Also tracking this test failure so we can get it cleaned up.

`<kentonv> and apps/web-publishing which has been broken ever since I rewrote the HTTP handling into C++`

**Comment by ocdtrekkie** [comment]
I suspect this one is super simple? One assertion is failed, which may just be a different choice of language.

```
✖ Testing if element <#result> contains text: "Shutdown success".  - expected "Shutdown success" but got: "Success"
    at Object.<anonymous> (/home/runner/work/sandstorm/sandstorm/tests/apps/web-publishing.js:69:17)
```

**Comment by kentonv** [comment]
It's not super-simple, or I would have fixed it at the time. :)

It's been a while since I looked at it, but IIRC the problem is that the test tries to verify that web publishing still works while the grain is not running. But it was using some trick to verify that the grain was not running which doesn't work anymore -- with the new gateway code, whatever it was doing actually has the effect of starting the grain back up. Which is actually a good thing in general, but it poses a challenge for this test specifically. At the time I couldn't think of a simple way to change the test such that it actually tested what it was supposed to be testing, but I didn't want to delete the test because I felt that it the thing it was trying to test was actually important...

**Comment by zenhack** [comment]
Picking through this, it seems that the problem is that `getUiBridge()` wraps the capability for the app in a `CapRedirector` that restarts it on disconnect, and because the app just does an `exit(0)` in its request handler, it's going to disconnect before returning.

The comments on `CapRedirector` suggest that it was originally intended to do this only for the sandstorm frontend, rather than grains, so I assume what changed when you wrote the gateway is that we started using this there too, whereas the old js version would just let the grain stay dead.

Since the CapRedirector only detects disconnects when making method calls, It seems like if we somehow deferred the exit() until after that method has returned, then it shouldn't get restarted unless another request is made to the grain. I will have to try this.
