### ISSUE TITLE
Unbundle clang

### ISSUE THREAD

**Issue by zenhack** [sandstorm-io/sandstorm#3331]
I wanted to get people's thoughts on this: right now the build downloads clang binaries from the chromium project. IIRC this was originally added because we were using C++ features that at the time were very new (C++14), and many distros did not have a sufficiently recent toolchain, so folks were having difficulty getting Sandstorm to build.

This is probably no longer necessary; afaik we haven't started depending on even newer features, and most distros should now be shipping a compiler that supports C++14. So: is there any reason to keep doing this? It would be vaguely nice not to have to re-download the compiler every time I did `make clean`.

**Comment by ocdtrekkie** [comment]
I have traumatic memories from that time, I believe that was why nobody ever succeeded in building Sandstorm. I don't know enough to meaningfully comment on if we no longer need to do this or not though. Are we likely to use newer C++ features soon?

**Comment by zenhack** [comment]
Fwiw, I remember having issues building sandstorm back then too, despite having a very recent compiler (I run arch...). There were many issues, this was only one of them. (Not having to build node from source anymore helps too; I remember that being a big sticking point).

Personally I'm fine restricting myself to C++14. @kentonv will have to comment on this, but I imagine capnproto is likely to want to be a little conservative with bleeding edge features, since there's more of a compatibility demand on the library.

We should change the compile flags though; right now we're passing `-std=c++1z`, which would make it easy to "accidentally" use newer features. (I suppose it's also possible I missed some newer stuff going in, but we should test).

**Comment by kentonv** [comment]
Is there a good reason _not_ to pin clang?

Based on my experience with Cap'n Proto, if we want to say we support whatever compiler version comes with your distro, then realistically we need to set up CI with a build matrix with old and new versions of GCC and Clang, otherwise things are likely to break randomly for any compiler we aren't testing. Unfortunately, restricting ourselves to C++14 does not necessarily mean all C++14 compilers will successfully build the code the same way.

I'd much prefer we keep our clang version pinned so that everyone get the same results and we don't have to spend time chasing down problems.

I also could easily imagine that we soon want to use C++20 features (async/await?) which won't be possible if we aren't pinning Clang.

**Comment by ocdtrekkie** [comment]
I will note that I've seen multiple people build from source to work around the recent breakage, so people being able to build from source without running into additional walls has been a really nice perk lately.

**Comment by zenhack** [comment]
FWIW setting up a build matrix might not be a bad idea anyway; GCC has
some warnings that clang doesn't, and having built sandstorm with GCC
trying to get asan working I'll be sending in at least one patch due to
stuff it spotted (though the issue is benign in this case, it could
easily not have been, and that makes me nervous). It would probably be
good to be running stuff with asan or the like too. I agree we'd
*definitely* want to do this if we were actually going to support
multiple compilers.

...but I guess I don't feel *that* strongly.

Quoting Kenton Varda (2020-05-09 13:36:44)

**Comment by kentonv** [comment]
Clang has its own address sanitizer; we should probably use that rather than trying to maintain a GCC build: https://clang.llvm.org/docs/AddressSanitizer.html

What warnings did GCC have that Clang doesn't? Is it possible we just haven't enabled them in Clang? In my experience GCC's warnings tend to be wrong more often than they are useful. :/

**Comment by zenhack** [comment]
Yeah, I know clang has this too, I ended up doing it with GCC because for some reason clang's libasan is missing on my system? And the clang we're downloading for some reason only has arm versions. Was just the path of least resistance in this case.

The warning that came up is on this line:

https://github.com/sandstorm-io/sandstorm/blob/714b8e4f2313e49eec4f6bd8d0b9b5720bf2fdbd/src/sandstorm/sandstorm-http-bridge.c%2B%2B#L189

`nread` is unsigned (size_t), so the comparison with zero is always true. I'd hazard a guess whoever wrote that was thinking about APIs like read/write that return an `ssize_t` with a negative value for errors. In this case it's harmless, but ineffectual bounds checks make me nervous.

**Comment by zenhack** [comment]
I think I've come around to this not being a good idea, so I'm going to close.

btw, I have now managed to get an asan-instrumented version of sandstorm built with clang, although it still has problems. baby steps.
