### ISSUE TITLE
update main page to reflect current status of project

### ISSUE THREAD

**Issue by CouldBeThis** [sandstorm-io/sandstorm#3340]
Hello! I am not a user of sandstorm though it looks really interesting to me. I just found out about it an hour or so ago. 

I would like to suggest that that [main page](https://sandstorm.io/) be updated to reflect the current status of the project. 

For example, the page states hosting is possibly on "our community-run servers" but as you are all aware, the oasis project (which I believe is whats being referred to here?) closed since new year. There is a link to oasis signin in the top right corner of the page and in the footer.  Links and references to this which imply it's active should be removed. Maybe search the text of the  source files. 

It was only by searching on reddit that I found the [post from February](https://sandstorm.io/news/2020-02-03-reviving-sandstorm) about reviving the project. Since there is no followup post on the blog, I infer this is still a work in progress. 

If there is doubt about the longevity or stability of the project, I think that should be honestly conveyed to potential end users, especially unsophisticated ones like myself who could run into a lot of trouble becoming reliant on a project that could vaporize. Perhaps add an updates email list signup form or twitter handle or something for people who are interested in hearing about progress. 

Anyway I'm sure someone who is actually familiar with the project would be better suited to make more specific suggestions/changes. Oftentimes devs and others who are really involved in a project don't look at this stuff once it's posted so an uninformed user like myself is better able to notice potential problems in it. So perhaps someone can take the time to go read that stuff to see what needs to be updated.

**Comment by zenhack** [comment]
Yeah, we should remove the remaining references to Oasis. I did a pass on the website around the same time I wrote that post, but IIRC at the time it was still technically possible to log in to Oasis and download/transfer existing data and such, so we left the sign in links in place. We probably also just missed a few things that didn't match the particular strings I searched for, and I agree "our community run servers" should probably be removed.

Fwiw, the uptick in activity has kept going, and I'm honestly less worried about the project vaporizing now than I was when it was managed by a VC funded startup. Development is slower due to fewer resources, but it's also less dependent on continually finding more investors, or (old fashioned idea) actually having a sustainable business model...

I think most of us are generally in agreement that parts of the website still feel too business-y.

I also think it would be nice to get another blog post out about something. Hopefully once the couple loose ends with Let's Encrypt/TLS stuff that went in recently are taken care of that will be a good topic for one...

**Comment by CouldBeThis** [comment]
I logged into Oasis using github and that's where I found out it was no longer supported. 

Whatever the outlook is, I think it would be good to have something about it. 

a bit of a rant you can skip if you are not interested: I am a long time user of open source software and it's always my strong preference.  But  lately I am growing distrustful. there has been so much growth in packages that either run entirely on a host somewhere (I generally avoid selfhosting where possible), or are reliant on someone doing something.  in this case, if I understand, someone needs to ?laboriously? create packages for updates to be sent out; if this wasn't done then all your data would be vulnerable to whatever issues missed updates addressed. Developers of projects put up these beautiful aspirational pages that describe the project they *plan* to end up with rather than what actually exists. Then I spend a bunch of time trying to set something up (which is very slow sometimes as a non dev because I have to look up every single thing, read oodles of documentation if it exists, sort though dependencies I don't understand etc), only to find that there was actually no possibility that it would ever function as I hoped, or critical support is withdrawn shortly after. I understand that these things take a tremendous amount of work, that many are done with inadequate funding if there is any at all and I don't have any ill will to developers who for whatever reason move on. I just think setting clear expectations is fair.

Anyway you are obviously not responsible for this widespread practice. I am just explaining from a POV not often represented on github (a person who knows github exists and can use it, but isn't a programmer) because from what I read I get the impression that the target audience includes people like myself.  Which is the extent to which I able able to contribute. 

I will probably try installing this on my rbpi when I have the opportunity. :)

**Comment by ocdtrekkie** [comment]
Sandstorm app packaging is a bit of a thing, and many app packages are older versions of apps. However, Sandstorm's security model is significantly more restrictive than most. While that makes packaging more work, it also means Sandstorm isn't particularly reliant on app updates for security, the impact of an app vulnerability is often incredibly small or even completely mitigated by design.

Sandstorm also won't run on a Raspberry Pi, unfortunately. While theoretically, Sandstorm could be built for ARM systems, it'd also require ARM releases of all the app packages, which would multiply the app packaging and update difficulties.

**Comment by ocdtrekkie** [comment]
As @zenhack said though, I also feel much more confident in the long-term outlook of Sandstorm now that it's moving along without startup funding. The progress is slower, but features are prioritized by what users want and need rather than what is likely to move the needle on business success.

Sandstorm basically has the best security model. While I can't tell you that Sandstorm will change the world of app hosting, I think everyone else's platforms will eventually end up having to look more like Sandstorm someday.

If there's additional feedback you have on the website or documentation, feel free to share it and I'll try to push some PRs to clean them up, and feel free to ask any questions you have. The perspective of newcomers is often pretty valuable, so we're happy to take it into account.

**Comment by Michael-S** [comment]
@CouldBeThis  

I can't add anything constructive here, just that I'm sympathetic to your frustration.  Building useful software that is simple to maintain and install is incredibly time-consuming, and most of the open source community has a lot more heart, hope, and dreams than time and money.

I love Sandstorm and I've been using it since the original launch.  I have not yet recommended it to my less technical friends and family, for the reasons you state.

**Comment by zenhack** [comment]
There are two relevant prs now:

- https://github.com/sandstorm-io/sandstorm-website/pull/320
- https://github.com/sandstorm-io/sandstorm-website/pull/321

Once those are merged I suggest we close this and open separate issues about any further changes  needed that we find.

**Comment by ocdtrekkie** [comment]
I will close this now, as it relates more to the website than Sandstorm itself, and I think the website PRs do cover this issue suitably.
