### ISSUE TITLE
Install Instructions

### ISSUE THREAD

**Issue by TWINGSISTER** [sandstorm-io/sandstorm#3368]
I discovered this wonderful work and searched issues and found nothing about this so I dare to ask.
It is difficult for me to find a free server to install Sandstorm. I would be glad to propose my colleagues this environment but I would like to bring them to  a computer lab and ask them to follow a procedure so that at the end they have their own copy running for free and possibly with no credit card. So things like AWS are out.
Probably you can do that for an unlimited time onto Heroku free tier and onto IBM  Cloud. One year free tier from Pivotal and two months from Red Hat Open Shift. I couldn't find any other option. 
I think that deployment on Heroku could be the right way to go since I succeeded installing Huginn without installing Docker just pressing a button
https://elements.heroku.com/buttons/huginn/huginn
as in 
https://elements.heroku.com/buttons/huginn/huginn 
Can you help me in this?

**Comment by Michael-S** [comment]
I run a Sandstorm instance out of my house, and I've done that since the project launched.  It requires just a bit more technical expertise than running Sandstorm on traditional server hosting because you have to configure your home network settings properly, and because you have to set up your own backups.  But you don't need a fixed IP address from your internet service provider because of the sandcats dynamic DNS ( https://docs.sandstorm.io/en/latest/administering/sandcats/ ).

Unless you're supporting a lot of users from one Sandstorm installation, the Sandstorm resource requirements aren't that high.  You could probably comfortably use it on a Linux virtual machine with 3GB of RAM running on all but the lowest tier desktop computer.  Or you could install Linux on an old laptop (provided it has 2 or ideally 3GB of RAM and an x86_64 processor) and run it that way.

As you may already know, Sandstorm is not - yet - supported on the Raspberry Pi or other ARM processor architectures, and there are no plans to support it on non-64 bit x86 processors.

The other option I would suggest is that if you and your colleagues have a good level of trust, you could pool your money and have one shared instance for all of you.  That could be one server rental for all of you from AWS, DigitalOcean, Linode, Vultr, Scaleway, or whatever (I have used the first three, not the last two but they all have good reputations).  Or one of you could buy a low end used laptop or desktop and host it out of their home for all of you.

**Comment by zenhack** [comment]
Unfortunately deploying to a PaaS like Heroku or OpenShift isn't technically feasible; Sandstorm's sandboxing mechanisms require it to have more access to the OS than these platforms provide. You really need a VM or an actual machine, unfortunately. I really wish there was a free option we could point people to.

I second most of @Michael-S's advice.

**Comment by ocdtrekkie** [comment]
It's also worth noting that your colleagues could try Sandstorm at https://demo.sandstorm.io and see if they like it, prior to investing any money in it. Michael's suggestion to get a cheap hosting solution to share amongst you is a good idea too: Sandstorm works pretty well and is very efficient for a small group of users, since grains/apps that aren't open aren't running and using server resources.

I will go ahead and mark this closed since supporting Heroku or OpenShift isn't possible.
