### ISSUE TITLE
Failed to install app: TypeError: path must be a string

### ISSUE THREAD

**Issue by mbcheikh** [sandstorm-io/sandstorm#349]
Some applications fail to install (etherpad, wordpress). Others installs are ok (ethercalc, draw.io). Here is the log for the install
Downloading app: http://sandstorm.io/apps/etherpad4.spk
Failed to install app: TypeError: path must be a string
    at Object.fs.unlinkSync (fs.js:771:18)
    at AppInstaller.<anonymous> (app/server/installer.js:325:8)
    at ClientRequest.<anonymous> (app/server/installer.js:182:21)
    at ClientRequest.emit (events.js:95:17)
    at Socket.socketErrorListener (http.js:1551:9)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)

**Comment by kentonv** [comment]
The TypeError was actually a bug in the error path, fixed by #351. If not for that bug, you would have seen some other error.

I'm guessing the real error is the DNS error that people have suddenly been reporting lately. It's interesting that you saw the error for apps where the package is hosted at sandstorm.io but not for apps which are hosted elsewhere.

Could you tell me a bit about the machine you're running on? Does the machine's network configuration change often (e.g. is it a laptop that connects to many different wifi networks)? Anything else unusual about it?

**Comment by mbcheikh** [comment]
The error has now disappeared without doing anything. I was able to install all the applications and to use them without errors. Thank you for your fast response
