### ISSUE TITLE
Add support for passing ACME challenges to PowerDNS-based DNS services

### ISSUE THREAD

**Issue by riesenrad** [sandstorm-io/sandstorm#3530]
Sandstorm is all about self-hosting. However, all DNS services which currently are supported by Sandstorm to pass ACME challenges (with the purpose of creating TLS certificates) cannot be self-hosted. PowerDNS Authorative Server is a software allowing to self-host a DNS service. An operator of a Sandstorm instance should be able to configure Sandstorm to use their own PowerDNS Authorative Server instance, akin

```
sandstorm configure-acme-challenge powerdns '{ "foo": "bar" }'
```

However, currently, this fails:

```
server:~ # sandstorm configure-acme-challenge powerdns '{ "foo": "bar" }'
sandstorm configure-acme-challenge: powerdns: unknown module: powerdns
Try 'sandstorm configure-acme-challenge --help' for more information.
```

It fails because, currently, the Sandstorm distribution does not contain the acme-dns-01-powerdns NodeJS package (see https://www.npmjs.com/package/acme-dns-01-powerdns or https://git.y.gy/firstdorsal/acme-dns-01-powerdns).
Therefore, this package should be included in the Sandstorm distribution, like the other acme-dns-01-* NodeJS package are already included.

It seems that adding a dependency on this package is a trivial task.

**Comment by ocdtrekkie** [comment]
Yeah, this should be simple assuming it works like the modules for other providers, a few folks have submitted other additions in the past.

**Comment by ocdtrekkie** [comment]
#3449 is an example to follow, if you want to submit it yourself, otherwise I can try to put it together tonight if I have time.

**Comment by riesenrad** [comment]
It would be great, if you can do it :-)

**Comment by ocdtrekkie** [comment]
So the only thing I'm noticing, is the instructions for the powerdns package expect using a .env file instead of the usual instructions the other DNS provider plugins use. I think that might just be the author expressing his preference though, because the sample code looks like it does something similar to other packages. So I suppose it shouldn't be much harm to add it, and then you can let us know if it works for you!

More than likely, we should be able to get this into the next release, which is in roughly a month. But once I have the PR open, we can also probably point you to an unofficial dev build you could upgrade to if you want to get it sooner.

**Comment by zenhack** [comment]
Quoting Jacob Weisz (2021-06-13 19:06:22)

> I think that might just be the author expressing his preference
> though, because the sample code looks like it does something similar
> to other packages.

This was my interpretation -- I suspect it will work just fine.
