### ISSUE TITLE
Implement email and password authentication with 2FA

### ISSUE THREAD

**Issue by jonatasbaldin** [sandstorm-io/sandstorm#3561]
Hi there!

I didn't know that email/password was not a feature until I installed Sandstorm myself.

I believe that it should be a thing for a couple of reasons:
- Users might not want to be trapped with other services (GitHub, Google), like myself
- People don't have or don't understand other authentication systems (like LDAP)

The passwordless solution should work nicely, but less techy users might don't understand SMTP or don't want to have an account with a SMTP provider.

I browsed around the issues and understood that the main reason against email/password is security, since people use weak passwords etc.

What I propose is: **Implement email/password login with required 2FA authentication**.

I believe that solutions like these should be as accessible as possible, specially for non-tech users. Requiring them to setup third-party services could be a big blocker.

What do you think?

I'm trying Sandstorm for the first time and it is really fantastic, thanks a lot ❤️

**Comment by ocdtrekkie** [comment]
Since you browsed other issues about this, I won't rehash too much, but the Sandstorm project is less funded today than it was when the decision was first made not to include an authentication database directly in Sandstorm. We are less equipped today to handle issues with authentication than we were then.

SMTP setup can definitely be a point of frustration, but I would point out that a password system won't really help avoid SMTP setup. It's a pretty critical component for grain sharing and notifications, so the Sandstorm experience without it will be pretty limiting.

**Comment by jonatasbaldin** [comment]
Got it. Thanks for the answer @ocdtrekkie.
