### ISSUE TITLE
E_CREATE_ACME_ACCOUNT on Ubuntu 18.04

### ISSUE THREAD

**Issue by jdougan** [sandstorm-io/sandstorm#3624]
I spun up what Chunkhost calls an Ubuntu 18.04 instance for sandstorm because the sandstorm/ttrss I have on a 16 instance is falling over with updater crashes and I wanted to update anyways.  Then the installer fell over trying to do ACME stuff (E_CREATE_ACME_ACCOUNT).

[console.log](https://github.com/sandstorm-io/sandstorm/files/8767860/console.log)

[sandstorm.conf.txt](https://github.com/sandstorm-io/sandstorm/files/8767879/sandstorm.conf.txt)

[sandstorm.log](https://github.com/sandstorm-io/sandstorm/files/8767880/sandstorm.log)

[mongo.log](https://github.com/sandstorm-io/sandstorm/files/8767884/mongo.log)

updater.log is empty

Am I missing a package? Anything else that might help y'all?

(Once I have a chance to look more closely at the original install, that may get a separate issue)

**Comment by ocdtrekkie** [comment]
The installer not even being able to report the error sounds like something is wrong with Internet connectivity in general. I believe that is basically a plain curl command from the install script, and it would've given a different error if you didn't have curl. But you also successfully downloaded Sandstorm itself using curl, so that's a bit strange. I was wondering about maybe a TLS issue, but the earlier download was over HTTPS, and your date and time looks accurate too.

And then also not sure why Sandstorm appears to fail to spin up Mongo and then dies too, that's interesting.

**Comment by ocdtrekkie** [comment]
Actually, that might be a red herring: https://github.com/sandstorm-io/sandstorm/blob/master/install.sh#L92 as that reports to Oasis, which does not exist...

**Comment by jdougan** [comment]
How can I manage/delete the sandcats entry without having sandstorm running?

**Comment by ocdtrekkie** [comment]
So actually deleting your entry for the Sandcats server requires Kenton deleting it for you. But you should be able to recover it on a fresh install via the registered email address when setting up a server.

`Error: couldn't add user: not master` seems to be the core issue here, now that we identified #3625 as likely unrelated. Since Sandstorm can't set up it's database correctly, it can't configure the certificate info, which it stores in the database. That seems to happen for Mongo databases with replication, when trying to write to a secondary? Your mongo.log suggests there's a replSet, but I am pretty sure Sandstorm uses it's own internally packaged Mongo? So I'm confused.

**Comment by jdougan** [comment]
I havent killed the VPS yet, anything I can do to it, copy from it, that'll help?

**Comment by ocdtrekkie** [comment]
@zenhack may have better insight. This is a weird one to me, so I'd love to find out what's going on, but I don't know how much it's costing you to keep it running, so I don't know if I would suggest holding off.

Did you get the mongo.log from inside the /opt/sandstorm folder, or is that a system mongo?

**Comment by jdougan** [comment]
> @zenhack may have better insight. This is a weird one to me, so I'd love to find out what's going on, but I don't know how much it's costing you to keep it running, so I don't know if I would suggest holding off.

It's a pretty minimum instance and there is nothing important in it .  I can wait for a bit.

> Did you get the mongo.log from inside the /opt/sandstorm folder, or is that a system mongo?

/opt/sandstorm/var/log

relevant part of /var/log/syslog, check the exit code:

```
May 24 20:27:40 ss20220524a systemd[1]: Starting Sandstorm server...
May 24 20:27:40 ss20220524a sandstorm[834]: Sandstorm started. PID = 838
May 24 20:27:40 ss20220524a systemd[1]: Started Sandstorm server.
May 24 20:27:40 ss20220524a systemd[1]: Started resolvconf-pull-resolved.service
.
May 24 20:27:56 ss20220524a systemd[1]: sandstorm.service: Main process exited,
code=exited, status=1/FAILURE
May 24 20:27:56 ss20220524a systemd[1]: sandstorm.service: Failed with result 'e
xit-code'.
```

**Comment by ocdtrekkie** [comment]
Okay, just checking. I think more than likely you provided anything I can think of which would help figure out what happened.

**Comment by jdougan** [comment]
Tried with Centos 7, similar result. This time I specifically get a E_FETCH_CERTIFICATE error before it blows up in the error reporting.
The console og has a bunch of stuff at the top from `yum update`. Only there in case you want version info.
[centos7console.log](https://github.com/sandstorm-io/sandstorm/files/8790363/centos7console.log)

[sandstorm.conf.txt](https://github.com/sandstorm-io/sandstorm/files/8790366/sandstorm.conf.txt)

[mongo.log](https://github.com/sandstorm-io/sandstorm/files/8790369/mongo.log)

[sandstorm.log](https://github.com/sandstorm-io/sandstorm/files/8790371/sandstorm.log)

Updater.log empty

**Comment by zenhack** [comment]
(Apologies for the slow response time on my part; it's been a busy week)

How much memory does the centos box have? In the second sandstorm.log it looks like it might be dying in the midst of installing the standard apps, so I'm wondering if you're hitting #3429.

This, from the first log, looks relevant:

```
** Starting MongoDB...
note: noprealloc may hurt performance in many applications
about to fork child process, waiting until server is ready for connections.
forked process: 8
child process started successfully, parent exiting
2022-05-25T03:27:56.929+0000 Error: couldn't add user: not master at src/mongo/shell/db.js:1004
failed to load: /tmp/mongo-command.YUjPjo
```

I've seen this happen in CI a couple times, but I've never been able to reproduce it and this is the first I've heard of it happening outside of our CI.

I think the ACME error code is a red-herring; it sounds like mongo died on it and that happened to be what it was in the middle of.

Also, it seems like this might be two different issues, though if the first issue is happening because of limited memory, it wouldn't surprise me if that was the source of the second as well.

We generally recommend a minimum of 2GiB anyway, though it's definitely a bug that we need anywhere near that much during setup.

**Comment by jdougan** [comment]
In both cases it is 1 GB. (for that matter that is what my existing sandstorm install is running on.)  In all cases they are dedicated sandstorm boxes.  I'm  running this in a fairly tight budget, maybe the right answer to to figure out how to get all the ttrss data out and drop sandstorm?

**Comment by ocdtrekkie** [comment]
Are you only using Sandstorm for TTRSS? Unfortunately I don't think Sandstorm is really meant to run in a 1 GB environment, although as you can tell, it's possible.

Trying to think, if we think it crashed installing default apps though, we might be able to skip that? Dev installs don't have default apps.

**Comment by zenhack** [comment]
Do you have a swap partition/file? If it's just the one grain, it might be okay steady-state; adding swap might be enough to get it through setup.

**Comment by jdougan** [comment]
I just checked, swap is off, but it can be set up.   I can try that. Other possibility that just occurred to me is to install on a 2GB vps, back it up and restore onto a smaller one.

How difficult is it to reconfigure a sandstorm install with a different sandcats name? Last time I tried backing up nd restoring the whole vps, things got confused because both sandstorms were assuming that had the name.

**Comment by jdougan** [comment]
It installed on a 2GB Ubuntu 18 instance, and failed on a 1 GB instance with 2GB swap. When I tried again with a 4 GB swap, it installed.

Is there  a warning in the instructions about the installation memory requirement?

How difficult is it to reconfigure a sandstorm install with a different sandcats name without starting it? Last time I tried backing up nd restoring the whole vps, things got confused because both sandstorms were assuming that had the name and shutting down the old instance wasn't an option.

**Comment by ocdtrekkie** [comment]
Ian indicated he might take a look at the issue soon, otherwise it might make sense to include a warning about it, I'd agree.

We don't presently list any system requirements except the processor architecture and the minimum kernel version. I honestly think it might be appropriate to say Sandstorm requires 2 GB of RAM to begin with, even if it's theoretically possible to get it running on 1 GB. It's definitely something that's come up a few times before.

**Comment by zenhack** [comment]
Yeah, we probably should have recommended system requirements in the docs somewhere -- though the memory usage during installation is just a bug, the cause of which I have identified, and I did start messing around with fixing it.

**Comment by zenhack** [comment]
Re: changing the sandcats name: I have never tried this, and I haven't dug into that part of the code enough to have an intuition as to how it might go. Sorry :(

**Comment by ocdtrekkie** [comment]
Ahhhhh, I guess we do specify that on the website. I checked the docs site instead. That seems accurate/adequate.

I suppose either a process of documentation for changing your Sandcats name probably makes sense. I do suspect you'll have some challenges with it since the registration process is part of the install script, and I don't think Sandstorm itself is intended to do that at present.

**Comment by jdougan** [comment]
Now I have the other issues opened, I'll just close this one, unless y'all want to reopen it to be more searchable.
