### ISSUE TITLE
Does Sandstorm passwordless login links need some changes?

### ISSUE THREAD

**Issue by xet7** [sandstorm-io/sandstorm#3638]
Outlook scans emails arriving in your inbox and sends all found URLs to Bing:
https://news.ycombinator.com/item?id=31892299

**Comment by zenhack** [comment]
Bravo Microsoft.

Hopefully they at least respect robots.txt? If so that should keep sandstorm's links out of search results. They're also single-use and I *think* have a 10 minute expiration.

**Comment by ocdtrekkie** [comment]
I don't believe sharing invitations expire. Especially if you manually create a link and then email it. I have several document invitation links publicly posted going out for years that are still occasionally clicked on.

But yeah, hopefully since we disallow indexing we should be okay, I believe. (Thanks for #3279, Ian!)

**Comment by ocdtrekkie** [comment]
As a note, some discussion on the story suggests that while BingBot is the user agent, that this also may just be malware scanning/SmartScreen, and not an intentional attempt to feed the links into Bing indexing. I saw one comment claiming a link got into Bing this way, but we'll have to see when there's more testing and feedback on this.

*Assuming* that's true, I think this might frustrate email login, but shouldn't really impact shared grains negatively (except in the case of a manually-pasted share link, which BingBot could then access, but presumably not list anywhere).

**Comment by zenhack** [comment]
Do we have someone who uses outlook who could test this against some server to see if bing is actually hitting these links?

**Comment by kentonv** [comment]
Does... does this mean Outlook automatically follows the unsubscribe link on every mass mail, thus unsubscribing people from everything?

**Comment by zenhack** [comment]
I'm tempted to suggest there's nothing actionable for us to do here; it seems like given that we set `robots.txt` correctly if this is still a problem for us then we're probably in good company... Should we just close?

**Comment by xet7** [comment]
@zenhack 

Yes I think so.
