### ISSUE TITLE
How are updates to applications handled?

### ISSUE THREAD

**Issue by mattl** [sandstorm-io/sandstorm#378]
WordPress has a lot of users, as so it gets a lot of updates.

After installing WordPress from the Sandstorm demo, I am presented with a WordPress 4.1 site that refuses to acknowledge a new version. How does Sandstorm handle updates to projects and how can app developers ensure that users on Sandstorm are getting access to critical fixes?

**Comment by dwrensha** [comment]
Hi! A few things to note:
 1. Once there's a new packaged version of the WordPress app, you'll be able to install it and have the option to automatically migrate your data. We plan to additionally implement optional push updates in the future.
 2. The security-centric design of Sandstorm makes app updates less important. In the WordPress app, any content that you publish is served as static HTML. The only people who will have access to anything other than static HTML are the people with whom you explicitly share access via the "share" button. If you install an evil plugin, it can still mess up the data of your instance, but the damage will be confined only to that instance due to Sandstorm's tight Sandboxing.

**Comment by paulproteus** [comment]
Thanks for asking this, @mattl ! I'm going to close this for now, since I believe @dwrensha answered the question in a comment. If not, then please re-open it so we don't lose track.
