### ISSUE TITLE
Feature Request: local accounts or Active Directory/LDAPauthentication

### ISSUE THREAD

**Issue by captainwasabi** [sandstorm-io/sandstorm#429]
I can't require all my users to go get github or google accounts.  I'd like to use this but that's impossible.

**Comment by ocdtrekkie** [comment]
AD/LDAP is definitely high on my want list too, I want to make a Sandstorm server at my company. Email token authentication may meet your needs as well though, and is currently implemented. If you have an internal mail server, this can operate entirely in-house.

**Comment by captainwasabi** [comment]
ugh, I was so hopeful re:email token and tried it out.  Even getting an email and clicking a link **everytime** they want to log in is not something they'll accept. :(  Once a year maybe.  maybe not.

**Comment by kentonv** [comment]
Hi,

We plan to support LDAP as a feature of our enterprise product, coming later this year. If you'd like to be one of our early testers for this product, sign up here:

https://docs.google.com/a/corp.sandstorm.io/forms/d/15RikXG1b-giAf93PJiCd2bkPBvGhR_MT3ocziEzbqOw/viewform

> clicking a link everytime they want to log in is not something they'll accept.

Note that logins don't expire, so it's more like every time they want to log in from a new computer.

We are trying very hard to avoid implementing password login as it is highly insecure and requires additional work on the part of the server admin to police hijacked accounts. We don't feel that the average self-hoster is in a good position to rely on passwords. It may work OK in a corp environment with dedicated IT staff.

How do you feel about 2-factor authentication?

> I need to mass invite people, and I can't expect them to all respond within 15 minutes.

The way to invite people is through the "Send Invite" tab in the admin settings. Invites do not expire, and can be used with any login mechanism including Google and Github (which are massively more secure than email, if your users happen to have one).

It sounds like maybe you are trying to send "invites" by typing email addresses into the email login box? That won't do what you want -- even if the user logs in within 15 minutes, they'll only be a guest with no ability to do anything (see below). Perhaps we should improve the UI here to make this clearer.

> I also need some way to delete users

In the new "users" tab under the admin panel (which rolled out over the weekend), you can set users to "guest" if you don't want them to be able to install apps or create grains. They can still log in for identity purposes, but they can't do anything once logged in except see things that non-guest users shared with them.

Note that anyone who logs in uninvited is automatically made a "guest". (Thus it wouldn't make sense to "delete" users because they'd just be recreated the next time they log in.)

**Comment by captainwasabi** [comment]
| ...logins don't expire... and ...invites don't expire...

Ah, ok, when I was testing I was logging out and then trying to log back in.  And was having to re-invite myself.  I will retest.

Can they use the same invite from multiple computers? (I have 4 that I use, 2 at home and 2 at work) or does it disable after it's used?  Can they use the same invite multiple times from the same computer?  For me to get buy-in from my C-types it has to be EASY and works every time.

| ...Google and Github...

Some of my users probably have both, some will definitely have neither and I can't ask then to set them up for business purposes.

Finally, I guess I'd have to be able to disable the guest user type.  If I need to revoke access to someone they can't log in at all or see anything, even if it was shared with them previously.

Personally, I am cool with two-factor and use it for myself in multiple ways, won't work for my C-types.

LDAP, I use it for multiple things, including services hosted on Ubuntu servers via winbind.  If I had an actual IT budget then I wouldn't mind it being Enterprise only, that aside it probably should be since unless you are in a corporate environment you probably are not using it.

**Comment by kentonv** [comment]
We'd be very happy to do whatever we can to help you make your case to your "C-types". :) Could you send an e-mail to sales@sandstorm.io (which goes to me and @jadeqwang -- not actual sales people ;) ) to tell us more about your company and your needs?

> Ah, ok, when I was testing I was logging out and then trying to log back in. And was having to re-invite myself. I will retest.

To be clear, "invites" are the things created through the admin panel (at `/admin`). If you clicked on "sign in" in the upper-right and then entered an e-mail address, that doesn't send an "invite", it sends a login token. When using email login, you do in fact have to generate a new login token every time you log in, including at least once from each computer. However, once you've logged in on a computer, you remain logged in until you choose to log out.

With LDAP integration, it will be possible to integrate with your company's single-sign-on, which should make this all much easier. The email login is meant as a stop-gap for people who can't use any of the other systems.

> Finally, I guess I'd have to be able to disable the guest user type. If I need to revoke access to someone they can't log in at all or see anything, even if it was shared with them previously.

Since a guest account can'd do anything except accept shares, I think another way to say what you want is: you want to prohibit users from sharing outside of your organization, and you want to be able to add and remove users from your organization. This is something we plan to implement as a "sharing policy". Policies don't control who can log in but do control who is allowed to share with whom. In our enterprise product, system administrators will be able to apply policies across the whole organization, whereas in the standard edition users will be able to set policies only on their own grains.

Our sharing model is currently pretty new, though, and we're still working on these features. We'd be happy to up the priority of that work if there is a potential client who needs it soon. :)

**Comment by captainwasabi** [comment]
Hi, I can already prevent sharing outside my organization.  It'll be on a
LAN behind a firewall.  If you want to get to it you have to VPN anyway.
VPN already works of AD so I'm good there.

Unfortunately, I wouldn't identify is as a potential "client."  As I
mentioned before, I got no budget.

And I guess revoking access to something is as easy as backing it up,
killing the grain, then starting a new grain from the backup, or something
like that.

--

**Comment by neo-luddite** [comment]
hey,
I'd really like to see ldap integrated in the non-enterprise version. auth via google and/or github are out of the question (3rd party), and auth via email is much too insecure for our group of acitivists. I understand your logic behind the email-auth-system, but in our case (relative small user group and non public) the users cannot request new passwords via email but have to deal with the admins on a secured communication channel if the cat ate their post-it with the password.

tnx

**Comment by kentonv** [comment]
@neo-luddite We're currently working on a plan that I believe you'll find acceptable:

- "Sandstorm for Work" will be open source (Apache 2.0).
- In order to get zero-maintenance auto-updates from us, you'll need to pay a subscription fee.
- However, we will happily waive the subscription fee for non-profit groups such as yours (we'll give you a "feature key" which unlocks LDAP in the official build for free).

We expect to launch this in the next two months or so.

@captainwasabi Assuming your workplace is for-profit, we won't be able to waive the fee, which will probably be $15/user/month. Perhaps you could expense it on a company credit card? If not, your other option is to build from source and remove the "feature key" check, but then you won't get auto-updates.

**Comment by ocdtrekkie** [comment]
@kentonv Assuming people show general common respect for you guys, I think that sounds like a pretty awesome way to do this.

**Comment by neo-luddite** [comment]
@kentonv
sounds great, tnx a lot!

**Comment by boredland** [comment]
Are there any updates in that matter?

**Comment by ocdtrekkie** [comment]
@boredland Sandstorm for Work supports both SAML and LDAP. SAML is preferred for Active Directory.

https://docs.sandstorm.io/en/latest/administering/for-work/
https://docs.sandstorm.io/en/latest/administering/active-directory/

**Comment by kentonv** [comment]
Indeed, I think we can close this bug as "done"! :D
