### ISSUE TITLE
Listen on ports 80 (and possibly 443) in default install

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#497]
In the default install, if you have nothing else running on port 80, it'd be great if Sandstorm took over that port. That way, no one has to see ugly `:6080` strings in their URLs.

Some thoughts about this:

* Once we have this, if we have some kind of TLS certificate integration, we could also bind to port 443.

Some questions about this:

* What can we do to support people installing Sandstorm today, and then later deciding they want to add nginx etc. to the VM that they are running Sandstorm on, in order to enable apps that aren't Sandstorm itself?
  * Proposal: Write a wiki page saying clearly how to configure Sandstorm to stop listening on ports 80 and 443, and provide a sample nginx conf stanza on how to do that, and preferably add a test to `installer-tests/` indicating that Sandstorm can actually be reached if someone follows these steps.

* What should we do if the installer detects you _do_ have port 80 in use? Presumably Sandstorm should do what it does now, which is to take port 6080, but that does mean that OAuth URLs (breaking auth providers) would change if they decide to tidy things up. It's kind of sad that the installer will result in different port numbers based on details of your system.

Semi-crazy alternative:

* Sandstorm could _always_ listen on port 6080, and we can use `iptables` port forwarding to borrow port 80/443, and then tell people how to turn that off if they want to have nginx etc.
  * The problem with this is that it's pretty un-discoverable because it means the use of port 80/443 by Sandstorm wouldn't show up in `lsof -i TCP`. I actually lost an hour last week sysadmining a system where I had configured something like this, trying to figure out why my ports were acting weird.

**Comment by zarvox** [comment]
My general feelings on this are the for the most part, predictability, limiting scope, and letting users connect the pieces are more useful if you live on a machine that is potentially shared with other services.  On the other hand, if you know you're the only thing running on this machine and this machine exists purely to run Sandstorm, autoconfiguring everything is probably the way to go.  I guess it's the difference between users treating Sandstorm as a service, vs. treating a Sandstorm instance as an appliance.

There's another question about how safe we feel letting node run as root, or at least start as root before binding 80 and 443 (maybe socket handoff can help us here?), and a second question about how we feel about letting the same process that runs a bunch of variable-quality JS also having your TLS keys mapped.

Sandstorm should probably continue to bind 6080 regardless, and require a reverse proxy of some sort if you want it to bind elsewhere.  In any event, regardless of which port it actually listens on, the Sandstorm backend will need to know where it's supposed to be found, though it can infer this from the `Host:` header or through explicit configuration.

I'm -1 on the idea of modifying `iptables` directly; if the user has any existing rules, this is very likely to do one of:

1. break their existing functionality, by virtue of changing the semantics of their chains
2. get lost in an upgrade/reboot because the rules aren't persistent

And then things you mentioned about inscrutability.

**Comment by paulproteus** [comment]
Yeah, the `iptables` idea isn't a real one. Pretend I never said it.

re: 80 + 443 + socket handoff: +1 to socket handoff, be that via Sandstorm supervisor or systemd.

**Comment by paulproteus** [comment]
re: 6080: Should it redirect to `:80`, if you reach the Sandstorm instance on `:6080`? I can see arguments either way.

**Comment by paulproteus** [comment]
I believe this is closed with #900 .
