### ISSUE TITLE
Integrate with unhosted apps

### ISSUE THREAD

**Issue by mitar** [sandstorm-io/sandstorm#508]
Reading about Sandstorm cannot make me stop thinking about concepts laid out in [unhosted apps](https://unhosted.org/book/). They are proposing the use of quite few standards like:
* [remoteStorag](https://remotestorage.io/)
* [webFinger](https://en.wikipedia.org/wiki/WebFinger)
* [DialBack](https://tools.ietf.org/id/draft-prodromou-dialback-00.txt)
* [WebIntents](http://webintents.org/)

And probably few more.

(BTW, why Sandstorm is not using [Open Web App manifest](https://marketplace.firefox.com/developers/docs/manifests) as its base?)

**Comment by kentonv** [comment]
Hi Mitar,

Sandstorm works very differently than these other platforms. It would take a while to enumerate everything, but our biggest difference from "unhosted" apps is that Sandstorm apps are hosted from your own server. Unhosted apps are still, ironically, hosted by the developer; it's just that the developer's domain only hosts the app code, while storage happens elsewhere. Unhosted apps have no sever-side component, which severely limits what they can do. For example, it would be rather difficult to build a real-time collaborative document editor in the unhosted model. Moreover, there's nothing stopping an unhosted app from phoning home to the developer's server and possibly spying on you, whereas a Sandstorm app would require your permission before it could do this.

It's possible that we could integrate somewhat with these apps through their various protocols, but our first priority is to support the most-commonly-used protocols on the web, like SMTP, XMPP, OAuth, etc.

It will probably be possible to build Sandstorm apps which use or implement some of the Unhosted protocols, without Sandstorm's help. For instance, I'd guess it would be possible to build a remoteStorage provider, so that unhosted apps can store to your Sandstorm server. But it's generally preferable for these apps to be packaged directly for Sandstorm, so that they can be hosted directly from your server and in our secure sandbox.

Regarding Open Web App Manifest, again, this is a standard designed for a completely different kind of platform: one where you host "web apps" directly from the developer's server. Sandstorm is based on installing a package file to your own server. The needs are very different, so trying to use Open Web App Manifest would probably create more confusion and problems than it would save.

Hope that helps.

**Comment by mitar** [comment]
Thanks! :-) Very useful to understand Sandstorm more.

**Comment by mitar** [comment]
(BTW, I really like [this project](https://github.com/dominictarr/r-edit), like [phoenix](https://github.com/ssbc/phoenix).)

**Comment by jmatsushita** [comment]
Sandstorm looks totally awesome but I'm not sure @michielbdejong or @pierreozoux would agree with your description of unhosted apps!

**Comment by kentonv** [comment]
I'm happy to be corrected if I've misunderstood anything!

**Comment by michielbdejong** [comment]
The thing is, we already had the name 'unhosted' for the project, and then retro-fitted that onto the thing we were working on two years later, which was 'statics-only web apps'. It's not entirely logical as a name, because the statics still need to be hosted. So I actually usually say 'client-side web apps' instead of 'unhosted web apps', to make it clearer. 'unhosted' is a confusing name because it makes people think of apps that live in a DHT or similar.

**Comment by paulproteus** [comment]
Hi @mitar and all,

I think that if we haven't progressed on this in a year, keeping it open as an issue isn't going to cause it to progress. The core team hasn't been focusing on integration with unhosted apps.

I would personally love to see unhosted apps and Sandstorm integrate well. Since it's not a core team priority, I think the best thing to do is to close this issue, so that passers-by know that we're not actively working on it.

My advice is:

- to generally discuss the topic, use the email list.

- for specific changes you want to see in Sandstorm, please open a ticket and/or pull request for them.

I think remoteStorage should be possible, or at least nearly possible, to implement as a Sandstorm app, which would go a long way toward this.
