### ISSUE TITLE
Admin panel never show after script install

### ISSUE THREAD

**Issue by pierreem** [sandstorm-io/sandstorm#537]
Hello, i've try sandstorm on a personal server, i used the install script and make all default choice, but the link for admin panel never respond to request (timeout)

i've try to use direct ip instead of sandcats solution, but it still dont work, i've try to restart sandstorm, restart server, change port, call update and remake every time a new token. nothing work.

The log aren't very usefull, and the --verbose option didn't show me anything. 

What can i do ?

**Comment by paulproteus** [comment]
Hi pierreem,

I wonder if you're having a firewall-related problem. Is this on Amazon EC2
that you're setting it up?

https://github.com/sandstorm-io/sandstorm/wiki/Self-hosting-FAQ talks about
"What ports does Sandstorm need open?", which might help, but we can
provide other links as needed.

**Comment by pierreem** [comment]
No firewall. I'ts a private server (no virtual) from kimsufi (cheap branch of OVH) and there is no firewall on it ! (except if i put one) 

I've installed an ubuntu 14.04 on it.

**Comment by kentonv** [comment]
Hi @pierreem,

If you SSH into your server and do:

    curl http://localhost:6080

Do you get a web page back? (Even an error page.) Or does it fail to connect?

**Comment by pierreem** [comment]
Connection refused on localhost web page ! curl failed to connect. 

spe@sandstorm:~$ sudo sandstorm status
Sandstorm is running; PID = 4634
spe@sandstorm:~$ curl http://localhost:6080
curl: (7) Failed to connect to localhost port 6080: Connection refused

**Comment by kentonv** [comment]
Weird. What does your `/opt/sandstorm/sandstorm.conf` look like?

**Comment by pierreem** [comment]
look like this:
SERVER_USER=sandstorm
PORT=6080
MONGO_PORT=6081
BIND_IP=37.187.116.13
BASE_URL=http://octip.sandcats.io:6080
WILDCARD_HOST=*.octip.sandcats.io:6080
UPDATE_CHANNEL=dev
ALLOW_DEV_ACCOUNTS=false
SANDCATS_BASE_DOMAIN=sandcats.io

it's a new server with a fresh install of ubuntu 14.04, so i can give you an ssh access to it if you want. (mail me through my github public email)

**Comment by dwrensha** [comment]
Hm. Yeah, localhost and local.sandstorm.io will not work with that config because the BIND_IP is neither `127.0.0.1` nor `0.0.0.0`. However, if you only interact with your server through octip.sandcats.io then this shouldn't be a problem.

I can successfully visit `http://octip.sandcats.io:6080/admin/` and it gives me the expected "You are not logged in as admin and there isn't a valid token specified" error.

@pierreem, when you do `sandstorm admin-token`, you should get something that looks like:

```
Generated new admin token.

Please proceed to http://<HOST>/admin/settings/<TOKEN>
...
```
What does it display for HOST in your case?

**Comment by pierreem** [comment]
Ok, it's working now, but i didn't do anything .... I didn't even connect to the server by ssh since my last try ! 
I will put the issue in resolve, since it'is... but ... 

(for the ip things, originally it was a 0.0.0.0, but i've changed it to server ip* when searching a solution)
*i've update my comment below.

host is correct: octip.sandcats.io and was already correct before.

**Comment by antoniusblock666** [comment]
I'm getting exactly the same issue. I'm using Ubuntu server on a virtualbox instance with Bridged network.

When I enter the IP address of the server into a browser I get the "Sandstorm static publishing needs further configuration" page. But when I try to go to xxx.sandacts.io I just get a timeout error.

Any idea wht the issue could be?

**Comment by paulproteus** [comment]
Hi @antoniusblock666 , you probably have a situation where the sandcats IP address is the server's external/global IP, but you don't have the corresponding NAT/port-forwarding rules set up. Since the IP-address way is reachable, you can try the xip.io wildcard service, see: https://docs.sandstorm.io/en/latest/administering/faq/#how-do-i-use-sandstorm-with-an-internal-ip-address
