### ISSUE TITLE
"Vagrant up" should install linux deps automatically inside the new VM

### ISSUE THREAD

**Issue by onceuponatimeforever** [sandstorm-io/sandstorm#544]
I expect that when I first vagrant ssh into the new VM, I should already be able to have git, build-essential, and g++ installed in there. `./run-dev.sh` expects the latter 2 dependencies.

**Comment by kentonv** [comment]
The current vagrantfile is meant more for app development or playing around with Sandstorm, but not really for hacking on Sandstorm itself. We could conceivably provide a separate Vagrantfile (or a separate box name within the current Vagrantfile) for that purpose.

**Comment by paulproteus** [comment]
My vague opinion here is that multiple Vagrant boxes is a fairly high cognitive burden, and doubly so since it affects what commands people run (`vagrant ssh` vs `vagrant ssh dev`, if the new box is called `dev`), so I would propose:

* The Vagrant sandstorm setup should use `SERVER_USER=vagrant` so that the chown stuff isn't required.
* The dependencies are not auto-installed, but we patch `run-dev.sh` so that it detects missing dependencies and tells the user how to install them.

This seems to me to a good way to accommodate both kinds of plausible users of the Vagrantfile -- (1) those trying out Sandstorm before running it on a server (which I've recommended to e.g. Yoz) and (2a) those who want to hack on the Sandstorm shell. If your'e in a category I'll call "(2b) Hacking on the Sandstorm C++, etc." then I think we can document in https://github.com/sandstorm-io/sandstorm/wiki/Install-Sandstorm-via-Vagrant what you should do.

@onceuponatimeforever would you be OK if `run-dev.sh` explained very clearly what to run, to get those depenencies? (Alternately, `run-dev.sh` could detect that this is the Vagrant box, and could then `sudo apt-get install` what it needs, but that seems excessively magical.)

I figure if it's easy to accommodate those in 1 and 2a, and 2b people need to read some docs, that is a good situation.

@kentonv +1 on the above idea generally, and am I right that adjusting SERVER_USER would be enough to make `run-dev.sh` for the shell work properly?

I think this also would reasonably-cleanly handle the issues that @diracdeltas was running into earlier with understanding how to use the Vagrant box to hack on Sandstorm. I'll have to spend some time reading through https://github.com/sandstorm-io/sandstorm/issues/263 and https://github.com/sandstorm-io/sandstorm/pull/264 to make totally sure, though.

**Comment by kentonv** [comment]
Adjusting SERVER_USER sounds like a reasonable thing to do. Off the top of my head, it seems like it should make `run-dev.sh` work, though someone should actually try it. It seems to me that the bigger problem is getting the dependencies installed and documenting how to use Vagrant for this.

**Comment by paulproteus** [comment]
Hi all, especially @onceuponatimeforever ,

For now, I've "closed" this by making the Vagrantfile link to documentation on how to install those dependencies. I think this is a reasonable-enough way forward, even though it doesn't directly address the issue. Those instructions are slightly manual, but also they are the same instructions we ask everyone else to follow, which means that we won't let them get out of sync with reality.

You can read that doc here: https://github.com/sandstorm-io/sandstorm/wiki/Using-the-Vagrantfile

I believe this change addresses the spirit of the issue, which is the former undiscoverability of how to successfully contribute changes to Sandstorm given only the `Vagrantfile`.
