### ISSUE TITLE
Feature request: Make login token expiration interval configurable

### ISSUE THREAD

**Issue by isislovecruft** [sandstorm-io/sandstorm#577]
Hello wonderful Sandstorm people!

Some of the Tor people using https://storm.torproject.org are wondering if you guys would consider taking a patch to increase the interval by which an email login token expires. I imagine this would best be done via a configuration file option, so that it defaults to the normal 15 minute interval if the option is left unspecified.

Is this a patch which you might consider taking?

Thanks!

**Comment by paulproteus** [comment]
@kentonv I'm curious what your take is.

My feeling here is that it's OK if people configure it to be longer than 15 minutes, but if it starts getting into many many hours or days, the tokens become something of a risk. We could call the option e.g.

`BE_VERY_CAREFUL_EMAIL_TOKEN_VALIDITY_IN_MINUTES`

to cue people into thinking it's important to think hard about what you set this to, or we could hard-code a max (2 hours?) in the source plus let people configure `EMAIL_TOKEN_VALIDITY_IN_MINUTES`, and display an error somewhere if they set it to higher than that max.

Or we could make the duration configurable in the admin dashboard -- then we can provide feedback via the UI if the user sets it above some reasonable amount (2 hours?).

Of all these, I think I'd go with the lazy-ish thing of letting people configure this themselves and warning them in the docs that they really ought to be careful.

(p.s. naturally feel free to pick different names for the actual config option than what I named above)

**Comment by kentonv** [comment]
Hi Isis,

Could you describe your motivation for this?

Generally the idea behind the email login UI is that the user types in their own email address, and then immediately goes and clicks the link in the email. It's kind of like if you never remembered your password and instead always logged into web sites by doing a password reset. I'm having trouble seeing where it would be necessary to have an expiration more than 15 minutes (or even 5 minutes), but I'm happy to increase it if there is a good reason. I think we would want to increase it for everyone rather than make it configurable, unless there is something that makes your server unique here.

We have seen some people misinterpret the email login UI as being an invite system. They then type in other people's email addresses, who takes a while to see the email and click through, and often then find the token is expired. This isn't the intended use of the UI, though -- we need to find a way to make this clearer. The best way to "invite" someone is to send them an email manually with a link back to the server, where they can then go through the login flow themselves. Or, if you want to give people the ability to install apps and make grains, use the "send invites" tab in the admin panel, which sends tokens that do not expire.

**Comment by ocdtrekkie** [comment]
I am leaning in the direction of closing this one? The original requestor did not respond with regards to the need, and I think login tokens should definitely be very ethereal. 15 minutes is pretty standard for most emailed and texted login tokens on other sites as well.

So this probably falls into "we should need a really good reason/a lot of demand to add this option", and I don't think the Sandstorm instance linked above still exists.

**Comment by zenhack** [comment]
Agree; in lieu of a specific use case we should just close this.
