### ISSUE TITLE
Use A HREF in grain links, in shell

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#600]
### Steps to reproduce

* Log into a Sandstorm (e.g. the Demo)

* Create two grains

### Expected behavior

* Right-click, "open in new tab" should work with the links to the grains

### Actual behavior

* Right clicking navigates the current page away from the grain list, which is sad because I now to open a new tab with the grain list to open a second thing from the grain list.

### Screenshots & proposal

![no-links](https://cloud.githubusercontent.com/assets/25457/8753943/a496c5f4-2c74-11e5-9721-57f77b259d60.png)

I propose these HTML elements should be `A` tags, so that the browser's link UI can apply.

**Comment by paulproteus** [comment]
@jparyani and/or @kentonv - is there a reason this is the way it is right now? If no reason, then I can see about implementing this.

**Comment by kentonv** [comment]
I don't observe the problem where right-clicking navigates. For me it just opens the usual right-click menu, but with no option for "open in new tab" since it doesn't recognize the table row as a link.

I agree it would be nice to make it an actual `<a>` element. Note that the's a bit of a complication in that we handle the click event on the `<tr>`, and you can't really replace a `<tr>` with an `<a>` directly. You could perhaps make just the title cell contain `<a>` elements, and hope that people don't right-click in the date cell. Or you could make them both be `<a>` elements, though that feels weird.

Remember to specify style `display: block; width: 100%; height: 100%;" so that the `<a>` elements actually cover the entire cell. (Hmm, though I wonder if width/height 100% has weird effects inside a table, since the size of the table cells is usually based on content. Might need to play with it...)

**Comment by paulproteus** [comment]
+1!

**Comment by kpreid** [comment]
In my opinion, making all cells be `<a>` elements, styled to fill the area of the cell, is the best of a not-good set of options.

(Another option not yet mentioned is to not use `<table>` but some other structure, so that an `<a>` can contain the entire row. CSS can be used to apply table-type layout.)

**Comment by zarvox** [comment]
I think we can call this one fixed.  The new grainlist *does* use `<a>` elements, so you can right-click the links and open in a new tab.  Additionally, multigrain makes it easier to have multiple documents open at once.
