### ISSUE TITLE
Notifications & Account Info cannot be closed on mobile view

### ISSUE THREAD

**Issue by JamborJan** [sandstorm-io/sandstorm#608]
Tested with iOS 8.4 & Sandstorm 0.98

When you tab on notifications or your login name the "pop up" styled info box opens. This cannot be closed. Also tapping in the background or besides the info box doesn't close it.

![image2](https://cloud.githubusercontent.com/assets/7508960/8793883/14ebcfc4-2f7d-11e5-861e-9742d510b790.png)
![image1](https://cloud.githubusercontent.com/assets/7508960/8793884/14f03730-2f7d-11e5-8b99-cc0e20a41cc5.png)

**Comment by kentonv** [comment]
Apparently mobile Safari (unlike any other browser or even desktop Safari) uses some sort of heuristics to decide if an element is really supposed to be clickable and drops the events on the floor rather than delivering them otherwise. I'll add a close button to the corner of the popups as an explicit `<button>` element, which it should understand...
