### ISSUE TITLE
Cannot create subprocess in iPython (Oasis)

### ISSUE THREAD

**Issue by bqpd** [sandstorm-io/sandstorm#612]
Attempts to create a subprocess (e.g. via `subprocess.Popen`) raise `OSError: [Errno 2] No such file or directory`.

Weirdly, `os.popen(foo)` works for `"echo $PATH"` but finds no `"ls"` command, instead logging `sh: 1: ls: not found`.

The context here is that I want to install/update a few python packages; from other Sandstorm docs online it seems that the right way to do this is to repackage, but I figured that the OSError deserved mention since `subprocess.Popen` seems to work [here](https://gist.github.com/jparyani/9946050#file-sandstorm-ipynb), but not on my grain.

(Unrelatedly, Sandstorm is amazing and inspiring. Many thanks!)

**Comment by jparyani** [comment]
This is because `ls` doesn't exist inside the IPython Sandstorm package. Try again with `sh` and it should work.

Also, it seems `python` is somehow no longer in the `$PATH`. If you really need it, then `/opt/virtualenv/notebook-environment2/bin/python` should work instead, but is obviously not ideal. I'll fix it in the next release.

**Comment by kentonv** [comment]
Can one of you re-file this on the Sandstorm-iPython package issue tracker? Thanks.

**Comment by jparyani** [comment]
Done. https://github.com/jparyani/ipython/issues/3
