### ISSUE TITLE
Sandstom outgoing HTTPS request failed.

### ISSUE THREAD

**Issue by sunilsrikumar** [sandstorm-io/sandstorm#622]
Post instllation of Jetpack plugin in WordPress, the system doen't allow jetpack to connect to wordpress.com for registration. 

The possible reason could be - Sandstorm server is not supporting outgoing HTTPS request. Can you please check.

Sunil

**Comment by kentonv** [comment]
Hi Sunil,

Per [Sandstorm's security model](https://docs.sandstorm.io/en/latest/developing/security-practices/), apps are not given network access. They must use Sandstorm-provided APIs to request access to specific resources in order to do things like make outgoing HTTP requests. Unfortunately, Sandstorm-unaware Wordpress plugins that want to make outgoing requests won't work.

In general, we haven't put a lot of work into making Wordpress work well on Sandstorm as it's a very big app and we think that Wordpress hosting is well-served already. In general I'd recommend using Wordpress on Sandstorm only for fairly simple static sites for now.

With that said, feel free to file bugs/feature requests on the Wordpress Sandstorm project:

https://github.com/dwrensha/wordpress-sandstorm
