### ISSUE TITLE
Question: Is it possible to use sandstrom to have something like Bitnami.com?

### ISSUE THREAD

**Issue by diff-** [sandstorm-io/sandstorm#709]
1. I mean a website that allow users to install an app like Wordpress and have an individual dashboard that makes it possible to set custom domain, pay billing, etc.

2. I sandstorm like [Juju](juju.ubuntu.com)?

**Comment by paulproteus** [comment]
Hi @diff- ,

Thanks for asking. Let me answer these in order.

1. Sandstorm has some hooks that should make it possible for anyone to build custom billing code on top of it. However, I don't think they're well-documented. We (the company behind Sandstorm) are just in the process of writing them and finalizing them, so apologies in advance for their status. Our hosted service is sometimes called "Oasis" and sometimes called "Blackrock" so if you search `git log` for the text `blackrock` you should find all the related code.

2. Sandstorm isn't really a lot like Juju, as far as I can tell. Sandstorm is designed to run on one machine, and runs each app instance isolated from data from other app instances, whereas Juju is about connecting lots of different servers to run large-scale applications.

I hope you'll try the demo, and/or install it on your own machine, to get more of a sense of it.

I'm going to close this for now, since (if I understand correctly) you're not filing a bug against the code. If you do have more questions, feel free to leave a comment here or email support@sandstorm.io!

**Comment by paulproteus** [comment]
Note that we do have some code that is separate from Sandstorm, that is part of "blackrock", that is not open source, related to scaling Sandstorm to run on multiple machines. Depending on the hosting service you want to run, you might not need it.

https://blog.sandstorm.io/news/2015-01-15-sandstorm-1.3M-seed-round-pay-it-forward.html discusses that, if it's helpful.

**Comment by diff-** [comment]
> Our hosted service is sometimes called "Oasis"

Will you release your billing plugin on Oasis when go to the final release: the stable version? 

Note: I want to use it as a SaaS to make it possible for my customers to get their wordpress/[gost](gost.org) install automatically when they order.

**Comment by kentonv** [comment]
@diff- If you're interested in running a paid Sandstorm host (where users can install any apps they want), we plan to enable that by selling Blackrock (the code that runs Oasis). We currently don't plan to make Blackrock open source, since we need to make money somehow. :) See: https://blog.sandstorm.io/news/2015-01-15-sandstorm-1.3M-seed-round-pay-it-forward.html

Unfortunately Blackrock is not ready for sale yet; still lots of work to do. Probably some time in 2016. Please email sales@sandstorm.io if you're interested.
