### ISSUE TITLE
Running sandstorm admin-token as non-privileged user crashes

### ISSUE THREAD

**Issue by rngadam** [sandstorm-io/sandstorm#711]
Should probably offer a user-readable error "Run as root user or under sudo"

```
$ sandstorm admin-token
*** Uncaught exception ***
sandstorm/util.c++:47: failed: open(name.cStr(), flags, mode): Permission denied; name = ../var/sandstorm/adminToken
stack: 0x541e08 0x541d89 0x541d7a 0x5143a1 0x515025
```

**Comment by paulproteus** [comment]
Hi @rngadam,

Thanks for filing this. You're absolutely right.

I'm going to label this as `bite-sized` since it should be a relatively straightforward task for a contributor interested in tackling a Sandstorm C++ bug.

The core dev team would also like to see this fixed, and will fix it, in the fullness of time, as it's a pretty annoying command line usability issue.

**Comment by dwrensha** [comment]
I think the solution here is to have a check at the very beginning of the `sandstorm` executable that exits with an error message is the user is neither root nor part of the SERVER_USER group.

**Comment by paulproteus** [comment]
As a note to self/other bug fixers:

It looks like `adminToken()` in `run-bundle.c++` has a permissions issue, and it's "just" a matter of avoiding the exception, and doesn't involve any Cap'n Proto. (I'm always on the hunt for "easy" bugs that involve Cap'n Proto, since I periodically hear from prospective new contributors that they like Cap'n Proto.)

@dwrensha 's proposed fix seems great to me.

**Comment by mrdomino** [comment]
I started a fix for this last night. The approach I thought to take was to check `access("../var/sandstorm", W_OK)` and print an informative error if it failed with EACCES. I could easily be convinced that we should instead do the membership test via parsing id like we currently do to discover SERVER_USER's group.

I was figuring on doing the check somewhere near or in changeToInstallDir -- maybe rename it to changeToInstallDirAndCheckAccess or something. If we want to parse id output then I guess readConfig or after would be a better place for it, so we can compare against config.uids.

**Comment by mrdomino** [comment]
Went with a totally different approach, just embedding the fix in readConfig.
