### ISSUE TITLE
Installation complete. Click "My Files" to create a new file with this app.

### ISSUE THREAD

**Issue by ocdtrekkie** [sandstorm-io/sandstorm#72]
App Installed page still refers to old file picker menu. In this case, the only clearly presented choice is "Upgrade Files". I suggest perhaps a smaller link below the upgrade files button that says "Do not upgrade files".

In this case, I am updating an app, but do not want to update my files. It is not clear where I should go from here. (If I, you know, don't already know my way around Sandstorm.)

Actually, there's a general point about it saying App Installed instead of App Upgraded, and that it really shouldn't be telling me how to create new files with this app on an upgrade page anyways.

![myfilesmenu](https://cloud.githubusercontent.com/assets/4399499/3862695/7e300d4c-1f3e-11e4-9b6c-3e1396b56431.png)

**Comment by paulproteus** [comment]
Hey @ocdtrekkie -- thanks for filing this.

Basically, I totally agree with you. Can I possibly interest you in helping fix this?

I think it'd be a pretty straightforward HTML/CSS fix, and I'd be happy to remote-pair-program with you on it if that would help. I'd also be very happy to answer any questions or provide links to docs as needed.

**Comment by paulproteus** [comment]
Note that to do "straightforward HTML fix"es, you do need a working development environment, which involves installing Meteor. (One day, we can have a Sandstorm app that exists for submitting pull requests against Sandstorm???)

**Comment by ocdtrekkie** [comment]
Notes on fixing this in case I don't get to figuring out how to do it, or so I have reference for when I give it a shot:

https://github.com/sandstorm-io/sandstorm/blob/master/shell/client/shell.html#L309 is where the link to not upgrade files should be added, after a line break.

https://github.com/sandstorm-io/sandstorm/blob/master/shell/shared/install.js#L357-L358 are representative of the routing instructions we need to trigger, to act like a completed install and go to the page in question.

While at it, the other aforementioned issue, the My Files sentence at https://github.com/sandstorm-io/sandstorm/blob/master/shell/client/shell.html#L300 can simply be deleted, and the `else` at https://github.com/sandstorm-io/sandstorm/blob/master/shell/client/shell.html#L310-L311 should probably be axed because `my-files-arrow` pointed to the old file picker which no longer exists, so that arrow should never ever ever show.

**Comment by ocdtrekkie** [comment]
@paulproteus I am very sure I cannot figure out how to test this on my client. (I looked at the 'Hacking on the shell' instructions, but I can't even find the shell folder I'm supposed to cd to. :/)

I wrote proposed changes here: https://github.com/ocdtrekkie/sandstorm/tree/patch-2 that are completely untested and prone to failure due to my lack of any idea what I am doing. Can you test and/or tell me what I did horribly wrong?

**Comment by paulproteus** [comment]
Hi Jake! Thanks for submitting this! Sorry it took me a while to get to
reading through it.

You had asked for feedback, so here goes:

* It looks like this change removes the 'Click "My Files"...' message, even
if this is a new installation of an app. You might want to instead wrap the
'Click "My Files"...' message in a {{#if ! hasNewerVersion && !
hasOlderVersion}} conditional, so that it appears for a fresh installation
of an app. Note that the above is *also* untested by me!

* It's usually considered icky to use <BR> tags, since they can be hard to
control with CSS. (I don't know that Sandstorm has a HTML/CSS style guide,
but presumably we should gain one so I can have a place to store micro tips
like this.) So I recommend using a paragraph tag for the new ""Do not
upgrade files" message.

* I think the Javascript changes you wrote look reasonable. I haven't
manually tested them; I'll do that next. I find it easier to review changes
like this if the JS changes are in the same commit as the HTML changes, but
the separation that you have is OK.

* I would suggest using a git commit log message that explains more clearly
what the change is, rather than simply the purpose of it (although the
purpose is essential -- thank you for writing that).
https://github.com/erlang/otp/wiki/Writing-good-commit-messages has some
tips that I generally like.

* Big +1 for setting 'selectedApp' the JS. I would encourage you to take
the existing code that already does basically that thing, and create a
helper Javascript function, something like:

var jumpToApp(appId) {
    check(appId, String);
    Session.set("selectedApp", appId);
    Router.go("root", {}, {replaceState: true;}
};

and move the comments from around line 354 into this helper function, and
then you can adjust other places that have the same copy-pasta to call into
your new function instead.

* One good way to get feedback is to submit things as a pull request, even
if you don't need us to necessarily merge the changes right away. You can
provide a title for the pull request that indicates that like, "(Do not
merge - feedback only!) Fix #72". That way, despite my slowness, others
might have been more likely to see this and review it. (Though if you did
it this way intentionally to ensure semi-private feedback, I can understand
that.)

That's feedback from reading the branch, not from running it. The only real
show-stopper is the first one, but I might find other important issues
after testing it. You said you were having trouble testing it; why is that?

Written from a Brown Line train to Loop,

Asheesh.

**Comment by ocdtrekkie** [comment]
- The reason I am removing the "Click My Files" instruction thing is because "My Files" is a menu that no longer exists! It is from back when the files were a drop-down, rather than the columnar structure we have now.

- I can definitely switch the <br> to a <p>, I was trying to avoid a lot of spacing between them, but that is good feedback.

- Apologies on awful separation. GitHub web editor allows single file edit commits only. I couldn't get the "Hacking on the Shell" instructions figured out, so all of this is totally untested right now. (Maybe you can show me what I need to do tonight?) Which is also why I was hesitant to go right ahead and make a PR for it.

- The helper function makes sense, but you will find me very hesitant to go rearranging other people's code, because I rarely admit to knowing what I'm doing.

**Comment by paulproteus** [comment]
BTW @zarvox , this might make a good starting project for hacking on Meteor stuff.

**Comment by ocdtrekkie** [comment]
Asheesh, you were going to help me fix this one! :P

**Comment by zarvox** [comment]
This is obsoleted by the new install flow, which drops you straight into the app details page once you've confirmed installation.

**Comment by ocdtrekkie** [comment]
@zarvox Is this part fixed? "App Installed page still refers to old file picker menu. In this case, the only clearly presented choice is "Upgrade Files". I suggest perhaps a smaller link below the upgrade files button that says "Do not upgrade files"."

**Comment by paulproteus** [comment]
Jake, I guess Drew helped you fix it instead!

(Sorry Jake that I didn't have bandwidth for it! Glad it got resolved one
way or another.)

**Comment by zarvox** [comment]
@ocdtrekkie That blocking aspect of that choice is removed - you simply get redirected to the app details page after confirming installation.  "Upgrade files" is now just a button shown on the app details page, and if you don't want to upgrade, you can still access your grains and create new ones from that page, which I think is more helpful than a "Don't upgrade" button.

I hope that's a reasonable compromise between the dual goals of making it hard for users to be confused down the road about grain versions vs. app versions by dismissing that message, while making it clear that you can continue using everything as before and don't have to upgrade your grains now or even decide immediately whether you want to or not. :)

**Comment by ocdtrekkie** [comment]
@zarvox But then will people be encouraged to update their grains clearly, which most users should, in fact, do?

**Comment by ocdtrekkie** [comment]
Arguably, if the setup is as described, it may be ideal for neither case. For common users, we want to avoid them getting stuck thinking they have bugs/issues with apps, because they didn't upgrade their grains.

On the advanced side, an "upgrade grains" button doesn't do me a lot of good either, because I probably want to upgrade just one grain to see if it works well/is a pleasing update. (And the ability to downgrade is equally key, of course.)

**Comment by zarvox** [comment]
I appreciate your dedication to making sure that our UX makes as much sense as possible!

The common case will be users seeing that there are updates in the notifications menu, and clicking "Apply Updates" there, which also upgrades all of the grains.  Only manual installs of newer versions of apps that you have older grains still kicking around for will trigger this UI, and I think it behaves reasonably (though perhaps not optimally) in those scenarios.  At the very least, you will always be able to see that there is a version mismatch upon returning to this page, even if you can't take appropriate action yet.  This was not the case before the recent updates - you had to make the decision at upgrade time, we only gave you half the appropriate buttons, and you couldn't review your choice later without going through the install workflow again. :P

I'd venture a guess that only people who will ever see the button/prompt either:

1. are testing specific versions of an app,
2. are testing upgrade behavior, or
3. have disabled app update notifications

I'm open to changing the behavior here when we add support for doing individual/aggregate actions on the grain list, though.  I don't want to overwhelm users with irrelevant information (most users will have all their grains at the same version as the latest app release version), but I do want to support acceptance testing workflows like the one you've described.  That becomes easier when your actions are on individual grains rather than the broad strokes we currently have.

FWIW, I didn't mean to dismiss your use case by closing the ticket - I'm just going through a bunch of older issues and attempting to close ones that have been either fixed or obsoleted by recent changes (which I'm sure you're getting emails for ;) ).  Feel free to reopen this bug (and perhaps retitle, to make it clearer what you're looking for?) if you like, or maybe open a new one with some of the crystallized ideas from this thread extracted. :)

**Comment by ocdtrekkie** [comment]
No, I agree this ticket should be closed. The UI the ticket was filed against is almost wholly different than this latter discussion. :)
