### ISSUE TITLE
App store admin setting

### ISSUE THREAD

**Issue by ocdtrekkie** [sandstorm-io/sandstorm#722]
It may be a good time to turn this into a setting, so that people hosting who want to direct to a specific app list (especially an internal organization one) or something similar can set where the Install button goes. It should be under "Advanced Settings" on the admin panel.

The expected UI should probably be a setting in the admin panel to enter an alternate address, **as well as a one-button press to restore it to default**. If the address is the default address, the software should know that, so that if you change the default upstream, the setting is automatically updated. (For instance, if mine says sandstorm.io/apps, and you change it over to apps.sandstorm.io, it should know to update itself. However, if I set it to apps.mycompanyintranet.net, it should preserve the custom setting.)

**Comment by zarvox** [comment]
Slightly different suggestion preserving the goals and character of this request:

Sandstorm should support multiple app indices, and you should be able to remove the default app index if you so choose.

In the enterprise use case, you probably want to be able to install internal line-of-business apps that may not be offered on the App Market.  You probably still want to be able to use e.g. Ethercalc and many of the other apps available on the market, without having to run a complete mirror of all the app market content (though of course, you could do that too if you wanted!).

Maybe some day there will be third-party markets, and maybe they'd have separate indices with no curation.  Maybe you want to run an index with just some prerelease apps for your friends for testing.

To make this work cleanly for end users, we'd have to offer a browse-and-install flow in the Sandstorm shell itself.  Sandstorm could pull the app index manifests from each app index (which it already needs to do to discover app updates), and present some UI in the shell itself rather than sending you to apps.sandstorm.io, integrating the view and search for apps across all the different indices.  This would make for a smooth, cohesive installation experience for end users, regardless of whose apps they're running and where the SPKs are published.

Other thoughts:

* When you install an app, I'd expect it to receive updates from the same index that it was originally installed
* I'm not sure exactly how reviews are implemented and if they're in the app index or if we'd have to query those separately.  Perhaps the number-uniques-per-bucket of +2..-2 reviews wind up in the index?  (I should look at the JSON blob...)

**Comment by ocdtrekkie** [comment]
@zarvox I agree, though my short-term priority was ensuring that everyone has the option to move away from any service tie-in at any time. (As a rule of thumb, I feel Sandstorm should never hardcode a web address into the code, except for "here's the default".)

#931 addresses this satisfactorily for now.

Another thing is, that Sandstorm.io may want the existing App Market to support private app distribution as a service you offer. So that may be an alternative option to multiple app indices as well. If a corporation was comfortable with allowing open install of App Market apps, they are probably okay listing their internal apps with a whitelist to only allow their server to install them or something.

If someone wants to definitely internally handle app install, I'd expect them to either fully mirror the App Market apps they wish to allow, or include direct install links to the SPKs hosted on the App Market within their own app list page.

**Comment by ocdtrekkie** [comment]
Either the solution of listing private apps on the public App Market site, or listing public apps on a private app list site would both be viable options for organization-managed Sandstorm installs, and both would keep the Sandstorm platform components for install and auto-update a bit 'simpler'.

I wouldn't be like -1 on it, I'd be more like -0, I'm just not sure if it'd add enough value to justify it. (And there's other install features I feel need much more complexity: Users need more control over which documents use which appVersions, and being able to restore a backup with an older appVersion or whatever.)

**Comment by ocdtrekkie** [comment]
This was addressed satisfactorily.
