### ISSUE TITLE
Adjustments to share icon styling

### ISSUE THREAD

**Issue by neynah** [sandstorm-io/sandstorm#861]
1. Purple BG made it more difficult for users to find it (in user testing). Possibly because it is styled differently than the rest of the UI. I think we should remove the purple.

2. Current share icon is easily confused with social media sharing that is common in other interfaces (especially on mobile). Should be replaced with a person icon, perhaps with a plus sign.

![share-icon-edit1](https://cloud.githubusercontent.com/assets/855341/9777791/0bab7ff0-571d-11e5-84d7-ee30e41c6f40.png)

**Comment by kentonv** [comment]
Oh wow. It only just occurred to me that people likely have learned to tune out "share" because it usually means "tweet about us".

**Comment by zarvox** [comment]
Perhaps "Share Access" is clearer?  It's more text than I'd like for a tool button, though.

For what it's worth, Google Docs' "Share" button communicates a couple of bits of state about what the current document visibility is, which seems helpful.  They use a lock icon if you allow sharing for that document only by identity, a person head atop a chain link if you allow sharing by link or identity, and a globe if you have made the document public.

**Comment by neynah** [comment]
"Share Access" does not seem like too much additional text-if it communicates better I think it'd be worth it. I also like the different icons communicating different state. Is that difficult to implement?

**Comment by zarvox** [comment]
Well, we don't currently have a concept of flexible per-document visibility policy - the current state of things is that all Sandstorm grains use the second state I described (link sharing allowed, but not fully public).  Since we currently don't have a fully-implemented share-by-identity, and we don't support making grains "public" in the sense that gdocs does, their specific approach to icons doesn't quite fit for Sandstorm, at least yet.

Making the UI show different icons depending on if sharing tokens exist or not should be fairly straightforward, provided you know what icon you want to show under what conditions and they're all the same size on the page.

**Comment by kentonv** [comment]
I think icons for "you own this and haven't shared this", "you own this and have shared it", and "this is someone else's grain shared with you" make sense.

Some day we may have a notion of "public" in the form of generating short links, or something.

**Comment by zarvox** [comment]
+1 to all this.

**Comment by paulproteus** [comment]
@neynah says this is closed, so I am going to mark it as such!
