### ISSUE TITLE
Design for an individual app's page (new UI)

### ISSUE THREAD

**Issue by neynah** [sandstorm-io/sandstorm#873]
This is the page you'll see after you click on an app under "Apps" tab.

1st draft for desktop and mobile. @zarvox 

1. Am I missing anything?
2. Thoughts on the subtle highlight of the "Create new..."?

![app-page1](https://cloud.githubusercontent.com/assets/855341/9804647/dd8fc946-57e4-11e5-8181-d47f8914437a.png)
![app-page1-mobile1](https://cloud.githubusercontent.com/assets/855341/9804648/dd946f78-57e4-11e5-9e17-67a0cc0c5acd.png)

**Comment by ocdtrekkie** [comment]
Huge +1 on this. I've wanted this info in the UI directly for a while. 

We should have a link to the source repository if it's listed in the manifest so people can report bugs.

**Comment by neynah** [comment]
+1 on that idea ocdtrekkie.

**Comment by kentonv** [comment]
Looks pretty good.

We will probably need an intermediate view between the mobile and wide views, since I suspect at 900px (where "desktop mode" usually starts) the design as you have it won't fit. I think what we can do here is basically take the layout of the metadata from the mobile version but still have the big icon on the left.

I just had a thought: instead of "verified", maybe we should say "signed by". This more literally states what the information means, and I think helps clarify the case where the author and the packager are different people. Of course it would be the packager signing the package.

Speaking of which, we'll need a design variant for the case where the author and packager are different people. We'll need to show both names ("Packaged by:" and "Upstream author:"). I wonder if we should hide the profile picture in this case, since it seems odd to show the packager's picture when they aren't the main author.

One more note: In addition to github and twitter we should link directly to the user's keybase profile. The key fingerprint can link there, but I think we should display their keybase profile name too, and it should probably be presented as a separate item from the fingerprint, in the same style as github and twitter. Maybe we should ask Keybase for a logo to use...

**Comment by neynah** [comment]
Ideally I should be making mock-ups for mobile, wide, and intermediate as you suggest. Especially in the case where the sidebar will be expanded there will also be less width for content.

I'm curious as to what value the author/packager profile picture adds versus just having their name & username.

**Comment by zarvox** [comment]
Looks very attractive.

"Distributed by" might be a less-jargony way to say "signed by"/"verified".

Do we actually have pictures for packages?  Or is this assuming that we'll piggyback on e.g. GitHub or someone else's profile pictures?  There's a potential infoleak if we're fetching those assets.

Prefer mixed-case for the Uninstall button.  All caps are less readable.

**Comment by paulproteus** [comment]
In this mockup, UNINSTALL is vastly more prominent than NEW. I would prefer
if uninstall were (e.g) at the bottom of the page, and NEW were somewhere
big and easy to find.

FWIW.

**Comment by neynah** [comment]
I agree with the mixed-case- it's a terrible habit I have.

In the mobile view, install appears to be the most prominent (I should change that). In the wide view I imagine it's less prominent than creating a new grain but I'm not entirely sure.

**Comment by kentonv** [comment]
@zarvox "Distributed by" does not express the fact that we've checked signatures, which I think is the most important thing to express here.

The profile picture (and name) would come from Keybase.

**Comment by ocdtrekkie** [comment]
I am iffy on the value of pulling profile pictures from Keybase. I'd rather just... not. What if I like an app but someone set their Keybase profile picture to something I find distasteful? I don't feel it adds value. And while I'm happy to link to things outside of Sandstorm, I don't want to get into the habit of having Sandstorm servers pull assets from specific other web servers.

Another good question, tied into the eventual ability to detect and offer updates: There should probably be a link to the app market page somewhere here. (Though this brings up #722 where we cannot/shouldn't assume the server admin wants to be hooked up to the official app market service. Though we can possibly assume/require third party app lists should definitely accept http(s)://$APP_MARKET_DOMAIN/app/$APP_ID)

**Comment by ocdtrekkie** [comment]
Out of curiosity, is it worth that much UI space to list out the key and all of the verified methods included? Or could we list the verified author name, specify something like "Keybase verified" or something, and have some sort of expandable thing for if you want all of those details? Especially in the mobile UI, I feel it's a lot of space usage for something the user will either never care about and never check (let's be honest), or check once.

**Comment by paulproteus** [comment]
If I understand what Jake's saying, I agree.

I would love to see the app's technical & author details minimized when I'm
thinking "I need a new EtherCalc sheet".

To me, I'll be mostly on this page to either find data created with this
app ("open a spreadsheet I looked at yesterday") or create a new grain
("make a new spreadsheet"). I'd love to see a design that emphasizes those
use cases and minimizes app info. To put it a different way, we're putting
app authorship & version number a high degree of visibility, much higher
than e.g. Google Docs, or Android apps, or Debian packages. I'd rather see
that info on a separate screen, or (for example) on the same page as
"Uninstall", behind a link like "Info & uninstall", or at least most of it
"below the fold".


I also am OK with anything, including following Nena's and/or Kenton's
hunches, so long as we do user tests to make sure it's usable. As always,
I'm just one person spouting untested UI ideas, so you should not take what
I say too seriously.

**Comment by neynah** [comment]
For the verified section I would defer to Kenton as I don't think I fully understand/appreciate the value of those details so it's hard for me to say. From my understanding this information is valuable during the install and then again only when someone is specifically looking for it.

I do agree that it currently takes up more space than is reasonable. If space is an issue and we still want to display this section we could either:

1) not display the usernames for each icon
2) perhaps just make the text smaller, or
3) have an expandable section as @ocdtrekkie suggests.

I think I prefer option 1, but 3 if the usernames should be displayed.

Also if we decide to add a link to the source repository then does it also make sense to add a link to the app's page on the App Market? e.g. https://apps.sandstorm.io/app/a0n6hwm32zjsrzes8gnjg734dh6jwt7x83xdgytspe761pe2asw0

**Comment by ocdtrekkie** [comment]
@neynah As I said in a comment above, I'd definitely say an app market link should be included. "I see my app was last updated on Sep 3rd, I wonder if there's a newer version" currently means going separately to the app market and finding that app again.

But my caveat is #722. Some, particularly on-premises users, may choose to gate in their staff to a preprovided list or internal 'store'. And hopefully the platform will be so exciting that other markets and sources may eventually exist. So we can't assume non-Oasis servers will point to apps.sandstorm.io.

**Comment by neynah** [comment]
2nd draft, designed at 900px with sidebar. (Basically, smallest width for desktop.)

![apppage-draft2](https://cloud.githubusercontent.com/assets/855341/9827737/37500daa-589a-11e5-9c9f-fd28139ea2ed.png)

![apppage-verified-draft1](https://cloud.githubusercontent.com/assets/855341/9827832/5da98e62-589b-11e5-8695-ab5a1b89d64b.png)

**Comment by paulproteus** [comment]
Oooooooh I love the "Verified" drop-down. That's really cool IMHO.

Also are we really going to keep this "Source code" link visible up top? If
so:

1. OMG YES this is the coolest thing ever software freedom 4 life

2. It'd be nice if there were a way to hint to users that "Source Code" is
how they report a bug in the app.

**Comment by ocdtrekkie** [comment]
Could "Report Issue" or something similar be used there? We could even default to /issues for Github links. 

I think the author name being visible outside the dropdown would be nice.

**Comment by neynah** [comment]
- increased text size for legibility
- changed "Source Code" to "Source" (saves space, is it still clear what it is?)
- added "Report Issue"
- displayed author name by default

![apppage-draft3](https://cloud.githubusercontent.com/assets/855341/9892035/ec1ae1b0-5bbf-11e5-9ce5-da47c06a653a.png)
![apppage-verified-draft2](https://cloud.githubusercontent.com/assets/855341/9892039/edce64d2-5bbf-11e5-823b-6609903a1f35.png)

**Comment by ocdtrekkie** [comment]
+1 @neynah

**Comment by paulproteus** [comment]
You added a link for "Report issue" which I like in theory.

The metadata we have is "documented" here:
https://github.com/sandstorm-io/sandstorm/blob/master/src/sandstorm/package.capnp

Given that, would you send them to the contactEmail upon clicking that? Or
to the source code URL? Maybe (curious what @kentonv thinks) we should
allow contactLink to be an alternative to contactEmail and then let people
collect issues on GitHub rather than by email.

**Comment by ocdtrekkie** [comment]
Well, I think "Report Issue" should go to the source. If we wanted to be clever, we could check if the link was a Github link, and automatically make it /issues if it is.

**Comment by paulproteus** [comment]
Then if they both go the the same place, maybe it should be labeled:

"Source & issues​"

?

Or something else where it's the same UI element.

**Comment by kentonv** [comment]
Hmm. Mostly I like it, but two things that I wonder:

- It's a little sad that when we hide this information, we're not reclaiming the space for use by anything else. Is there really any benefit if the space is going to be blank otherwise? Maybe we should reduce the icon size so that everything below can be moved up into this blank space?

- I'm a little wary of writing the user's chosen display name with the word "verified" directly under it, because their display name is actually the one thing that *isn't* verified (I could set my Keybase display name to "Google, Inc.", for example). Maybe we can solve this by changing the name "verified" to something like "signature" or "show signature"?

- We need a keybase logo to put next to the keybase username.

**Comment by kentonv** [comment]
BTW @ocdtrekkie even if we remove the picture (which I guess I agree makes sense, especially since it is also not verified), we nevertheless need to call out to keybase to get the account names. Otherwise all we have is the PGP key fingerprint, which most people won't find useful.

**Comment by ocdtrekkie** [comment]
That is a valid point, @kentonv. One of the mockups moves the picture into the dropdown. Can we maybe set the concept that we should only call out to Keybase if people open it? 
Basically, then the user is specifically requesting info from Keybase, rather than the server deciding it wants to call Keybase.

**Comment by kentonv** [comment]
@ocdtrekkie The display name also comes from keybase, so we'd need to move that back into the dropdown, or remove it.

But I really want to always display the identity information at app install time, without you clicking anything, because I don't want it to be easy to click through a spoofing attack. And if we're displaying it at install time anyway, then we can cache that and not do requests later on.

If we're only calling keybase at app install time, do you still object?

**Comment by ocdtrekkie** [comment]
It's not an incredibly big deal either way (as Keybase is the sort of service unlikely to be doing insecure or unkind things), in theory, but I'd like to err on the side of assuming the server shouldn't talk to anyone. (Or that it have the option to be used without it talking to anyone.)

What happens if you upload an SPK on a local-only connection (or install via a intranet app store)? What would you like to happen there?

**Comment by kentonv** [comment]
@ocdtrekkie If there is a signature, I really want to display info about it, so that if it's something unexpected, people can say "Wait, that sounds wrong!" If we don't display it by default, I don't think most people will bother clicking anywhere to look at it.

**Comment by neynah** [comment]
Based on comments above, I'll change "Verified" to "Signature."

Are we displaying author details by default on install, and hiding it in the drop down all other times?

**Comment by neynah** [comment]
Update(also with grids):
![apppage-verified-draft3](https://cloud.githubusercontent.com/assets/855341/10032688/7e5c7dbc-6139-11e5-8e62-65f42dc7bf07.png)

**Comment by kentonv** [comment]
> Are we displaying author details by default on install, and hiding it in the drop down all other times?

That sounds good to me, yeah.
