### ISSUE TITLE
In the case of DNS issues, try restarting Sandstorm

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#895]
Right now, on my laptop, I see this message logged to the Sandstorm log:

```
Couldn't send UDP sandcats ping { [Error: getaddrinfo ESRCH] code: 'ESRCH', errno: 'ESRCH', syscall: 'getaddrinfo' }

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: getaddrinfo ESRCH
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
** Front-end died! Restarting it...
```

It's being logged in a loop, so presumably it causes Sandstorm to never fully bring up the interface.

We should fix this by being more resilient to DNS failures in the sandcats UDP ping code, but the real issue here is that `/etc/resolv.conf` changed on my system.

`sudo service sandstorm stop ; sleep 2 ; sudo service sandstorm start`

worked fine to make the error go away. This is seemingly because `run-bundle` will freshly copy `resolv.conf` in? (But I don't find evidence for that in `run-bundle`'s source code, in a quick skimming, but can look into this more in the future.)

A number of people have reported this sort of problem. Maybe it makes sense for there to be an RPC that the shell can do, so it can ask Sandstorm to make sure the right thing happens.

**Comment by paulproteus** [comment]
I see now that `etc.list` in `run-bundle.c++` controls the list of files that get copied in, and that the restarting of `node` is done all within the chroot, so what we might arguably need is a way to tell Sandstorm to re-create the chroot, rather than use the existing one.

**Comment by kentonv** [comment]
Actually, what we should probably do is bind-mount the files in etc.list rather than copy. It turns out you can bind a file over a file. This way Sandstorm would never have a stale copy. (I didn't know this was possible at the time I originally wrote the code...)

**Comment by zarvox** [comment]
I implemented the suggested patch (bind-mounting the files from etc.list), but unfortunately, bind mounts operate on the inode, whereas most editors will do the `rename(2)` dance to atomically commit the new version of the file.  This results in the child namespace seeing a deleted file when the parent namespace file is modified with a text editor.  Sadly, this also appears to be the case for `/etc/resolv.conf` getting updated by dhclient, which is probably the primary cause of issues from out-of-date `/etc/` contents.

On systems that use `resolvconf` to manage `/etc/resolv.conf`, I suspect the situation is even worse - `/etc/resolv.conf` is itself a symlink to a file in `/etc/resolvconf/run/`, so we'd bind in the symlink, but not its target, and attempts to open the file would just get `ENOENT`.

I'm not sure if there's a way to deal with the above other than maybe setting up inotify watches in the root namespace and either rebinding the mounts or replacing the files in the child namespace or something.

On the upside: most actual Sandstorm deployments aren't likely to change DNS servers that frequently, since most deployments will likely be in datacenters or in virtual machines where the address is assigned by the virtualization software, not the host's network.  That said, it's still a potential pain point for folks running with sandcats on laptops.

**Comment by paulproteus** [comment]
jorge on freenode just ran into this problem. Thought I'd leave a note here to at least indicate as much.

@zarvox your hard work digging into this is super useful.

**Comment by paulproteus** [comment]
@kentonv would you be possibly OK with the supervisor:

* Mounting all of `/etc`, or

* Adding an `LD_PRELOAD` that maps name resolution to the outside via RPC, or

* Mounting all of `/etc` as `/etc.host` and creating an empty `/etc` and using symlinks to whitelist which files we are effectively including, or

* Having the node codebase have an RPC to the supervisor that allows it to ask itself to be restarted, and having the node codebase check every ~30 seconds if DNS is broken, and if so, ask to be restarted (but presumably the supervisor should only be willing to restart it so many times per hour)

I'm not quite sure what the best approach is, but it does seem to me we should do something about this.

**Comment by kentonv** [comment]
Of those options, I'd start with the symlink approach, then maybe go to the RPC approach some day if we want to be compatible with the host glibc's nsswitch stuff. (I wouldn't implement it as an LD_PRELOAD -- glibc already gives us hooks for implementing a custom resolver, might as well use them.)

**Comment by kentonv** [comment]
Reopening because the change was reverted due to regressions. We'll try again soon.
