### ISSUE TITLE
Wildcard subdomains make SSL expensive

### ISSUE THREAD

**Issue by DanielHeath** [sandstorm-io/sandstorm#96]
If I want to run my sandstorm instance over SSL, I have to either pay $300/year for a wildcard cert or convince everyone to trust my self-signed certificates.

I assume the technical reason for the subdomains is to prevent cookies being shared?
Is there another way to achieve this?

**Comment by diracdeltas** [comment]
FWIW, I found that you can get wildcard certs for almost free with deals like http://lowendtalk.com/discussion/comment/930243. Otherwise https://www.gogetssl.com/wildcard-ssl-certificates/ lists some for <$60 per year.

**Comment by JamborJan** [comment]
For those who didn't know that yet: https://letsencrypt.org/ arriving approx. mid 2015 and the pricing question is done.

In the time being I use a cert via df.eu for 119,88 €.

**Comment by diracdeltas** [comment]
Yep, I used to sort-of work on letsencrypt :). But their chances of supporting wildcard domains for free are dubious (at least for initial launch).

**Comment by eightnoteight** [comment]
I see this is old, 
but why don't sandstorm allocate static subdomains to the applications instead of dynamic ones? that is some relief if someone like me wants to host only small number of apps.

**Comment by kentonv** [comment]
@eightnoteight Sandstorm is all about fine-grained containers. For example, every document you create with Etherpad is in its own container and therefore needs to run on a new hostname. This improves security because it means that if you have one document you share with lots of people and another document that you want to keep completely private, you do not need to worry that someone who has access to the first document could exploit a bug in Etherpad to get access to the second. (In fact, there have been multiple bugs in Etherpad lately that had this effect for non-Sandstorm users, but on Sandstorm none of these bugs were harmful.)

Moreover, we actually create a new hostname not just for every document, but for every _session_. Every time you open the document, you get a new hostname. Every user who opens the document gets a different hostname. This further improves security by mitigating XSRF, reflected XSS, and clickjacking attacks -- attacks performed by other web sites open in your browser. These attacks don't work because (usually) the other web site cannot guess the hostname of the app, since it's always different.

As you can see, all of this really does demand a wildcard.

**Comment by alisalaah** [comment]
I read through https://letsencrypt.org/ briefly and if they intend on being automated is it possible to generate an ssl cert with them (using some API) at time of creation of a grain (or later in the settings) and just make a cert for each subdomain/app?

**Comment by ocdtrekkie** [comment]
@alisalaah That's been brought up before. The big problem is that the subdomains need to be secret, or they don't work. So you can't really have certs issued for them.

**Comment by kentonv** [comment]
@alisalaah It's covered in this doc:

https://docs.sandstorm.io/en/latest/administering/wildcard/
