### ISSUE TITLE
Sign-in fails after enabling HTTPS

### ISSUE THREAD

**Issue by timmc** [sandstorm-io/sandstorm#960]
I performed the instructions to turn on HTTPS. That's working, but signins now fail.

0. Added `HTTPS_PORT=6443` and updated `BASE_URL` and `WILDCARD_HOST`
1. Updated Google and Github OAuth client registrations to new origins
2. Restarted sandstorm
3. Opened `/` on the new origin
4. Presented with sign-in page offering Google and Github options
5. Clicking either takes me to `/admin/settings` with the following message:

> You are not logged in as admin and there isn't a valid token specified. You should either log in as an admin user or generate a token from the command line by doing `sandstorm admin-token` in order to access the admin settings page. 

Additionally, the sign-in menu on the upper right for that page is a no-op -- clicking the Google and Github buttons doesn't even navigate.

I can get some traffic traces later.

**Comment by timmc** [comment]
I had failed to run `sudo sandstorm admin-token` so this ticket, as such, can likely be closed out. However, there were some other difficulties, and I'm not sure which ones deserve an issue:

- I used the admin token to sign in, but once I had unchecked and rechecked the Google option, I had to go find the client ID and secret again. It would be nice to know in advance that unchecking deconfigures, not just disables.
- I was not able to reconfigure Google and Github without generating another admin token; I think deconfiguring those login options kicked me out of the session! The message was a generic "error, go look at log" (which I could no longer do from the web.)

**Comment by paulproteus** [comment]
This is great feedback. Thank you very much for filing!​

**Comment by kentonv** [comment]
What probably happened here is that changing BASE_URL caused us to purge the OAuth configuration, which we have to do because _usually_ when people change BASE_URL they don't remember to update their OAuth config on the google/github side at the same time. Unfortunately, we have no way of detecting whether the user has done this, and the failure mode if they haven't is an unhelpfully obscure error when they try to log in (without any notification sent to Sandstorm).

But it sounds like there's definitely some bugs going on around this. The check boxes ought to have been automatically un-checked at the same time that the services were de-configured, and un-checking the services should not invalidate the admin token.

**Comment by paulproteus** [comment]
I'll assign this to me and figure out the best next steps.

**Comment by paulproteus** [comment]
I believe #1387 addresses this, so I will close it.

To quote it:

> Disables oauth services on BASE_URL change, but does not delete the config. Displays red boxes in the admin area, explaining why the services were disabled.

> Google login has been automatically disabled because BASE_URL changed. Please make sure the configuration is correct before re-enabling.

Thanks @timmc for filing this!
