### ISSUE TITLE
Restyle Notifications Dropdown

### ISSUE THREAD

**Issue by neynah** [sandstorm-io/sandstorm#992]
I'm Ok with either & can make improvements. :dancer: 

![notifications-styling1](https://cloud.githubusercontent.com/assets/855341/10376345/519f44be-6db2-11e5-8480-3aa79708cf11.png)

**Comment by jparyani** [comment]
Can we include a timestamp in there as well?

**Comment by neynah** [comment]
Oh right. One timestamp for all?

**Comment by jparyani** [comment]
Yep, it's a per notification thing.

**Comment by paulproteus** [comment]
I want to click on these and see release notes, fwiw, based on what I'm
seeing here. At least a link called "More info" that neither dismisses nor
accepts the notification.​ Or a "(i)" link after the app that takes me to
the changelog UI in the market.

**Comment by zarvox** [comment]
Implementation note: you might need to make the content have a `max-height` and `overflow: auto` so that it's always possible to get to the buttons at the bottom, even if you have like 224 app updates that you're emphatically ignoring.

**Comment by neynah** [comment]
@paulproteus Could you show me an example link for the release notes?

**Comment by paulproteus** [comment]
I ​was under the impression
https://apps.sandstorm.io/app/vfnwptfn02ty21w715snyyczw0nqxkv3jvawcah10c6z7hj1hnu0
links to it but I guess not

@kentonv why do we ask people to provide a changelog, then?
https://docs.sandstorm.io/en/latest/developing/publishing-apps/#changelog
is where we ask them to provide a changelog.

Or maybe that app just doesn't link to a changelog.

**Comment by kentonv** [comment]
@paulproteus I'd like the changelog to appear in the app market UI, but it doesn't currently.

**Comment by neynah** [comment]
Deferring to @jparyani for what's displayed in the time stamp.
![notifications-draft2](https://cloud.githubusercontent.com/assets/855341/10403012/9d914a36-6e7d-11e5-88ae-321bec37b939.png)

**Comment by kentonv** [comment]
I suppose we need a matching design for the background-processing notification too?

**Comment by neynah** [comment]
Where can I see what that currently looks like?

**Comment by kentonv** [comment]
https://alpha.sandstorm.io/install/dbed78d1ef5ed4a4f8193e829672623e?url=https://sandstorm.io/apps/jparyani/background-test-0.spk demonstrates backgrounding (note: won't actually work on Oasis currently, which is why I went with Alpha).

Here's a screenshot:

![background-notification](https://cloud.githubusercontent.com/assets/4001805/10404853/0527c916-6e8a-11e5-9ac5-7427fe32537c.png)

The purpose of the notification is to say "this grain is keeping itself alive in the background even if you don't have it open, but you can click here to cancel it". The notification cannot be dismissed without canceling, but it goes away automatically when the grain is done with its background job.

**Comment by jparyani** [comment]
This was fixed in #1026
