### ISSUE TITLE
Dev accounts should not need me to configure an email address

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#999]
Steps to reproduce:

* Install Sandstorm for the first time (in my case, via `vagrant-spk`) with dev accounts enabled
* Visit the front page
* Click "with Dev Account" to sign in with a dev account
* Log in as Alice (admin)

Expected behavior:

* I am logged in.

Actual behavior:

* I see a prompt asking me what email address Alice (admin) uses.

Screenshot:

(screenshot is of Bob, not Alice, but it's the same problem)

![email-address-prompt](https://cloud.githubusercontent.com/assets/25457/10407253/4d06e60a-6e9d-11e5-9660-10eab9875821.png)

Proposed fix:

* Give Alice an email address of `alice@example.com` rather than prompting the user.
* Do the same for the other dev accounts, too.

**Comment by zarvox** [comment]
I'm inclined to give Alice a default email address, since I see this dialog like three times a day.  However, it /is/ useful (for me, at least!) to be able to get to this view with the blocking modal with dev users for testing.  Is there maybe a happy medium here?

My general thoughts are that this page is not very usable to begin with - the topbar is missing; you can't sign out if you want to back out of agreeing to the TOS, the sidebar is present and lets you interact but won't actually do anything different until you complete the interstitial.

I think I'd be happier if we just did a proper redirect to a specific route rather than hijacking whatever your current view is.

**Comment by dwrensha** [comment]
> I think I'd be happier if we just did a proper redirect to a specific route rather than hijacking whatever your current view is.

+1. I'm going to try out this strategy for the new account settings page. (See also #970.)

**Comment by dwrensha** [comment]
Hm. A simple would lose context. E.g. a new user visiting a share link would have to re-enter the the link after confirming their profile.

**Comment by zarvox** [comment]
Yeah, you'll need to capture the original URI as some parameter, and then redirect to that (or a default page) when you're done with the interstitial.

**Comment by kentonv** [comment]
(As discussed in person a couple days ago)

It seems to me that changing the URL does not in itself solve any of the usability problems this dialog has, and all the problems can be solved just as easily without creating a new route. Meanwhile it adds some complication around preserving state.

I do agree that we should improve the usability of this dialog, e.g. not hiding logout, etc.

Note that you can run `testFirstSignup()` on the console any time you want to see this dialog again for testing purposes.

**Comment by paulproteus** [comment]
I believe this is fixed now due to @dwrensha 's work. Closing with gratitude!
